const skills = [
    {
        id: "learn-jujitsu",
        title: "Learn Jujitsu",
        description: "Master the art of grappling and close combat.",
        cost: 200,
        prerequisites: [
            { type: "skill", value: "wrestling" } // Requires the 'wrestling' skill
        ],
        consequences: [
            { type: "discount", targetChoiceId: "buy-mma-gym", value: 100 } // Gives a $100 discount on 'buy-mma-gym'
        ],
        playerUpdates: [
            { attribute: "skills", action: "add", value: "jujitsu" }
        ]
    },
    {
        id: "buy-mma-gym",
        title: "Buy MMA Gym",
        description: "Invest in a facility to train your combat skills.",
        baseCost: 1000, // Base cost
        currentCost: 1000, // This will be dynamically updated based on consequences
        prerequisites: [],
        consequences: [],
        playerUpdates: [
            { attribute: "assets", action: "add", value: "mma-gym" }
        ]
    },
    {
        id: "explore-galaxy",
        title: "Explore the Galaxy",
        description: "Embark on a journey into the unknown.",
        cost: 50,
        prerequisites: [
            { type: "fleetSize", value: 1 } // Requires at least 1 ship
        ],
        consequences: [],
        playerUpdates: [
            { attribute: "credits", action: "add", value: 500 } // Gain credits from exploration
        ]
    },
    // Skills from "Page 1 Stardust word.docx"
    {
        id: "basic-piloting",
        title: "Basic Piloting",
        description: "If you're going into space, it's probably a good idea to at least know how to fly a ship. This course will teach you the basics, and when you're through, you'll be able to adequately pilot almost any ship. Don't expect to outwit more experienced pilots, however.",
        cost: 0, // Assuming initial courses are free as per "You may take up to 6 courses..."
        prerequisites: [],
        consequences: [],
        playerUpdates: [{ attribute: "skills", action: "add", value: "basic-piloting" }]
    },
    {
        id: "ship-gunnery",
        title: "Ship Gunnery",
        description: "Learning how to fire a ship's weapons is almost an essential skill needed when space-faring. Hostiles. can find the sneakiest ways of getting you where they want you to be, so you best be prepared to defend yourself from them. You'll be able to ade- quately fire any ship weapon from this course.",
        cost: 0,
        prerequisites: [],
        consequences: [],
        playerUpdates: [{ attribute: "skills", action: "add", value: "ship-gunnery" }]
    },
    {
        id: "medical",
        title: "Medical",
        description: "People with medical knowledge are few and far between, but they're always in high demand. Having a doctor on board can improve the quality of life tenfold. Better yet, why not train yourself to become one?",
        cost: 0,
        prerequisites: [],
        consequences: [],
        playerUpdates: [{ attribute: "skills", action: "add", value: "medical" }]
    },
    {
        id: "computer-science",
        title: "Computer Science",
        description: "Information technology is heavily embedded into everything, so it's valuable knowledge to have. Especially when piloting a ship, it certainly helps to know how it works under the hood. Computer science is almost an essential skill to have for anyone hoping to travel the stars",
        cost: 0,
        prerequisites: [],
        consequences: [],
        playerUpdates: [{ attribute: "skills", action: "add", value: "computer-science" }]
    },
    {
        id: "standard-piloting",
        title: "Standard Piloting",
        description: "This course will put you through much more realistic simulations, and even take you onto the field a few times. New techniques open up a wave of new possibilities for you as an aspiring pilot, and you fly confidently enough to go toe-to-toe with other pilots out there.",
        cost: 2000000, // 2m per additional course
        prerequisites: [{ type: "skill", value: "basic-piloting" }],
        consequences: [],
        playerUpdates: [{ attribute: "skills", action: "add", value: "standard-piloting" }]
    },
    {
        id: "ship-weapon-specialization",
        title: "Ship Weapon Specialization",
        description: "This course highlights the advanced techniques in handling a certain ship weapon type. You can select either kinetic, energy, blaster, or explosive, boosting that weapon type's effectiveness when you're in command of the ship they're attached to.",
        cost: 2000000,
        prerequisites: [{ type: "skill", value: "ship-gunnery" }],
        consequences: [],
        playerUpdates: [{ attribute: "skills", action: "add", value: "ship-weapon-specialization" }]
    },
    {
        id: "mechanics",
        title: "Mechanics",
        description: "Having no mechanical knowledge on your ship can lead to a boatload of problems; it's a no-brainer to have one on board. That said, knowing how to fix things yourself can't hurt, and it helps keep your mechanic doing more important things than trying to fix your robotic leg.",
        cost: 0,
        prerequisites: [],
        consequences: [],
        playerUpdates: [{ attribute: "skills", action: "add", value: "mechanics" }]
    },
    {
        id: "cyber-security",
        title: "Cyber Security",
        description: "Take information technology a step further and into the world of info-sec. For as long humanity can remember, hacking and cyber defence has been a volatile field that requires top-of-the-line intuition and craftiness. E-war is just as dangerous as conven- tional warfare, and some argue it is more so.",
        cost: 2000000,
        prerequisites: [{ type: "skill", value: "computer-science" }],
        consequences: [],
        playerUpdates: [{ attribute: "skills", action: "add", value: "cyber-security" }]
    },
    {
        id: "advanced-piloting",
        title: "Advanced Piloting",
        description: "You're in the real world now, and you can't settle for anything less than the best when it comes to being a pilot. You'll be put in the most realistic conditions, enough that you're convinced that these are real situations they're throwing at you. Come out of this alive and you'll quickly become a respected pilot.",
        cost: 2000000,
        prerequisites: [{ type: "skill", value: "standard-piloting" }],
        consequences: [],
        playerUpdates: [{ attribute: "skills", action: "add", value: "advanced-piloting" }]
    },
    {
        id: "standard-combat-training",
        title: "Standard Combat Training",
        description: "Hand-to-hand, long-ranged, you name it. This course teaches you the basics in combat defence and offence, skills you might find invaluable one day. The universe is not a friendly place, so knowing how to fire a weapon properly can bring you a long way.",
        cost: 0,
        prerequisites: [],
        consequences: [],
        playerUpdates: [{ attribute: "skills", action: "add", value: "standard-combat-training" }]
    },
    {
        id: "nuclear",
        title: "Nuclear",
        description: "Almost every ship nowadays is powered by nuclear technology, be it through fission, fusion, or even anti- matter. At least knowing the do's and don'ts of nuclear sciences may mean the difference between life and becoming atomized into oblivion.",
        cost: 0,
        prerequisites: [],
        consequences: [],
        playerUpdates: [{ attribute: "skills", action: "add", value: "nuclear" }]
    },
    {
        id: "industry",
        title: "Industry",
        description: "All of this would not be possible if it were not for the industrious side of society. Everything from mining, refining, and processing is covered in this course. If you plan on sailing the stars to make profit off of them, then you're going to want to have this skill under your belt.",
        cost: 0,
        prerequisites: [],
        consequences: [],
        playerUpdates: [{ attribute: "skills", action: "add", value: "industry" }]
    },
    {
        id: "diplomacy",
        title: "Diplomacy",
        description: "As someone who's likely going to get into a lot of interactions with others, it's good to at least know how to handle situations into your favour. You'll become a great mediator and can convince most people you're right. After taking this course, you can hire up to 4 crew members hostile to your faction.",
        cost: 0,
        prerequisites: [],
        consequences: [{ type: "crew-hire-limit", value: 4, condition: "hostile-faction" }],
        playerUpdates: [{ attribute: "skills", action: "add", value: "diplomacy" }]
    },
    {
        id: "advanced-combat-training",
        title: "Advanced Combat Training",
        description: "Just pointing and shooting isn't enough; you need to know how to win, and this course can get you there. You'll be learning everything from valuable survival skills to the discipline of following and giving orders. You will be nothing short of a professional combat- ant in these times of conflict.",
        cost: 2000000,
        prerequisites: [{ type: "skill", value: "standard-combat-training" }],
        consequences: [],
        playerUpdates: [{ attribute: "skills", action: "add", value: "advanced-combat-training" }]
    },
    {
        id: "mind-link",
        title: "Mind-Link",
        description: "Experimental tech developed at Triglav that requires an immense amount of knowledge, patience, and fortitude to get through. With this skill, you'll be able to link your mind to your ship.",
        cost: 2000000,
        prerequisites: [
            { type: "skill", value: "medical" },
            { type: "skill", value: "mechanics" },
            { type: "skill", value: "nuclear" },
            { type: "skill", value: "advanced-piloting" },
            { type: "skill", value: "computer-science" }
        ],
        consequences: [{ type: "job-slots", value: 3 }], // Can assume 3 jobs instead of 2
        playerUpdates: [{ attribute: "skills", action: "add", value: "mind-link" }]
    },
    {
        id: "mercantile",
        title: "Mercantile",
        description: "After all is said and done, you're going to want to be able to make profit, and lots of it. It's probably a good idea to have the know-how on how to barter and trade, since the whole product of industry is to not only build society but to acquire the means to do it even better.",
        cost: 0,
        prerequisites: [],
        consequences: [],
        playerUpdates: [{ attribute: "skills", action: "add", value: "mercantile" }]
    }
];

export const titles = [
    {
        id:"title-rogue",
        title:"The Rogue",
        prerequisites: "none",
        consequences: [],
        credits: 200000000,
        description: "One or more of your crew will betray you at some point while you are adventuring the stars. You best hope you have good security personnel... unless they're the traitors. Name 5 traitors from the named crew members."
    },
    {
        id:"title-oldTimer",
        title:"The Old Timer",
        prerequisites: "none",
        consequences: {
            'energy-fusion': false, 
            'energy-mana': false,
            'energy-antiMatter': false,
            'shield-aegis': false,
            'shield-mana': false
        },
        credits: 100000000,
        description: "*Can't take nuclear fusion, mana core, or anti-matter energy *Can't take aegis or mana shields You never saw the reason to upgrade. What you have is perfect- ly fine, and you don't need anything fancier to accomplish what you do."
    },
    {
        id:"title-ghost",
        title:"The Ghost",
        prerequisites: "none",
        consequences: [],
        credits: 120000000,
        description: "For some reason, you appear as dead to all databases across the civilized galaxy. And whenever someone updates you as not dead, it reverts back the next day. This causes a lot of problems when you try to trade with others, gain acess to certain areas, or try to get people to take you seriously."
    },
    {
        id:"title-whisperer",
        title:"The Whisperer",
        prerequisites: "none",
        consequences: [],
        credits: 130000000,
        description: "It takes awhile for you to catch on, but you find out that your ship Al has began to develop a more... emotional personality. How it happened, you're not sure, but it's become moody and will reject your orders if not treated well... some- thing Al shouldn't do. It's probably best you don't piss it off."
    },
    // Titles from "Page 1 Stardust word.docx"
    {
        id: "title-the-rogue",
        title: "The Rogue",
        bonusCredits: 50000000,
        complications: [
            "One or more of your crew will betray you at some point while you are adventuring the stars. You best hope you have good security personnel... unless they're the traitors. Limited to 5 traitors total. Must be named crew members.",
            { type: "bonus-per-traitor", value: 30000000 }
        ],
        description: "One or more of your crew will betray you at some point while you are adventuring the stars. You best hope you have good security personnel... unless they're the traitors. Bonus starting credits: 50m +Every additional traitor adds 30m *Must be named crew members *Limited to 5 traitors total",
        prerequisites: [],
        consequences: []
    },
    {
        id: "title-the-old-timer",
        title: "The Old Timer",
        bonusCredits: 100000000,
        complications: [
            "Cannot take nuclear fusion, mana core, or anti-matter energy.",
            "Cannot take aegis or mana shields."
        ],
        description: "*Can't take nuclear fusion, mana core, or anti-matter energy *Can't take aegis or mana shields You never saw the reason to upgrade. What you have is perfect- ly fine, and you don't need anything fancier to accomplish what you do.",
        prerequisites: [],
        consequences: []
    },
    {
        id: "title-the-ghost",
        title: "The Ghost",
        bonusCredits: 120000000,
        complications: [
            "For some reason, you appear as dead to all databases across the civilized galaxy. And whenever someone updates you as not dead, it reverts back the next day. This causes a lot of problems when you try to trade with others, gain acess to certain areas, or try to get people to take you seriously."
        ],
        description: "For some reason, you appear as dead to all databases across the civilized galaxy. And whenever someone updates you as not dead, it reverts back the next day. This causes a lot of problems when you try to trade with others, gain acess to certain areas, or try to get people to take you seriously. Bonus starting credits: 120m",
        prerequisites: [],
        consequences: []
    },
    {
        id: "title-the-whisperer",
        title: "The Whisperer",
        bonusCredits: 130000000,
        complications: [
            "It takes awhile for you to catch on, but you find out that your ship Al has began to develop a more... emotional personality. How it happened, you're not sure, but it's become moody and will reject your orders if not treated well... some- thing Al shouldn't do. It's probably best you don't piss it off."
        ],
        description: "It takes awhile for you to catch on, but you find out that your ship Al has began to develop a more... emotional personality. How it happened, you're not sure, but it's become moody and will reject your orders if not treated well... some- thing Al shouldn't do. It's probably best you don't piss it off. Bonus starting credits: 130m",
        prerequisites: [],
        consequences: []
    },
    {
        id: "title-the-leader",
        title: "The Leader",
        bonusCredits: 140000000,
        complications: [
            "A hostile bandit group has a bone to pick with you. They will show up at the most inconvenient times, but almost never to confront you directly. Sabotage, traps, and spies await you when you least expect it. The larger your crew, the more likely they can infiltrate. You might want intimidating crew members."
        ],
        description: "A hostile bandit group has a bone to pick with you. They will show up at the most inconvenient times, but almost never to confront you directly. Sabotage, traps, and spies await you when you least expect it. The larger your crew, the more likely they can infiltrate. You might want intimidating crew members. Bonus starting credits: 140m",
        prerequisites: [],
        consequences: []
    },
    {
        id: "title-the-saint",
        title: "The Saint",
        bonusCredits: 150000000,
        complications: [
            "The notorious (former) \"Siblings of Death\" both join your crew at the same time, unbeknownst to each other. However, they don't find out until you're in the middle of space, and they hate each other's guts with a violent zeal."
        ],
        description: "The notorious (former) \"Siblings of Death\" both join your crew at the same time, unbeknownst to each other. However, they don't find out until you're in the middle of space, and they hate each other's guts with a violent zeal. Bonus starting credits: 150m +Can get Alessia (combat) and Ricce (combat) for free",
        playerUpdates: [
            { attribute: "crew", action: "add", value: "Alessia" },
            { attribute: "crew", action: "add", value: "Ricce" }
        ],
        prerequisites: [],
        consequences: []
    },
    {
        id: "title-the-berserk",
        title: "The Berserk",
        bonusCredits: 170000000,
        complications: [
            "Something's wrong with the shields of your ships, but no matter what you do, it can't be fixed. However, your weapons seem improved.",
            "All ship shields permanently lose 2 points, to a minimum of 1.",
            "Shields cannot exceed 23/25."
        ],
        description: "Something's wrong with the shields of your ships, but no matter what you do, it can't be fixed. However, your weapons seem improved. Bonus starting credits: 170m +All ship weapons permanently gain 1 point of damage per volley *All ship shields permanently lose 2 points, to a minmum of 1 *Shields cannot exceed 23/25",
        playerUpdates: [
            { attribute: "ship-weapon-damage", action: "add", value: 1 },
            { attribute: "ship-shield-strength", action: "subtract", value: 2, min: 1 },
            { attribute: "ship-shield-max", action: "set", value: 23 }
        ],
        prerequisites: [],
        consequences: []
    },
    {
        id: "title-the-nemesis",
        title: "The Nemesis",
        bonusCredits: 180000000,
        complications: [
            "Somewhere out there in the galaxy, someone sees you as the 'Perfect Rival.' They fly a similar ship or fleet doctrine that is every bit as good as yours. Their leader? A notorious pilot who has had a fearsome record of flawless victo- ries, winning with genius tact. Your hope is to not face them alone..."
        ],
        description: "Somewhere out there in the galaxy, someone sees you as the 'Perfect Rival.' They fly a similar ship or fleet doctrine that is every bit as good as yours. Their leader? A notorious pilot who has had a fearsome record of flawless victo- ries, winning with genius tact. Your hope is to not face them alone... Bonus starting credits: 180m",
        prerequisites: [],
        consequences: []
    },
    {
        id: "title-the-harbinger",
        title: "The Harbinger",
        bonusCredits: 190000000,
        complications: [
            "You get horrendously lost and come across a huge ancient space station made completely out of Herald tech. However, you find yourself surrounded by a lot of mysterious Herald vessels. You know their ships are powerful, but they don't sem happy to see you. Better make a good impression..."
        ],
        description: "You get horrendously lost and come across a huge ancient space station made completely out of Herald tech. However, you find yourself surrounded by a lot of mysterious Herald vessels. You know their ships are powerful, but they don't sem happy to see you. Better make a good impression... Bonus starting credits: 190m",
        prerequisites: [],
        consequences: []
    },
    {
        id: "title-the-prisoner",
        title: "The Prisoner",
        bonusCredits: 200000000,
        complications: [
            "You've been captured by your enemies! To your surprise, instead of imprisoning you, they force you to work for them as a ship captain, seeing your skills as one.",
            "Origin must have hostile factions.",
            "Can only hire hostile or neutral crew members.",
            "Diplomacy skill effect reversed."
        ],
        description: "You've been captured by your enemies! To your surprise, instead of imprisoning you, they force you to work for them as a ship captain, seeing your skills as one. Bonus starting credits: 200m *Origin must have hostile factions *Can only hire hostile or neutral crew members *Diplomacy skill effect reversed",
        prerequisites: [],
        consequences: []
    },
    {
        id: "title-the-space-cowboy",
        title: "The Space Cowboy",
        bonusCredits: 200000000,
        complications: [
            "Someone unsavoury actively wants your head, and they've made that knowledge public. Anyone who wants to get in good with them or has something against you will be coming after you, knowing that there's a fat bounty reward waiting for them should they succeed."
        ],
        description: "Someone unsavoury actively wants your head, and they've made that knowledge public. Anyone who wants to get in good with them or has something against you will be coming after you, knowing that there's a fat bounty reward waiting for them should they succeed. Bonus starting credits: 200m",
        prerequisites: [],
        consequences: []
    },
    {
        id: "title-the-sleeper",
        title: "The Sleeper",
        bonusCredits: 210000000,
        complications: [
            "A group of mindless but well organized and well equipped rogue drones are always at your heels, determined to assimilate you, your crew, and your ships into its hoard. Why, you're not sure. You just know they're tough to deal with, as they have an almost endless arsenal of ships and weapons."
        ],
        description: "A group of mindless but well organized and well equipped rogue drones are always at your heels, determined to assimilate you, your crew, and your ships into its hoard. Why, you're not sure. You just know they're tough to deal with, as they have an almost endless arsenal of ships and weapons. Bonus starting credits: 210m",
        prerequisites: [],
        consequences: []
    },
    {
        id: "title-the-traveler",
        title: "The Traveler",
        bonusCredits: 220000000,
        complications: [
            "A wormhole will open up at a random point in time while you are in space and swallow you whole. You will appear in unknown space with no way to indicate where you are in the vast, empty universe. You may make it back eventually, but it will take years, at the least. Maybe decades... or never."
        ],
        description: "A wormhole will open up at a random point in time while you are in space and swallow you whole. You will appear in unknown space with no way to indicate where you are in the vast, empty universe. You may make it back eventually, but it will take years, at the least. Maybe decades... or never. Bonus starting credits: 220m",
        prerequisites: [],
        consequences: []
    },
    {
        id: "title-the-guardian",
        title: "The Guardian",
        bonusCredits: 240000000,
        complications: [
            "After finding an abandoned facility on a remote moon, you find a woman. You take her in; she was put through many experiments, mostly involving mind-link tech. On hearing about this, certain shady Federation entities will seek to capture her for some reason... and also hunt you and your crew down, regardless of your standings."
        ],
        description: "After finding an abandoned facility on a remote moon, you find a woman. You take her in; she was put through many experiments, mostly involving mind-link tech. On hearing about this, certain shady Federation entities will seek to capture her for some reason... and also hunt you and your crew down, regardless of your standings. Bonus starting credits: 240m +Can get \"Hailey\" (co-pilot) for free",
        playerUpdates: [{ attribute: "crew", action: "add", value: "Hailey" }],
        prerequisites: [],
        consequences: []
    },
    {
        id: "title-the-sorcerer",
        title: "The Sorcerer",
        bonusCredits: 240000000,
        complications: [
            "While passing by wreckages littering the former Luos Syndicate, you come across an SOS signal coming from a supposed aban- doned station. You investigate and find a woman hooked up to some sort of machines. Upon saving her, the twisted, possessed pirates of the Fire Legion will try to seek and eradicate you and your crew."
        ],
        description: "While passing by wreckages littering the former Luos Syndicate, you come across an SOS signal coming from a supposed aban- doned station. You investigate and find a woman hooked up to some sort of machines. Upon saving her, the twisted, possessed pirates of the Fire Legion will try to seek and eradicate you and your crew. Bonus starting credits: 240m +Can get \"Comet\" (gunner) for free",
        playerUpdates: [{ attribute: "crew", action: "add", value: "Comet" }],
        prerequisites: [],
        consequences: []
    },
    {
        id: "title-the-hellraiser",
        title: "The Hellraiser",
        bonusCredits: 420000000,
        complications: [
            "Receive all complications from The Leader, The Nemesis, and The Space Cowboy."
        ],
        description: "Receive all complications from The Leader, The Nemesis, and The Space Cowboy. Bonus starting credits: 420m *Cannot take The Leader, The Nemesis, or The Space Cowboy",
        prerequisites: [
            { type: "not-title", value: "title-the-leader" },
            { type: "not-title", value: "title-the-nemesis" },
            { type: "not-title", value: "title-the-space-cowboy" }
        ],
        consequences: []
    },
    {
        id: "title-the-fatebreaker",
        title: "The Fatebreaker",
        bonusCredits: 420000000,
        complications: [
            "Receive all complications from The Whisperer, The Sleeper and The Traveler."
        ],
        description: "Receive all complications from The Whisperer, The Sleeper and The Traveler. Bonus starting credits: 420m *Cannot take The Whisperer, The Sleeper, or The Traveler",
        prerequisites: [
            { type: "not-title", value: "title-the-whisperer" },
            { type: "not-title", value: "title-the-sleeper" },
            { type: "not-title", value: "title-the-traveler" }
        ],
        consequences: []
    },
    {
        id: "title-the-demigod",
        title: "The Demigod",
        bonusCredits: 440000000,
        complications: [
            "Receive all complications and crew members from The Guardian and The Sorcerer."
        ],
        description: "Receive all complications and crew members from The Guardian and The Sorcerer. Bonus starting credits: 440m *Cannot take The Guardian or The Sorcerer",
        prerequisites: [
            { type: "not-title", value: "title-the-guardian" },
            { type: "not-title", value: "title-the-sorcerer" }
        ],
        consequences: []
    }
];

const origins = [
    {
        id: "origin-federation-navy",
        title: "Federation Navy",
        hostiles: ["Red Daggers", "Talons", "Luos Syndicate"],
        description: "The venerable Federation Navy is the largest military space armada in the civilized galaxy. Consisting of many thousands of ships across many hundreds of branches, there is simply no force capable going toe-to-toe with them. Granted, with such a big sovereignty, the Navy is oftentimes spread thin, mobilizing as one only for extreme circumstances. Training to be a part of the Navy is extensive, thorough and disciplined, but it's known to reward many benefits... if sailing across the stars in some of the best tech around isn't enough, that is.",
        playerUpdates: [
            { attribute: "credits", action: "add", value: 100000000 }, // Base starting credits
            { attribute: "hull-discount", faction: "Federation Navy", value: 6000000 }
        ]
    },
    {
        id: "origin-federation-spec-ops",
        title: "Federation Spec Ops Forces",
        hostiles: ["Red Daggers", "Talons", "Luos Syndicate"],
        description: "Amidst the Federation's military might are its veritable spec ops programs, and there are many to choose from. Everything from solving internal strife to deploying in the outer-rim systems where piracy is large is inclusive; your stay won't be boring. However, your identity is often concealed, your social life often thrown out the window, and you won't really have many people to talk to other than your brothers and sisters of the forces. To some, that's worth it for a handful of the best skills in the galaxy",
        playerUpdates: [
            { attribute: "credits", action: "add", value: 120000000 }, // 100m + 20m bonus
            { attribute: "hull-discount", faction: "Triglav", value: 4000000 },
            { attribute: "hull-discount", faction: "Federation Navy", value: 4000000 }
        ]
    },
    {
        id: "origin-federation-civilian",
        title: "Federation Civilian",
        hostiles: [],
        description: "Not from the military? No problem! Renowned Federation schools like Rosette University or the University of Arcadia don't offer pilot training without a reason, and that's just two of potentially thousands. Space- faring might be expensive to most people, but all it takes is a good set of skills and a healthy amount of credits to find yourself out of the atmos- phere. Many from the Federation venture out almost aimlessly, often finding themselves a part of different factions. In fact, that's how many of these factions were born.",
        playerUpdates: [
            { attribute: "credits", action: "add", value: 100000000 }
        ]
    },
    {
        id: "origin-red-dagger-pirates",
        title: "Red Dagger Pirates",
        hostiles: ["Federation", "Blackhawk Elite"],
        description: "The Red Dagger Pirates are more of a coalition of several pirate groups spanning across the entirety of the civilized galaxy. While each group or gang more or less operate independently, they all generally have good standing with each other and can collaborate when needed. When it comes time for large scale conflict, they have a surprising ability to unite and mobilize almost as a make-shift military group fairly quickly. They've established a surprisingly efficient production line and have massive networks of shipyards across the outer rims.",
        playerUpdates: [
            { attribute: "credits", action: "add", value: 100000000 },
            { attribute: "hull-discount", faction: "Red Dagger Pirates", value: 6000000 }
        ]
    },
    {
        id: "origin-talons",
        title: "Talons",
        hostiles: ["Federation", "Blackhawk Elite"],
        description: "Not much is known about the Talons to other factions, but they tend to operate within their own unknown purpose. Initially labeled as a pirate group by the Federation, the Talons are known to employ some of the greatest skilled individuals in the galaxy. They are known for their notori- ous reputation of a classy but skilled and intelligent touch. Unlike other 'pirate' groups, the Talons bolster technology that could rival the likes of the Blackhawks and Federation Spec Ops. A Talon appearance is rare and surprising, and often an indicator that something's going down.",
        playerUpdates: [
            { attribute: "credits", action: "add", value: 100000000 },
            { attribute: "hull-discount", faction: "Talon", value: 6000000 }
        ]
    },
    {
        id: "origin-luos-syndicate",
        title: "Luos Syndicate",
        hostiles: ["Federation", "Blackhawk Elite"],
        description: "It has all come tumbling down for the Syndicate. A once large collective wealthy and powerful corporations, now crumbled and bombarded to dust by the recent Federation and Blackhawk galaxy-wide assault. Originally founded under the best of intentions while even establishing a big sovereignty and culture, corruption soon ran rampant, and the Syndi- cate found itself the centre of many shady trades. While not all of its members were inherently bad, all of its surviving corps and groups split, mainly between the feuding \"Core\" and \"Outer\" rings of organizations.",
        playerUpdates: [
            { attribute: "credits", action: "add", value: 100000000 },
            { attribute: "hull-discount", faction: "Talon", value: 4000000 },
            { attribute: "hull-discount", faction: "Red Dagger", value: 4000000 },
            { attribute: "hull-discount", faction: "Luos Syndicate", value: 4000000 }
        ]
    },
    {
        id: "origin-blackhawk-elite",
        title: "Blackhawk Elite",
        hostiles: ["Red Daggers", "Talons", "Luos Syndicate"],
        description: "As a collective of many mercenary groups, the Blackhawk Elites are known as some of the most elite mercenaries out there. They spend most of their time out in the outer rims, providing protection to those out of the Federation's protective reach and need it. They come into contact with bandits and pirates alike often, but that's the life that the Black- hawks strive for. Their society is highly militaristic, focused on bleeding discipline into its members because that's the type of mindset they need.",
        playerUpdates: [
            { attribute: "credits", action: "add", value: 100000000 },
            { attribute: "hull-discount", faction: "Blackhawk Elite", value: 6000000 }
        ]
    },
    {
        id: "origin-hammerhead-industries",
        title: "Hammerhead Industries",
        hostiles: [],
        description: "As the largest hardware manufacturer in the galaxy, Hammerhead Industries have established their own colonies that are home to a lot of productive and skilled individuals. This multi-trillion credit company produces many much-needed mechanics and engineers for the ever expanding industry of space faring and exploration. Their ships are everywhere, used by civilians, security groups, PMCs, and bandits alike. Show your skills as a down and dirty soot-lover and it won't be hard to strike gold in the industry world.",
        playerUpdates: [
            { attribute: "credits", action: "add", value: 100000000 },
            { attribute: "vehicle-mech-discount", value: 2000000, min: 1000000 }
        ]
    },
    {
        id: "origin-society-of-dustkeepers",
        title: "Society of Dustkeepers",
        hostiles: [],
        description: "\"Dustkeeper\" is more of a title than a faction. However, if you ever find yourself spelunking the depths of space in search of adventure and fortune on your lonesome, you'll also find yourself talking with others like yourself very often. Whether it's for the thrill of finding things never seen before or for the heaps of credits that ancient Herald artifacts can bring you, to others, it's all the same; you're a Dustkeeper. Maybe you travel alone, or maybe you travel with a band of like-minded people. Your purpose is seldom spoken, even if you get asked about it a lot.",
        playerUpdates: [
            { attribute: "credits", action: "add", value: 100000000 },
            { attribute: "weapon-discount", type: "kinetic", tier: 2, value: 1000000 }
        ]
    },
    {
        id: "origin-beatrice-r-and-d",
        title: "Beatrice R&D",
        hostiles: [],
        description: "Easily the most renowned scientific research company, Beatrice R&D is one of the reasons that space colonization has become a thing. Full of brilliant minds that spearhead the advancement of sciences, they've become so efficient at space exploration and terraforming that they have become self-sustaining colony on their own. After earning their independence from the Federation, Beatrice R&D continues to earn its respect from all entities. If not for their passive nature, then for their promise for taking humanity into new age upon new age.",
        playerUpdates: [
            { attribute: "credits", action: "add", value: 100000000 },
            { attribute: "drone-discount", value: 1000000, min: 1000000 }
        ]
    },
    {
        id: "origin-gazer",
        title: "Gazer",
        hostiles: ["Unknown"],
        description: "Some say that getting an invitation to join the Gazers is less likely than passing some of the Federation's top SOF programs, and many wouldn't doubt that. Ominously shady with an origin unknown, Gazer operators are among the best in the galaxy, even if the group is very small. With no side but their own, they often take on the \"big guys\" despite the horren- dous number differences. Their motives? Nobody but they know, and even some Gazers claim to not even know. As far as anyone can tell, they cause a ruckus for their own amusement.",
        playerUpdates: [
            { attribute: "credits", action: "add", value: 100000000 },
            { attribute: "hull-discount", faction: "Blackhawk Elite", value: 4000000 },
            { attribute: "hull-discount", faction: "Talon", value: 4000000 },
            { attribute: "hull-discount", faction: "Triglav", value: 4000000 }
        ]
    },
    {
        id: "origin-choose-your-own-adventure",
        title: "Choose Your Own Adventure",
        hostiles: [], // User can define
        description: "Perhaps you want to have your own origins. How did you inherit the millions of credits? Who are your friends, and who are your enemies? You can choose what alignment you wish. This is your adventure, so make it your own.",
        playerUpdates: [
            { attribute: "credits", action: "add", value: 100000000 },
            { attribute: "hull-discount", value: 3000000 } // 3m off all ship hulls
        ]
    }
];

const hulls = [
    {
    id:"title-pivk2",
    title:"PI Vk2",
    manufacturer: "Pulsar Inc.",
    cost: "20m",
    spinalMount: 3,
    broadsideMount: 6,
    pointDefence: 4,
    hangarSpace: 1,
    navigation: "20/25",
    hullArmour: "02/25",
    shieldStrength: "02/25",
    length: "50m",
    maxCrew: 5,
    extraRooms: 0,
    energyUse: 2,
    Description: "The PI Vk2 is often used as a shuttle for civilian liners or a luxury yacht for wealthy businessmen. Roomy, spacious, and surprisingly comfortable, the Vk2 is an increasingly common sight."
    },

    {
    id: "ships-s92tmc",
    title: "S92-TMC",
    manufacturer: "Hammerhead Ind",
    cost: 7000000,
    spinalWeaponMounts: 3,
    broadsideTurretMounts: 2,
    pointDefenceMounts: 4,
    hangarSpace: 1,
    navigation:"20/25",
    hullArmour: "03/25",
    shieldStrength: "01/25",
    length: "18m",
    maxCrew: 1,
    energyUse: "N/A", // Energy Use is often blank in the document, setting to N/A
    },
    {
        id: "ships-s97trn",
        title: "S97-TRN",
        manufacturer: "Hammerhead Ind.",
        cost: 9000000,
        spinalWeaponMounts: 3,
        broadsideTurretMounts: 4,
        pointDefenceMounts: 3,
        hangarSpace: 0,
        navigation: "20/25",
        hullArmour: "02/25",
        shieldStrength: "01/25",
        length: "24m",
        maxCrew: 1,
        extraRooms: 0,
        energyUse: "N/A",
    },
    {
        id: "ships-beyond",
        title: "Beyond",
        manufacturer: "Beatrice R&D",
        cost: 9000000,
        spinalWeaponMounts: 3,
        broadsideTurretMounts: 2,
        pointDefenceMounts: 3,
        hangarSpace: 2,
        navigation: "24/25",
        hullArmour: "04/25",
        shieldStrength: "01/25",
        length: "16m",
        maxCrew: 2,
        extraRooms: 0,
        energyUse: "N/A",
    },
    {
        id: "ships-wasp",
        title: "Wasp",
        manufacturer: "Federation Navy",
        cost: 11000000,
        spinalWeaponMounts: 3,
        broadsideTurretMounts: 4,
        pointDefenceMounts: 2,
        hangarSpace: 0,
        navigation: "21/25",
        hullArmour: "04/25",
        shieldStrength: "01/25",
        length: "20m",
        maxCrew: 1,
        extraRooms: 0,
        energyUse: "N/A",
    },
    {
        id: "ships-moth",
        title: "Moth",
        manufacturer: "Federation Navy",
        cost: 13000000,
        spinalWeaponMounts: 2,
        broadsideTurretMounts: 4,
        pointDefenceMounts: 4,
        hangarSpace: 3,
        navigation: "18/25",
        hullArmour: "05/25",
        shieldStrength: "01/25",
        length: "26m",
        maxCrew: 2,
        extraRooms: 0,
        energyUse: "N/A",
    },
    {
        id: "ships-tomahawk",
        title: "Tomahawk",
        manufacturer: "Red Dagger Pirates",
        cost: 13000000,
        spinalWeaponMounts: 4,
        broadsideTurretMounts: 4,
        pointDefenceMounts: 2,
        hangarSpace: 0,
        navigation: "24/25",
        hullArmour: "02/25",
        shieldStrength: "01/25",
        length: "18m",
        maxCrew: 1,
        extraRooms: 0,
        energyUse: "N/A",
    },
    {
        id: "ships-pi-v17",
        title: "PI V17",
        manufacturer: "Pulsar Inc.",
        cost: 13000000,
        spinalWeaponMounts: 3,
        broadsideTurretMounts: 4,
        pointDefenceMounts: 4,
        hangarSpace: 3,
        navigation: "22/25",
        hullArmour: "04/25",
        shieldStrength: "01/25",
        length: "24m",
        maxCrew: 2,
        extraRooms: 0,
        energyUse: "N/A",
    },
    {
        id: "ships-pike",
        title: "Pike",
        manufacturer: "Red Dagger Pirates",
        cost: 15000000,
        spinalWeaponMounts: 3,
        broadsideTurretMounts: 6,
        pointDefenceMounts: 2,
        hangarSpace: 1,
        navigation: "22/25",
        hullArmour: "02/25",
        shieldStrength: "01/25",
        length: "21m",
        maxCrew: 2,
        extraRooms: 0,
        energyUse: "N/A",
    },
    {
        id: "ships-x61-stark",
        title: "X61 Stark",
        manufacturer: "Triglav Innovations",
        cost: 15000000,
        spinalWeaponMounts: 4,
        broadsideTurretMounts: 4,
        pointDefenceMounts: 2,
        hangarSpace: 2,
        navigation: "21/25",
        hullArmour: "03/25",
        shieldStrength: "03/25",
        length: "24m",
        maxCrew: 1,
        extraRooms: 0,
        energyUse: "N/A",
    },
    {
        id: "ships-knight",
        title: "Knight",
        manufacturer: "Blackhawk Elite",
        cost: 18000000,
        spinalWeaponMounts: 4,
        broadsideTurretMounts: 4,
        pointDefenceMounts: 4,
        hangarSpace: 3,
        navigation: "20/25",
        hullArmour: "05/25",
        shieldStrength: "01/25",
        length: "28m",
        maxCrew: 1,
        extraRooms: 0,
        energyUse: "N/A",
    },
    {
        id: "ships-yokai",
        title: "Yōkai",
        manufacturer: "Talons",
        cost: 18000000,
        spinalWeaponMounts: 4,
        broadsideTurretMounts: 6,
        pointDefenceMounts: 4,
        hangarSpace: 0,
        navigation: "22/25",
        hullArmour: "03/25",
        shieldStrength: "01/25",
        length: "23m",
        maxCrew: 1,
        extraRooms: 0,
        energyUse: "N/A",
    },
    {
        id: "ships-scab",
        title: "\"Scab\"",
        manufacturer: "Heralds",
        cost: 30000000,
        spinalWeaponMounts: 5,
        broadsideTurretMounts: 6,
        pointDefenceMounts: 2,
        hangarSpace: 2,
        navigation: "23/25",
        hullArmour: "06/25",
        shieldStrength: "03/25",
        length: "25m",
        maxCrew: 2,
        extraRooms: 0,
        energyUse: "N/A",
    },
    // FRIGATES
    {
        id: "ships-s47ltm",
        title: "S47-LTM",
        manufacturer: "Hammerhead Ind.",
        cost: 18000000,
        spinalWeaponMounts: 3,
        broadsideTurretMounts: 6,
        pointDefenceMounts: 4,
        hangarSpace: 4,
        navigation: "15/25",
        hullArmour: "06/25",
        shieldStrength: "02/25",
        length: "120m",
        maxCrew: 12,
        extraRooms: 7,
        energyUse: "N/A",
    },
    {
        id: "ships-m8gg",
        title: "M8-GG",
        manufacturer: "Hammerhead Ind.",
        cost: 20000000,
        spinalWeaponMounts: 3,
        broadsideTurretMounts: 8,
        pointDefenceMounts: 3,
        hangarSpace: 3,
        navigation: "16/25",
        hullArmour: "05/25",
        shieldStrength: "03/25",
        length: "135m",
        maxCrew: 10,
        extraRooms: 9,
        energyUse: "DOOS",
    },
    {
        id: "ships-rusalka",
        title: "Rusalka",
        manufacturer: "Talons",
        cost: 34000000,
        spinalWeaponMounts: 4,
        broadsideTurretMounts: 12,
        pointDefenceMounts: 5,
        hangarSpace: 3,
        navigation: "17/25",
        hullArmour: "07/25",
        shieldStrength: "03/25",
        length: "139m",
        maxCrew: 12,
        extraRooms: 8,
        energyUse: "N/A",
    },
    {
        id: "ships-grin",
        title: "\"Grin\"",
        manufacturer: "Heralds",
        cost: 60000000,
        spinalWeaponMounts: 5,
        broadsideTurretMounts: 12,
        pointDefenceMounts: 2,
        hangarSpace: 5,
        navigation: "18/25",
        hullArmour: "09/25",
        shieldStrength: "04/25",
        length: "132m",
        maxCrew: 9,
        extraRooms: 8,
        energyUse: "DOOS",
    },
    // DESTROYERS
    {
        id: "ships-k792un4",
        title: "K792-UN4",
        manufacturer: "Hammerhead Ind.",
        cost: 24000000,
        spinalWeaponMounts: 5,
        broadsideTurretMounts: 8,
        pointDefenceMounts: 6,
        hangarSpace: 8,
        navigation: "12/25",
        hullArmour: "10/25",
        shieldStrength: "03/25",
        length: "210m",
        maxCrew: 32,
        extraRooms: 10,
        energyUse: "N/A",
    },
    {
        id: "ships-v77slt",
        title: "V77-SLT",
        manufacturer: "Hammerhead Ind.",
        cost: 26000000,
        spinalWeaponMounts: 5,
        broadsideTurretMounts: 10,
        pointDefenceMounts: 3,
        hangarSpace: 5,
        navigation: "12/25",
        hullArmour: "10/25",
        shieldStrength: "04/25",
        length: "240m",
        maxCrew: 40,
        extraRooms: 12,
        energyUse: "N/A",
    },
    {
        id: "ships-voyage",
        title: "Voyage",
        manufacturer: "Beatrice R&D",
        cost: 26000000,
        spinalWeaponMounts: 5,
        broadsideTurretMounts: 8,
        pointDefenceMounts: 4,
        hangarSpace: 9,
        navigation: "13/25",
        hullArmour: "10/25",
        shieldStrength: "04/25",
        length: "242m",
        maxCrew: 46,
        extraRooms: 15,
        energyUse: "N/A",
    },
    {
        id: "ships-dart",
        title: "Dart",
        manufacturer: "Red Dagger Pirates",
        cost: 28000000,
        spinalWeaponMounts: 5,
        broadsideTurretMounts: 10,
        pointDefenceMounts: 5,
        hangarSpace: 6,
        navigation: "16/25",
        hullArmour: "09/25",
        shieldStrength: "04/25",
        length: "223m",
        maxCrew: 38,
        extraRooms: 10,
        energyUse: "N/A",
    },
    {
        id: "ships-wolf",
        title: "Wolf",
        manufacturer: "Federation Navy",
        cost: 28000000,
        spinalWeaponMounts: 5,
        broadsideTurretMounts: 8,
        pointDefenceMounts: 5,
        hangarSpace: 10,
        navigation: "10/25",
        hullArmour: "12/25",
        shieldStrength: "04/25",
        length: "236m",
        maxCrew: 44,
        extraRooms: 13,
        energyUse: "DOO",
    },
    {
        id: "ships-longbow",
        title: "Longbow",
        manufacturer: "Red Dagger Pirates",
        cost: 30000000,
        spinalWeaponMounts: 6,
        broadsideTurretMounts: 10,
        pointDefenceMounts: 4,
        hangarSpace: 6,
        navigation: "14/25",
        hullArmour: "10/25",
        shieldStrength: "04/25",
        length: "235m",
        maxCrew: 42,
        extraRooms: 12,
        energyUse: "N/A",
    },
    {
        id: "ships-vulture",
        title: "Vulture",
        manufacturer: "Federation Navy",
        cost: 30000000,
        spinalWeaponMounts: 5,
        broadsideTurretMounts: 14,
        pointDefenceMounts: 6,
        hangarSpace: 6,
        navigation: "11/25",
        hullArmour: "13/25",
        shieldStrength: "04/25",
        length: "229m",
        maxCrew: 42,
        extraRooms: 12,
        energyUse: "DOO",
    },
    {
        id: "ships-pi-vd3",
        title: "PI Vd3",
        manufacturer: "Pulsar Inc.",
        cost: 32000000,
        spinalWeaponMounts: 5,
        broadsideTurretMounts: 12,
        pointDefenceMounts: 7,
        hangarSpace: 10,
        navigation: "13/25",
        hullArmour: "11/25",
        shieldStrength: "04/25",
        length: "252m",
        maxCrew: 56,
        extraRooms: 15,
        energyUse: "DOOS",
    },
    {
        id: "ships-x33-tribe",
        title: "X33 Tribe",
        manufacturer: "Triglav Innovations",
        cost: 36000000,
        spinalWeaponMounts: 6,
        broadsideTurretMounts: 12,
        pointDefenceMounts: 6,
        hangarSpace: 7,
        navigation: "13/25",
        hullArmour: "12/25",
        shieldStrength: "04/25",
        length: "247m",
        maxCrew: 44,
        extraRooms: 14,
        energyUse: "N/A",
    },
    {
        id: "ships-viking",
        title: "Viking",
        manufacturer: "Blackhawk Elite",
        cost: 42000000,
        spinalWeaponMounts: 5,
        broadsideTurretMounts: 14,
        pointDefenceMounts: 5,
        hangarSpace: 11,
        navigation: "10/25",
        hullArmour: "14/25",
        shieldStrength: "04/25",
        length: "255m",
        maxCrew: 48,
        extraRooms: 13,
        energyUse: "DOOD",
    },
    {
        id: "ships-acheri",
        title: "Acheri",
        manufacturer: "Talons",
        cost: 45000000,
        spinalWeaponMounts: 6,
        broadsideTurretMounts: 14,
        pointDefenceMounts: 6,
        hangarSpace: 7,
        navigation: "14/25",
        hullArmour: "11/25",
        shieldStrength: "04/25",
        length: "244m",
        maxCrew: 46,
        extraRooms: 12,
        energyUse: "N/A",
    },
    {
        id: "ships-carapace",
        title: "\"Carapace\"",
        manufacturer: "Heralds",
        cost: 70000000,
        spinalWeaponMounts: 7,
        broadsideTurretMounts: 14,
        pointDefenceMounts: 5,
        hangarSpace: 10,
        navigation: "16/25",
        hullArmour: "13/25",
        shieldStrength: "05/25",
        length: "237m",
        maxCrew: 36,
        extraRooms: 12,
        energyUse: "N/A",
    },
    // CRUISERS
    {
        id: "ships-s07dd",
        title: "S07-DD",
        manufacturer: "Hammerhead Ind.",
        cost: 40000000,
        spinalWeaponMounts: 3,
        broadsideTurretMounts: 12,
        pointDefenceMounts: 4,
        hangarSpace: 7,
        navigation: "06/25",
        hullArmour: "15/25",
        shieldStrength: "05/25",
        length: "498m",
        maxCrew: 280,
        extraRooms: 14,
        energyUse: "N/A",
    },
    {
        id: "ships-tco7b",
        title: "TCO-7B",
        manufacturer: "Hammerhead Ind.",
        cost: 42000000,
        spinalWeaponMounts: 2,
        broadsideTurretMounts: 10,
        pointDefenceMounts: 8,
        hangarSpace: 10,
        navigation: "05/25",
        hullArmour: "13/25",
        shieldStrength: "06/25",
        length: "512m",
        maxCrew: 300,
        extraRooms: 14,
        energyUse: "D",
    },
    {
        id: "ships-prospect",
        title: "Prospect",
        manufacturer: "Beatrice R&D",
        cost: 44000000,
        spinalWeaponMounts: 2,
        broadsideTurretMounts: 8,
        pointDefenceMounts: 8,
        hangarSpace: 9,
        navigation: "08/25",
        hullArmour: "13/25",
        shieldStrength: "07/25",
        length: "480m",
        maxCrew: 320,
        extraRooms: 16,
        energyUse: "N/A",
    },
    {
        id: "ships-manticore",
        title: "Manticore",
        manufacturer: "Federation Navy",
        cost: 48000000,
        spinalWeaponMounts: 2,
        broadsideTurretMounts: 18,
        pointDefenceMounts: 4,
        hangarSpace: 14,
        navigation: "06/25",
        hullArmour: "14/25",
        shieldStrength: "06/25",
        length: "491m",
        maxCrew: 310,
        extraRooms: 13,
        energyUse: "N/A",
    },
    {
        id: "ships-chimera",
        title: "Chimera",
        manufacturer: "Federation Navy",
        cost: 48000000,
        spinalWeaponMounts: 2,
        broadsideTurretMounts: 12,
        pointDefenceMounts: 14,
        hangarSpace: 8,
        navigation: "04/25",
        hullArmour: "16/25",
        shieldStrength: "06/25",
        length: "488m",
        maxCrew: 290,
        extraRooms: 14,
        energyUse: "N/A",
    },
    {
        id: "ships-glaive",
        title: "Glaive",
        manufacturer: "Red Dagger Pirates",
        cost: 52000000,
        spinalWeaponMounts: 3,
        broadsideTurretMounts: 18,
        pointDefenceMounts: 4,
        hangarSpace: 14,
        navigation: "08/25",
        hullArmour: "12/25",
        shieldStrength: "06/25",
        length: "502m",
        maxCrew: 280,
        extraRooms: 12,
        energyUse: "N/A",
    },
    {
        id: "ships-pi-vc9",
        title: "PI VC9",
        manufacturer: "Pulsar Inc.",
        cost: 54000000,
        spinalWeaponMounts: 2,
        broadsideTurretMounts: 14,
        pointDefenceMounts: 9,
        hangarSpace: 17,
        navigation: "06/25",
        hullArmour: "15/25",
        shieldStrength: "07/25",
        length: "523m",
        maxCrew: 340,
        extraRooms: 17,
        energyUse: "N/A",
    },
    {
        id: "ships-x21-riptide",
        title: "X21 Riptide",
        manufacturer: "Triglav Innovations",
        cost: 58000000,
        spinalWeaponMounts: 2,
        broadsideTurretMounts: 18,
        pointDefenceMounts: 6,
        hangarSpace: 10,
        navigation: "15/25",
        hullArmour: "14/25",
        shieldStrength: "06/25",
        length: "514m",
        maxCrew: 310,
        extraRooms: 14,
        energyUse: "D",
    },
    {
        id: "ships-orestes",
        title: "Orestes",
        manufacturer: "Luos Syndicate",
        cost: 60000000,
        spinalWeaponMounts: 3,
        broadsideTurretMounts: 20,
        pointDefenceMounts: 6,
        hangarSpace: 10,
        navigation: "05/25",
        hullArmour: "15/25",
        shieldStrength: "06/25",
        length: "480m",
        maxCrew: 320,
        extraRooms: 15,
        energyUse: "N/A",
    },
    {
        id: "ships-myrmidon",
        title: "Myrmidon",
        manufacturer: "Blackhawk Elite",
        cost: 54000000,
        spinalWeaponMounts: 4,
        broadsideTurretMounts: 20,
        pointDefenceMounts: 8,
        hangarSpace: 13,
        navigation: "03/25",
        hullArmour: "18/25",
        shieldStrength: "07/25",
        length: "535m",
        maxCrew: 340,
        extraRooms: 15,
        energyUse: "N/A",
    },
    {
        id: "ships-erel",
        title: "Er'el",
        manufacturer: "Talons",
        cost: 66000000,
        spinalWeaponMounts: 5,
        broadsideTurretMounts: 22,
        pointDefenceMounts: 6,
        hangarSpace: 10,
        navigation: "06/25",
        hullArmour: "14/25",
        shieldStrength: "07/25",
        length: "527m",
        maxCrew: 300,
        extraRooms: 14,
        energyUse: "N/A",
    },
    {
        id: "ships-waltz",
        title: "\"Waltz\"",
        manufacturer: "Heralds",
        cost: 92000000,
        spinalWeaponMounts: 5,
        broadsideTurretMounts: 24,
        pointDefenceMounts: 4,
        hangarSpace: 13,
        navigation: "07/25",
        hullArmour: "16/25",
        shieldStrength: "08/25",
        length: "509m",
        maxCrew: 290,
        extraRooms: 14,
        energyUse: "N/A",
    },
    // BATTLESHIPS
    {
        id: "ships-excursion",
        title: "Excursion",
        manufacturer: "Beatrice R&D",
        cost: 60000000,
        spinalWeaponMounts: 1,
        broadsideTurretMounts: 24,
        pointDefenceMounts: 10,
        hangarSpace: 21,
        navigation: "03/25",
        hullArmour: "17/25",
        shieldStrength: "07/25",
        length: "878m",
        maxCrew: 1900,
        extraRooms: 15,
        energyUse: "N/A",
    },
    {
        id: "ships-g8bs",
        title: "G8-BS",
        manufacturer: "Hammerhead Ind.",
        cost: 62000000,
        spinalWeaponMounts: 1,
        broadsideTurretMounts: 26,
        pointDefenceMounts: 12,
        hangarSpace: 24,
        navigation: "01/25",
        hullArmour: "20/25",
        shieldStrength: "07/25",
        length: "1.1km",
        maxCrew: 2200,
        extraRooms: 18,
        energyUse: "DODO",
    },
    {
        id: "ships-ogre",
        title: "Ogre",
        manufacturer: "Federation Navy",
        cost: 70000000,
        spinalWeaponMounts: 1,
        broadsideTurretMounts: 22,
        pointDefenceMounts: 12,
        hangarSpace: 15,
        navigation: "03/25",
        hullArmour: "18/25",
        shieldStrength: "07/25",
        length: "1.1km",
        maxCrew: 2400,
        extraRooms: 18,
        energyUse: "N/A",
    },
    {
        id: "ships-halberd",
        title: "Halberd",
        manufacturer: "Red Dagger Pirates",
        cost: 72000000,
        spinalWeaponMounts: 1,
        broadsideTurretMounts: 22,
        pointDefenceMounts: 12,
        hangarSpace: 24,
        navigation: "01/25",
        hullArmour: "18/25",
        shieldStrength: "08/25",
        length: "1.1km",
        maxCrew: 2100,
        extraRooms: 16,
        energyUse: "N/A",
    },
    {
        id: "ships-pi-vb6",
        title: "PI Vb6",
        manufacturer: "Pulsar Inc.",
        cost: 70000000,
        spinalWeaponMounts: 2,
        broadsideTurretMounts: 30,
        pointDefenceMounts: 6,
        hangarSpace: 15,
        navigation: "03/25",
        hullArmour: "20/25",
        shieldStrength: "08/25",
        length: "1.2km",
        maxCrew: 2500,
        extraRooms: 19,
        energyUse: "DOODOX",
    },
    {
        id: "ships-skinwalker",
        title: "Skinwalker",
        manufacturer: "Federation Navy",
        cost: 74000000,
        spinalWeaponMounts: 1,
        broadsideTurretMounts: 26,
        pointDefenceMounts: 12,
        hangarSpace: 24,
        navigation: "03/25",
        hullArmour: "18/25",
        shieldStrength: "07/25",
        length: "1km",
        maxCrew: 2200,
        extraRooms: 17,
        energyUse: "N/A",
    },
    {
        id: "ships-troilus",
        title: "Troilus",
        manufacturer: "Luos Syndicate",
        cost: 85000000,
        spinalWeaponMounts: 1,
        broadsideTurretMounts: 30,
        pointDefenceMounts: 9,
        hangarSpace: 18,
        navigation: "02/25",
        hullArmour: "17/25",
        shieldStrength: "07/25",
        length: "994m",
        maxCrew: 2300,
        extraRooms: 17,
        energyUse: "N/A",
    },
    {
        id: "ships-x7-phantom",
        title: "X7 Phantom",
        manufacturer: "Triglav Innovations",
        cost: 96000000,
        spinalWeaponMounts: 2,
        broadsideTurretMounts: 28,
        pointDefenceMounts: 6,
        hangarSpace: 18,
        navigation: "02/25",
        hullArmour: "17/25",
        shieldStrength: "07/25",
        length: "1km",
        maxCrew: 2100,
        extraRooms: 17,
        energyUse: "N/A",
    },
    {
        id: "ships-razertail",
        title: "Razertail",
        manufacturer: "Luos Syndicate",
        cost: 100000000,
        spinalWeaponMounts: 2,
        broadsideTurretMounts: 30,
        pointDefenceMounts: 8,
        hangarSpace: 21,
        navigation: "03/25",
        hullArmour: "20/25",
        shieldStrength: "08/25",
        length: "1.2km",
        maxCrew: 2400,
        extraRooms: 18,
        energyUse: "N/A",
    },
    {
        id: "ships-paladin",
        title: "Paladin",
        manufacturer: "Blackhawk Elite",
        cost: 105000000,
        spinalWeaponMounts: 2,
        broadsideTurretMounts: 32,
        pointDefenceMounts: 11,
        hangarSpace: 18,
        navigation: "03/25",
        hullArmour: "22/25",
        shieldStrength: "09/25",
        length: "1.4km",
        maxCrew: 2500,
        extraRooms: 19,
        energyUse: "N/A",
    },
    {
        id: "ships-ophanim",
        title: "Ophanim",
        manufacturer: "Talons",
        cost: 112000000,
        spinalWeaponMounts: 2,
        broadsideTurretMounts: 30,
        pointDefenceMounts: 10,
        hangarSpace: 23,
        navigation: "08/25",
        hullArmour: "19/25",
        shieldStrength: "08/25",
        length: "1.6km",
        maxCrew: 2200,
        extraRooms: 17,
        energyUse: "N/A",
    },
    {
        id: "ships-pyramid",
        title: "\"Pyramid\"",
        manufacturer: "Heralds",
        cost: 150000000,
        spinalWeaponMounts: 3,
        broadsideTurretMounts: 32,
        pointDefenceMounts: 10,
        hangarSpace: 26,
        navigation: "03/25",
        hullArmour: "23/25",
        shieldStrength: "10/25",
        length: "1.6km",
        maxCrew: 2300,
        extraRooms: 19,
        energyUse: "N/A",
    },
    // CARRIERS
    {
        id: "ships-id9f",
        title: "ID-9F",
        manufacturer: "Hammerhead Ind.",
        cost: 78000000,
        spinalWeaponMounts: 0,
        broadsideTurretMounts: 0,
        pointDefenceMounts: 10,
        hangarSpace: 54,
        navigation: "02/25",
        hullArmour: "19/25",
        shieldStrength: "08/25",
        length: "1.6km",
        maxCrew: 2800,
        extraRooms: 18,
        energyUse: "N/A",
    },
    {
        id: "ships-abyss",
        title: "Abyss",
        manufacturer: "Beatrice R&D",
        cost: 80000000,
        spinalWeaponMounts: 0,
        broadsideTurretMounts: 0,
        pointDefenceMounts: 15,
        hangarSpace: 52,
        navigation: "19/25",
        hullArmour: "08/25",
        shieldStrength: "07/25",
        length: "1.6km",
        maxCrew: 2800,
        extraRooms: 18,
        energyUse: "N/A",
    },
    {
        id: "ships-typhon",
        title: "Typhon",
        manufacturer: "Federation Navy",
        cost: 90000000,
        spinalWeaponMounts: 0,
        broadsideTurretMounts: 0,
        pointDefenceMounts: 13,
        hangarSpace: 54,
        navigation: "01/25",
        hullArmour: "21/25",
        shieldStrength: "09/25",
        length: "1.7km",
        maxCrew: 3000,
        extraRooms: 22,
        energyUse: "DODDOX",
    },
    {
        id: "ships-ouranos",
        title: "Ouranos",
        manufacturer: "Luos Syndicate",
        cost: 100000000,
        spinalWeaponMounts: 0,
        broadsideTurretMounts: 0,
        pointDefenceMounts: 12,
        hangarSpace: 60,
        navigation: "01/25",
        hullArmour: "22/25",
        shieldStrength: "08/25",
        length: "1.7km",
        maxCrew: 2700,
        extraRooms: 17,
        energyUse: "N/A",
    },
    {
        id: "ships-asmodai",
        title: "Asmodai",
        manufacturer: "Talons",
        cost: 100000000,
        spinalWeaponMounts: 0,
        broadsideTurretMounts: 6,
        pointDefenceMounts: 16,
        hangarSpace: 50,
        navigation: "01/25",
        hullArmour: "20/25",
        shieldStrength: "08/25",
        length: "2.2km",
        maxCrew: 3200,
        extraRooms: 19,
        energyUse: "N/A",
    },
    {
        id: "ships-gae-bulg",
        title: "Gáe Bulg",
        manufacturer: "Blackhawk Elite",
        cost: 120000000,
        spinalWeaponMounts: 1,
        broadsideTurretMounts: 0, // Assuming blank means 0 for carriers
        pointDefenceMounts: 16,
        hangarSpace: 66,
        navigation: "01/25",
        hullArmour: "19/25",
        shieldStrength: "08/25",
        length: "2.5km",
        maxCrew: 3800,
        extraRooms: 20,
        energyUse: "N/A",
    },
    // DREADNOUGHTS
    {
        id: "ships-gungnir",
        title: "Gungnir",
        manufacturer: "Blackhawk Elite",
        cost: 300000000,
        spinalWeaponMounts: 5,
        broadsideTurretMounts: 36,
        pointDefenceMounts: 16,
        hangarSpace: 38,
        navigation: "00/25",
        hullArmour: "40/25",
        shieldStrength: "10/25",
        length: "6.5km",
        maxCrew: 6000,
        extraRooms: 32,
        energyUse: "N/A",
    },
    {
        id: "ships-dhyana",
        title: "Dhyana",
        manufacturer: "Triglav Innovations",
        cost: 340000000,
        spinalWeaponMounts: 6,
        broadsideTurretMounts: 42,
        pointDefenceMounts: 14,
        hangarSpace: 28,
        navigation: "00/25",
        hullArmour: "34/25",
        shieldStrength: "10/25",
        length: "7km",
        maxCrew: 5600,
        extraRooms: 30,
        energyUse: "N/A",
    },
    {
        id: "ships-azrael",
        title: "Azrael",
        manufacturer: "Luos Syndicate & Talons",
        cost: 370000000,
        spinalWeaponMounts: 7,
        broadsideTurretMounts: 48,
        pointDefenceMounts: 12,
        hangarSpace: 26,
        navigation: "00/25",
        hullArmour: "33/25",
        shieldStrength: "09/25",
        length: "7km",
        maxCrew: 5400,
        extraRooms: 28,
        energyUse: "N/A",
    },
    {
        id: "ships-mothership",
        title: "\"Mothership\"",
        manufacturer: "Heralds",
        cost: 470000000,
        spinalWeaponMounts: 8,
        broadsideTurretMounts: 44,
        pointDefenceMounts: 15,
        hangarSpace: 42,
        navigation: "00/25",
        hullArmour: "38/25",
        shieldStrength: "10/25",
        length: "8.5km",
        maxCrew: 6000,
        extraRooms: 36,
        energyUse: "N/A",
    },
    // Additional ships from Page 2 Stardust.md
    {
        id: "ships-pi-v18",
        title: "PI V18",
        manufacturer: "Pulsar Inc.",
        cost: 15000000,
        spinalWeaponMounts: 4,
        broadsideTurretMounts: 4,
        pointDefenceMounts: 4,
        hangarSpace: 3,
        navigation: "04/25",
        hullArmour: "02/25",
        shieldStrength: "01/25",
        length: "24m",
        maxCrew: 2,
        extraRooms: 0,
        energyUse: 1,
        description: "Integrated PI Control V6 may be installed without occupying slots. Although Pulsar's next generation fighter is only in an incremental improvement on its previous efforts, the integrated PIO system is a classy touch that leaves room for a second command module. It is still very comfortable, and has a cozy cabin area for longer voyages."
    },
    {
        id: "ships-x66-omen",
        title: "X66 \"Omen\"",
        manufacturer: "Triglav Innovations",
        cost: 20000000,
        spinalWeaponMounts: 3,
        broadsideTurretMounts: 4,
        pointDefenceMounts: 2,
        hangarSpace: 1,
        navigation: "24/25",
        hullArmour: "02/25",
        shieldStrength: "02/25",
        length: "18m",
        maxCrew: 1,
        extraRooms: 0,
        energyUse: 1,
        description: "May perform missions for a mech, dropship, or drone. Incorporates integrated power capacitor to X66. With both automated flight and extended reconnaissance. While capable of carrying a pilot, it doesn't like it."
    },
    {
        id: "ships-cygnus",
        title: "Cygnus",
        manufacturer: "Talons",
        cost: 30000000,
        spinalWeaponMounts: 4,
        broadsideTurretMounts: 6,
        pointDefenceMounts: 2,
        hangarSpace: 3,
        navigation: "22/25",
        hullArmour: "02/25",
        shieldStrength: "02/25",
        length: "23m",
        maxCrew: 2,
        extraRooms: 0,
        energyUse: 1,
        description: "Digital Security may be installed without occupying slots. Recognizing the increasing uselessness of drone warfare, the Talon developed the Cygnus command and control fighter. It is fast and has a good range. The Federation finds the recent advances in the sophistication of Talon engineering concerning."
    },
    {
        id: "ships-scorpion",
        title: "Scorpion",
        manufacturer: "Heralds",
        cost: 36000000,
        spinalWeaponMounts: 4,
        broadsideTurretMounts: 6,
        pointDefenceMounts: 2,
        hangarSpace: 3,
        navigation: "24/25",
        hullArmour: "02/25",
        shieldStrength: "02/25",
        length: "25m",
        maxCrew: 2,
        extraRooms: 0,
        energyUse: 2,
        description: "May perform missions for a mech, dropship, or submarine. The \"Scorpion\" is a multi-environment fighter whose field-linked modules allow it to operate effectively in an atmosphere and perform a wide variety of tasks."
    },
    {
        id: "ships-hermes",
        title: "Hermes",
        manufacturer: "Beatrice R&D",
        cost: 16000000,
        spinalWeaponMounts: 2,
        broadsideTurretMounts: 6,
        pointDefenceMounts: 4,
        hangarSpace: 2,
        navigation: "21/25",
        hullArmour: "02/25",
        shieldStrength: "02/25",
        length: "49m",
        maxCrew: 5,
        extraRooms: 1,
        energyUse: 2,
        description: "The Hermes is useful as a shuttle or scout craft for Beatrice's larger ships. But it has also become a popular courier ship on its own merits."
    },
    {
        id: "ships-dirk",
        title: "Dirk",
        manufacturer: "Red Dagger Pirates",
        cost: 19000000,
        spinalWeaponMounts: 4,
        broadsideTurretMounts: 2,
        pointDefenceMounts: 1,
        hangarSpace: 1,
        navigation: "23/25",
        hullArmour: "02/25",
        shieldStrength: "02/25",
        length: "46m",
        maxCrew: 3,
        extraRooms: 0,
        energyUse: 2,
        description: "Don't be fooled by its small size. The Dirk never travels alone. These scout ships are always on the lookout for new prey, and are notorious for jamming a victim's warp drive while calling in their mothership for the kill."
    },
    {
        id: "ships-morning-star",
        title: "Morning Star",
        manufacturer: "Talons",
        cost: 28000000,
        spinalWeaponMounts: 4,
        broadsideTurretMounts: 10,
        pointDefenceMounts: 2,
        hangarSpace: 1,
        navigation: "20/25",
        hullArmour: "02/25",
        shieldStrength: "02/25",
        length: "65m",
        maxCrew: 8,
        extraRooms: 0,
        energyUse: 2,
        description: "The Morning Star is one of the earliest corvettes, and one of the most successful. Highly adaptable, it can fill the role of scout, interceptor, light support, heavy fighter, or planetary landing craft."
    },
    {
        id: "ships-shrike",
        title: "Shrike",
        manufacturer: "Heralds",
        cost: 45000000,
        spinalWeaponMounts: 5,
        broadsideTurretMounts: 10,
        pointDefenceMounts: 2,
        hangarSpace: 1,
        navigation: "21/25",
        hullArmour: "07/25",
        shieldStrength: "03/25",
        length: "70m",
        maxCrew: 10,
        extraRooms: 0,
        energyUse: 3,
        description: "The Shrike is usually found as a plaything of the super rich, who take pains to outfit them in the most expensive way possible."
    },
    {
        id: "ships-medusa",
        title: "Medusa",
        manufacturer: "Heralds",
        cost: 74000000,
        spinalWeaponMounts: 6,
        broadsideTurretMounts: 14,
        pointDefenceMounts: 8,
        hangarSpace: 10,
        navigation: "17/25",
        hullArmour: "12/25",
        shieldStrength: "05/25",
        length: "245m",
        maxCrew: 42,
        extraRooms: 1,
        energyUse: 4,
        description: "Fast and deadly, the \"Medusa\" is the quintessential raider. However the large number of point-defense mounts suggest the Heralds designed it as an escort vessel."
    },
    {
        id: "ships-rapier",
        title: "Rapier",
        manufacturer: "Red Dagger",
        cost: 40000000,
        spinalWeaponMounts: 5,
        broadsideTurretMounts: 14,
        pointDefenceMounts: 5,
        hangarSpace: 7,
        navigation: "12/25",
        hullArmour: "11/25",
        shieldStrength: "05/25",
        length: "349m",
        maxCrew: 11,
        extraRooms: 4,
        energyUse: 4,
        description: "Introduced in the battle of BRSRB-4, the Rapier quickly became the pirates’ favorite heavy skirmish vessel."
    },
    {
        id: "ships-pi-vc11",
        title: "PI Vc11",
        manufacturer: "Pulsar Inc.",
        cost: 49000000,
        spinalWeaponMounts: 5,
        broadsideTurretMounts: 16,
        pointDefenceMounts: 7,
        hangarSpace: 10,
        navigation: "10/25",
        hullArmour: "12/25",
        shieldStrength: "05/25",
        length: "364m",
        maxCrew: 15,
        extraRooms: 4,
        energyUse: 4,
        description: "Intent on overtaking Triglav’s technological lead, Pulsar Inc. engaged with a new partner to develop the PI Vc11 light cruiser. These compact, highly efficient ships retain Pulsar’s signature space-saving refinements while incorporating a more martial configuration."
    },
    {
        id: "ships-fury",
        title: "Fury",
        manufacturer: "Talons",
        cost: 64000000,
        spinalWeaponMounts: 6,
        broadsideTurretMounts: 18,
        pointDefenceMounts: 6,
        hangarSpace: 8,
        navigation: "11/25",
        hullArmour: "12/25",
        shieldStrength: "05/25",
        length: "360m",
        maxCrew: 12,
        extraRooms: 4,
        energyUse: 4,
        description: "Furies have become a menace in the Clover systems. Dedicated gunships capable of catching and killing Viking class destroyers, they operate in packs to take down larger vessels."
    },
    {
        id: "ships-harrower",
        title: "Harrower",
        manufacturer: "Heralds",
        cost: 99000000,
        spinalWeaponMounts: 6,
        broadsideTurretMounts: 20,
        pointDefenceMounts: 12,
        hangarSpace: 13,
        navigation: "14/25",
        hullArmour: "13/25",
        shieldStrength: "06/25",
        length: "347m",
        maxCrew: 10,
        extraRooms: 5,
        energyUse: 4,
        description: "These \"Harrower\" light cruisers were found with the \"Monarch\" battleships. They possess reactionless drives that give them incredible agility and allow them to safely land on planets."
    },
    {
        id: "ships-x45-scythe",
        title: "X45 Scythe",
        manufacturer: "Triglav Innovations",
        cost: 80000000,
        spinalWeaponMounts: 4,
        broadsideTurretMounts: 24,
        pointDefenceMounts: 8,
        hangarSpace: 18,
        navigation: "05/25",
        hullArmour: "15/25",
        shieldStrength: "08/25",
        length: "785m",
        maxCrew: 8,
        extraRooms: 5,
        energyUse: 6,
        description: "May not mount anti-matter cannon. Triglav found something out there, and they reverse-engineered it into the X45 Scythe. Although only time will tell if the battlecruiser design is viable, the Scythe’s ability to quickly bring heavy firepower to the battlefield has proven invaluable on several occasions."
    },
    {
        id: "ships-manta",
        title: "Manta",
        manufacturer: "Heralds",
        cost: 120000000,
        spinalWeaponMounts: 4,
        broadsideTurretMounts: 28,
        pointDefenceMounts: 8,
        hangarSpace: 20,
        navigation: "09/25",
        hullArmour: "19/25",
        shieldStrength: "09/25",
        length: "817m",
        maxCrew: 6,
        extraRooms: 5,
        energyUse: 7,
        description: "May not mount anti-matter cannon. The technology and design of the \"Manta\" are distinct from those found in other Herald ships. Triglav won’t be happy you have one of the original Herald battlecruisers."
    },
    {
        id: "ships-monarch",
        title: "Monarch",
        manufacturer: "Heralds",
        cost: 224000000,
        spinalWeaponMounts: 4,
        broadsideTurretMounts: 30,
        pointDefenceMounts: 10,
        hangarSpace: 28,
        navigation: "09/25",
        hullArmour: "22/25",
        shieldStrength: "09/25",
        length: "1960m",
        maxCrew: 21,
        extraRooms: 6,
        energyUse: 7,
        description: "Advanced Jump Drive allows the \"Monarch\" to travel freely between systems without jump gates. Kings of the \"Ghul\" tech family, two \"Monarch\" fast battleships were recently found. These ships feel alive, and maneuver with a grace unheard of in such a large vessel. Their gravity sails tacking against some unseen medium."
    },
    {
        id: "ships-charon",
        title: "Charon",
        manufacturer: "Beatrice R&D",
        cost: "96m, Unique", // Keep as string due to "Unique"
        spinalWeaponMounts: 2,
        broadsideTurretMounts: 15,
        pointDefenceMounts: 48,
        hangarSpace: "03/25", // Keep as string due to format
        navigation: "22/25",
        hullArmour: "22/25",
        shieldStrength: "09/25",
        length: "1390m",
        maxCrew: 28,
        extraRooms: 8,
        energyUse: 7,
        description: "Jump Field allows Charon’s fleet to travel freely between systems without jump gates. The Charon is Beatrice R&D’s flagship and the product of decades of work: a jump ship capable of conveying an entire fleet of vessels to an unexplored system in a single leap. Cynical minds note it can bypass jump gates for a back door attack."
    },
    {
        id: "ships-x65-odysseus",
        title: "X65 \"Odysseus\"",
        manufacturer: "Triglav Innovations",
        cost: 220000000,
        spinalWeaponMounts: 3,
        broadsideTurretMounts: 26,
        pointDefenceMounts: 8,
        hangarSpace: 24,
        navigation: "02/25",
        hullArmour: "22/25",
        shieldStrength: "09/25",
        length: "3700m",
        maxCrew: 24,
        extraRooms: 8,
        energyUse: 7,
        description: "Uses Dreadnought rules. Within the Odysseus, Triglav fused the titanic might of the dreadnought with the more versatile nature of the battleship, creating a new breed of super-capital ship."
    },
    {
        id: "ships-pi-va2",
        title: "PI Va2",
        manufacturer: "Pulsar Inc.",
        cost: 380000000,
        spinalWeaponMounts: 4,
        broadsideTurretMounts: 32,
        pointDefenceMounts: 20,
        hangarSpace: 30,
        navigation: "09/25",
        hullArmour: "20/25",
        shieldStrength: "10/25",
        length: "6km",
        maxCrew: 40,
        extraRooms: 7,
        energyUse: 7,
        description: "Advanced Jump Drive lets the Va2 travel freely between systems without jump gates. Designed for Pulsar’s corporate field headquarters, the Va2 is the ultimate deep space exploration vessel. It serves as a base for traversing and researching multiple systems in comfort and relative safety."
    },
    {
        id: "ships-archangel",
        title: "Archangel",
        manufacturer: "Talons",
        cost: 380000000,
        spinalWeaponMounts: 6,
        broadsideTurretMounts: 42,
        pointDefenceMounts: 14,
        hangarSpace: 44,
        navigation: "08/25",
        hullArmour: "32/25",
        shieldStrength: "10/25",
        length: "7km",
        maxCrew: 34,
        extraRooms: 7,
        energyUse: 7,
        description: "Although formidable in combat, the Archangel’s primary task is to watch over uncharted systems. It acts as a mobile fortress securing new worlds during the early terraforming and colonization stages. Only once a system is well established is it added to the galactic network."
    },
    {
        id: "ships-hades",
        title: "Hades",
        manufacturer: "Heralds",
        cost: "Special, Unique", // Keep as string
        spinalWeaponMounts: 0,
        broadsideTurretMounts: 48,
        pointDefenceMounts: 24,
        hangarSpace: 84,
        navigation: "09/25",
        hullArmour: "-/25", // Keep as string
        shieldStrength: "-/25", // Keep as string
        energyDampingField: "-80% Damage", // New field
        length: "12km",
        minCrew: 4000, // New field, splitting "Min Crew - Max Crew"
        maxCrew: 20000,
        extraRooms: 10,
        energyUse: 10,
        description: "Wormhole Generator creates a temporary gateway to any designated star system. Energy Damping Field negates 80% of damage received. Anti-matter cannon strike overloads damping field for five minutes, but \"Hades\" survives otherwise intact. \"Hades\" is a mobile space station the size of a small city, recovered from a decaying orbit around a black hole. Formerly a scientific research outpost, \"Hades\" possesses unique technologies that will have a strong impact on space travel once they are reverse engineered."
    }
]
