export const crew = [
    // This array contains data for various crew members and archetypes.
// Each object represents a worker with attributes:
// - title: The title of the crew member.
// - Skill Level: A numerical representation of their skill (e.g., 1m, 2m, etc.).
// - alignment: Their faction or general alignment (e.g., Neutral, Federation, Red Daggers).
// - cost: The hiring cost of the crew member.
// - description: A brief description of the crew member.
// - specialty: Their primary area of expertise.
// - equipment: Any specific equipment they are noted to have.
// If an attribute is missing from the source, it is assigned a value of 0.

  // --- Specific Pilot Characters ---
  {
    title: "Anna Tse",
    skillLevel: 0, // Not explicitly stated, but implied by context as a pilot
    alignment: "Neutral",
    cost: 1000000,
    description: "Fresh pilot program grad, super loyal.",
    specialty: "Pilot",
    equipment: 0,
  prerequisites: "none", prerequisites: "none", },
  {
    title: "Gregor Hunter",
    skillLevel: 0,
    alignment: "Neutral",
    cost: 2000000,
    description: "Your brother-like, experienced outer-rim guy.",
    specialty: "Pilot",
    equipment: 0,
  prerequisites: "none", prerequisites: "none", },
  {
    title: "Pepper",
    skillLevel: 0,
    alignment: "Neutral",
    cost: 1000000,
    description: "Naive but loves flying, wants to be a co-pilot.",
    specialty: "Pilot",
    equipment: 0,
  prerequisites: "none", prerequisites: "none", },
  {
    title: "Horace Carter",
    skillLevel: 0,
    alignment: "Neutral",
    cost: 2000000,
    description: "Vehicle enthusiast, desperate to be a pilot-for-hire.",
    specialty: "Pilot",
    equipment: 0,
  prerequisites: "none", },
  {
    title: "Kay Hunter",
    skillLevel: 0,
    alignment: "Neutral",
    cost: 2000000,
    description: "Gregor's younger sister, no experience, needs your guidance.",
    specialty: "Pilot",
    equipment: 0,
  prerequisites: "none", },
  {
    title: "Elijah Horton",
    skillLevel: 0,
    alignment: "Neutral",
    cost: 2000000,
    description: "Old-fashioned but skilled pilot, great at negotiating.",
    specialty: "Pilot",
    equipment: 0,
  prerequisites: "none", },
  {
    title: "Sgt. Mark LeCruz",
    skillLevel: 0,
    alignment: "Federation",
    cost: 2000000,
    description: "Ace pilot, led a fighter squad, great asset.",
    specialty: "Pilot",
    equipment: 0,
  prerequisites: "none", },
  {
    title: "Jacqueline Young",
    skillLevel: 0,
    alignment: "Neutral",
    cost: 2000000,
    description: "Piloted scouting vessels, good at dodging asteroids.",
    specialty: "Pilot",
    equipment: 0,
  prerequisites: "none", },
  {
    title: "Alvin Reyes",
    skillLevel: 0,
    alignment: "Blackhawk Elite",
    cost: 3000000,
    description: "Young gun, wants experience to prove himself.",
    specialty: "Pilot",
    equipment: 0,
  prerequisites: "none", },
  {
    title: "Tiffany Manson",
    skillLevel: 0,
    alignment: "Neutral",
    cost: 3000000,
    description: "Used to escort science and exploration vessels.",
    specialty: "Pilot",
    equipment: 0,
  prerequisites: "none", },
  {
    title: "Susan Zim",
    skillLevel: 0,
    alignment: "Red Daggers",
    cost: 3000000,
    description: "Sharp, partook in risky heists with a powerful gang.",
    specialty: "Pilot",
    equipment: 0,
  prerequisites: "none", },
  {
    title: "Tyler Vaughn",
    skillLevel: 0,
    alignment: "Federation",
    cost: 3000000,
    description: "Wealthy background, master tactician from the Navy.",
    specialty: "Pilot",
    equipment: 0,
  prerequisites: "none", },
  {
    title: "Ivan Chesnikov",
    skillLevel: 0,
    alignment: "Neutral",
    cost: 4000000,
    description: "Masked merc, friendly despite his past.",
    specialty: "Pilot",
    equipment: 0,
  prerequisites: "none", },
  {
    title: "Milka Star",
    skillLevel: 0,
    alignment: "Red Daggers",
    cost: 4000000,
    description: "Polite, shy, Red Dagger who dislikes the Federation, has a dog.",
    specialty: "Pilot",
    equipment: 0,
  prerequisites: "none", },
  {
    title: "Royce Kodai",
    skillLevel: 0,
    alignment: "Neutral",
    cost: 4000000,
    description: "Exceptional police officer, chased criminals in high-speed pursuits.",
    specialty: "Pilot",
    equipment: 0,
  prerequisites: "none", },
  {
    title: "Mokhov Petrovich",
    skillLevel: 0,
    alignment: "Blackhawk Elite",
    cost: 4000000,
    description: "Former drill sergeant seeking vengeance.",
    specialty: "Pilot",
    equipment: 0,
  prerequisites: "none", },
  {
    title: "E.R.I.",
    skillLevel: 0,
    alignment: "Neutral",
    cost: 5000000,
    description: "Sapient android, great pilot, not so good with social cues.",
    specialty: "Pilot",
    equipment: 0,
  prerequisites: "none", },
  {
    title: "Wes Lunso",
    skillLevel: 0,
    alignment: "Neutral",
    cost: 5000000,
    description: "Former merc, loves flying and racing.",
    specialty: "Pilot",
    equipment: 0,
  prerequisites: "none", },
  {
    title: "Lia Stitt",
    skillLevel: 0,
    alignment: "Neutral",
    cost: 5000000,
    description: "Thirsty for adventure, opportunist, loves detours.",
    specialty: "Pilot",
    equipment: 0,
  prerequisites: "none", },
  {
    title: "Hailey",
    skillLevel: 0,
    alignment: "Neutral",
    cost: "Special cost",
    description: "Requires 'The Guardian' title. Quiet, psi powers, knows what you'll say.",
    specialty: "Pilot",
    equipment: 0,
  prerequisites: "none", },
  {
    title: "Conrad Byrant",
    skillLevel: 0,
    alignment: "Blackhawk Elite",
    cost: 5000000,
    description: "Loyal, can fly for days without rest.",
    specialty: "Pilot",
    equipment: 0,
  prerequisites: "none", },
  {
    title: "Mikayla Stone",
    skillLevel: 0,
    alignment: "Gazers",
    cost: 6000000,
    description: "Elite Gazer pilot, bold, brash, keeps her cool.",
    specialty: "Pilot",
    equipment: 0,
  prerequisites: "none", },
  {
    title: "David \"Tabs\" Sharp",
    skillLevel: 0,
    alignment: "Talons",
    cost: 6000000,
    description: "Pilot prodigy, part of risky Talon ops, a little haughty.",
    specialty: "Pilot",
    equipment: 0,
  prerequisites: "none", },
  {
    title: "Tera en Chasteaux",
    skillLevel: 0,
    alignment: "Federation",
    cost: 7000000,
    description: "Best Fed pilot training, controlled her own patrol fleet.",
    specialty: "Pilot",
    equipment: 0,
  prerequisites: "none", },
  {
    title: "Dorian Krueger",
    skillLevel: 0,
    alignment: "Federation",
    cost: 9000000,
    description: "Battle-hardened SOF pilot, man of few words.",
    specialty: "Pilot",
    equipment: 0,
  prerequisites: "none", },
  {
    title: "Ise Ley'is",
    skillLevel: 0,
    alignment: "Luos Syndicate",
    cost: 9000000,
    description: "Ruthless, high-rank former PMC, respects strength.",
    specialty: "Pilot",
    equipment: 0,
  prerequisites: "none", },
  {
    title: "Lux",
    skillLevel: 0,
    alignment: "Neutral",
    cost: 14000000,
    description: "One of the best pilots for hire, sense of humor, mysterious past.",
    specialty: "Pilot",
    equipment: 0,
  prerequisites: "none", },
  {
    title: "Zetta",
    skillLevel: 0,
    alignment: "Neutral",
    cost: 18000000,
    description: "Origins unknown, obedient if you're competent.",
    specialty: "Pilot",
    equipment: 0,
  prerequisites: "none", },

  // --- Engineers ---
  {
    title: "Enrico Jourdan",
    skillLevel: 0,
    alignment: "Neutral",
    cost: 1000000,
    description: "Kind, loyal, cheap handiwork, no questions asked.",
    specialty: "Engineer",
    equipment: 0,
  prerequisites: "none", },
  {
    title: "Derek Windtalker",
    skillLevel: 0,
    alignment: "Neutral",
    cost: 2000000,
    description: "From a rare line of mechanics, believes he's one with metal.",
    specialty: "Engineer",
    equipment: 0,
  prerequisites: "none", },
  {
    title: "Alena Bach",
    skillLevel: 0,
    alignment: "Neutral",
    cost: 2000000,
    description: "Exceptional inventor, new to starship mechanics, wants to impress.",
    specialty: "Engineer",
    equipment: 0,
  prerequisites: "none", },
  {
    title: "Malcolm Red",
    skillLevel: 0,
    alignment: "Neutral",
    cost: 2000000,
    description: "Blames everything for not doing his job, skilled with a crowbar.",
    specialty: "Engineer",
    equipment: "Crowbar",
  prerequisites: "none", },
  {
    title: "Adan Cervantes",
    skillLevel: 0,
    alignment: "Neutral",
    cost: 3000000,
    description: "Highly intelligent nuclear engineer, radiation burns, life-support suit.",
    specialty: "Nuclear Engineer",
    equipment: "Life-support suit",
  prerequisites: "none", },
  {
    title: "Trainwreck",
    skillLevel: 0,
    alignment: "Red Daggers",
    cost: 3000000,
    description: "Can keep a 'shit sandwich' moving, wants to build a tank.",
    specialty: "Engineer",
    equipment: 0,
  prerequisites: "none", },
  {
    title: "Trisha \"Props\" Lim",
    skillLevel: 0,
    alignment: "Neutral",
    cost: 3000000,
    description: "Hobbyist mechanic, loves tinkering, bubbly personality.",
    specialty: "Mechanic",
    equipment: 0,
  prerequisites: "none", },
  {
    title: "Troy Hall",
    skillLevel: 0,
    alignment: "Neutral",
    cost: 3000000,
    description: "Loves working with machines, metal arm useful.",
    specialty: "Engineer",
    equipment: "Metal arm",
  prerequisites: "none", },
  {
    title: "Cindy Kayoko",
    skillLevel: 0,
    alignment: "Red Daggers",
    cost: 4000000,
    description: "Popular among Red Daggers, worked with questionable machinery, not political.",
    specialty: "Engineer",
    equipment: 0,
  prerequisites: "none", },
  {
    title: "Amy McCartney",
    skillLevel: 0,
    alignment: "Federation",
    cost: 4000000,
    description: "Revered scientist, graceful, sings, wants a tavern.",
    specialty: "Scientist (Engineer)",
    equipment: 0,
  prerequisites: "none", },
  {
    title: "Roxanne Gilliam",
    skillLevel: 0,
    alignment: "Talons",
    cost: 4000000,
    description: "Led nuclear research in Talon labs, anti-matter tech.",
    specialty: "Nuclear Research (Engineer)",
    equipment: 0,
  prerequisites: "none", },
  {
    title: "Mereille Fairley",
    skillLevel: 0,
    alignment: "Federation",
    cost: 4000000,
    description: "Geek with Fed gadgets, device for any situation.",
    specialty: "Gadgeteer (Engineer)",
    equipment: "Fed gadgets",
  prerequisites: "none", },
  {
    title: "Arthur Foster",
    skillLevel: 0,
    alignment: "Neutral",
    cost: 5000000,
    description: "Studied under big titles, offers skills for a challenge.",
    specialty: "Engineer",
    equipment: 0,
  prerequisites: "none", },
  {
    title: "Reid Enos",
    skillLevel: 0,
    alignment: "Neutral",
    cost: 6000000,
    description: "Mad scientist, knows lots about nuclear tech.",
    specialty: "Nuclear Tech (Engineer)",
    equipment: 0,
  prerequisites: "none", },

  // --- Doctors ---
  {
    title: "Kelly Moss",
    skillLevel: 0,
    alignment: "Neutral",
    cost: 0,
    description: "Cannot be alone in advanced infirmary, volunteered to aid the poor.",
    specialty: "Medic",
    equipment: 0,
  prerequisites: "none", },
  {
    title: "Bethany Parks",
    skillLevel: 0,
    alignment: "Federation",
    cost: 1000000,
    description: "Fresh out of medical school, wants field experience, loves cats.",
    specialty: "Medic",
    equipment: 0,
  prerequisites: "none", },
  {
    title: "Ignacio Lopez",
    skillLevel: 0,
    alignment: "Neutral",
    cost: 2000000,
    description: "Cares only for medical books, competent medic with a workplace.",
    specialty: "Medic",
    equipment: 0,
  prerequisites: "none", },
  // Trisha "Props" Lim is listed under Engineers and Doctors, will keep her under Engineers only as she is described as a "Hobbyist mechanic"
  {
    title: "Tina Wei",
    skillLevel: 0,
    alignment: "Neutral",
    cost: 4000000,
    description: "Former merc medic, used to stress of high demand.",
    specialty: "Merc Medic",
    equipment: 0,
  prerequisites: "none", },
  {
    title: "Lupe",
    skillLevel: 0,
    alignment: "Red Daggers",
    cost: 4000000,
    description: "Technically a doctor, but unconventional, pirate miracle worker.",
    specialty: "Unconventional Doctor",
    equipment: 0,
  prerequisites: "none", },
  {
    title: "Devon Trice",
    skillLevel: 0,
    alignment: "Blackhawk Elite",
    cost: 5000000,
    description: "Stalwart Blackhawk, favors less violent life, skilled in combat.",
    specialty: "Medic (Combat Skilled)",
    equipment: 0,
  prerequisites: "none", },
  {
    title: "Lyra Miralda",
    skillLevel: 0,
    alignment: "Neutral",
    cost: 7000000,
    description: "Young, in medical textbooks, quick, efficient, a little awkward.",
    specialty: "Medic",
    equipment: 0,
  prerequisites: "none", },

  // --- Ship Gunners ---
  {
    title: "Brian Richardson",
    skillLevel: 0,
    alignment: "Neutral",
    cost: 1000000,
    description: "Knows everything about ship weapons, student who'd drop studies for gunner job.",
    specialty: "Ship Weapons",
    equipment: 0,
  prerequisites: "none", },
  {
    title: "Seer",
    skillLevel: 0,
    alignment: "Red Daggers",
    cost: 1000000,
    description: "Bad history, prime pirate example, unsavory even to Red Daggers.",
    specialty: "Ship Gunner",
    equipment: 0,
  prerequisites: "none", },
  {
    title: "Elizabeth Tyler",
    skillLevel: 0,
    alignment: "Federation",
    cost: 2000000,
    description: "Part of rare Fed patrols, met action but inexperienced.",
    specialty: "Ship Gunner",
    equipment: 0,
  prerequisites: "none", },
  {
    title: "Alton Daniel",
    skillLevel: 0,
    alignment: "Neutral",
    cost: 2000000,
    description: "From a backwater planet, skilled in ship gunning.",
    specialty: "Ship Gunner",
    equipment: 0,
  prerequisites: "none", },
  {
    title: "John Pope",
    skillLevel: 0,
    alignment: "Neutral",
    cost: 3000000,
    description: "Former merchant, quick aim from bandit attacks.",
    specialty: "Ship Gunner",
    equipment: 0,
  prerequisites: "none", },
  {
    title: "Theresa Herder",
    skillLevel: 0,
    alignment: "Blackhawk Elite",
    cost: 3000000,
    description: "Former Fed gunner, Blackhawk Elite, disciplined but laid-back off work.",
    specialty: "Ship Gunner",
    equipment: 0,
  prerequisites: "none", },
  {
    title: "Vis'yeth",
    skillLevel: 0,
    alignment: "Luos Syndicate",
    cost: 4000000,
    description: "Mysterious, took down three cruisers himself in Haven defence.",
    specialty: "Ship Gunner",
    equipment: 0,
  prerequisites: "none", },
  {
    title: "Clara \"Sun\" Howell",
    skillLevel: 0,
    alignment: "Neutral",
    cost: 4000000,
    description: "Fiery and passionate, fun to tease about being a ginger.",
    specialty: "Ship Gunner",
    equipment: 0,
  prerequisites: "none", },
  {
    title: "Faith Nichols",
    skillLevel: 0,
    alignment: "Federation",
    cost: 4000000,
    description: "From Fed SOF, high-tech equipment, very innocent.",
    specialty: "Ship Gunner",
    equipment: "High-tech equipment",
  prerequisites: "none", },
  {
    title: "Comet",
    skillLevel: 0,
    alignment: "Neutral",
    cost: "Special cost",
    description: "Requires 'The Sorcerer' title, body mingles with energy.",
    specialty: "Ship Gunner",
    equipment: 0,
  prerequisites: "none", },
  {
    title: "Viktor",
    skillLevel: 0,
    alignment: "Neutral",
    cost: 5000000,
    description: "Down to earth, professional, reliable ship gunner.",
    specialty: "Ship Gunner",
    equipment: 0,
  prerequisites: "none", },
  {
    title: "Tavia \"Echo\" Tsun",
    skillLevel: 0,
    alignment: "Talons",
    cost: 5000000,
    description: "Rare Talon for hire, intimidating but down-to-earth, don't call her Tavi.",
    specialty: "Ship Gunner",
    equipment: 0,
  prerequisites: "none", },
  {
    title: "Lt. Bill Smith",
    skillLevel: 0,
    alignment: "Federation",
    cost: 5000000,
    description: "Veteran gunner, hits hard and ruthlessly.",
    specialty: "Ship Gunner",
    equipment: 0,
  prerequisites: "none", },
  {
    title: "Amanda Lynch",
    skillLevel: 0,
    alignment: "Neutral",
    cost: 6000000,
    description: "Fast, strong-willed, never lost a fleet fight, defended industrial areas.",
    specialty: "Ship Gunner",
    equipment: 0,
  prerequisites: "none", },

  // --- Combat & Security ---
  {
    title: "Owen Baker",
    skillLevel: 0,
    alignment: "Neutral",
    cost: 1000000,
    description: "Drove out bandits from his homeworld.",
    specialty: "Guerilla warfare",
    equipment: 0,
  prerequisites: "none", },
  {
    title: "Sasha Baker",
    skillLevel: 0,
    alignment: "Neutral",
    cost: 1000000,
    description: "Owen's younger sister, crack shot, too many kill notches.",
    specialty: "Sniping",
    equipment: 0,
  prerequisites: "none", },
  {
    title: "Myrie Shaffer",
    skillLevel: 0,
    alignment: "Red Daggers",
    cost: 2000000,
    description: "Worked for notorious pirate gang, makes deals go her way.",
    specialty: "Storming",
    equipment: 0,
  prerequisites: "none", },
  {
    title: "Pierre Mikisugi",
    skillLevel: 0,
    alignment: "Neutral",
    cost: 2000000,
    description: "Good cop, part of high-stake raids.",
    specialty: "Ship security",
    equipment: 0,
  prerequisites: "none", },
  {
    title: "Sophie Haynes",
    skillLevel: 0,
    alignment: "Federation",
    cost: 2000000,
    description: "Faith Nichols' friend, quick, witty, has a sixth sense for bad vibes.",
    specialty: "Covert ops",
    equipment: 0,
  prerequisites: "none", },
  {
    title: "Grzegorz Grzegrzółka",
    skillLevel: 0,
    alignment: "Neutral",
    cost: 2000000,
    description: "Ex-cop, works to pay for his sister's education, does things his own way.",
    specialty: "Ship security",
    equipment: 0,
  prerequisites: "none", },
  {
    title: "Ley'ra Laur",
    skillLevel: 0,
    alignment: "Luos Syndicate",
    cost: 3000000,
    description: "Steel nerves, took point in battles, lost her high-tech armor, shy off-duty.",
    specialty: "Point position",
    equipment: "Lost high-tech armor",
  prerequisites: "none", },
  {
    title: "Dani \"Cuts\" Laine",
    skillLevel: 0,
    alignment: "Blackhawk Elite",
    cost: 3000000,
    description: "Aggressive, blunt, fireteam leader, helped reduce crime in 3 systems.",
    specialty: "Long-range",
    equipment: 0,
  prerequisites: "none", },
  {
    title: "Ward Shapiro",
    skillLevel: 0,
    alignment: "Neutral",
    cost: 3000000,
    description: "Joined security to finish his book, got conscripted and sent to front lines.",
    specialty: "Sentry",
    equipment: 0,
  prerequisites: "none", },
  {
    title: "Sgt. Raul Miller",
    skillLevel: 0,
    alignment: "Federation",
    cost: 3000000,
    description: "Stationed on an ice planet, dealt with pirates and cartels, navigates tough terrain.",
    specialty: "Front-line assault",
    equipment: 0,
  prerequisites: "none", },
  {
    title: "Erik \"Sooter\" Burke",
    skillLevel: 0,
    alignment: "Red Daggers",
    cost: 3000000,
    description: "Not smart in other areas, but a great rank-and-file pirate with a weapon. Don't make him mad.",
    specialty: "Front-line assault",
    equipment: "Weapon",
  prerequisites: "none", },
  {
    title: "Vikram Solar",
    skillLevel: 0,
    alignment: "Neutral",
    cost: 4000000,
    description: "Loves laser weapons, refuses conventional ammo ('messy'), a bit of a neat freak.",
    specialty: "Long-range (Laser Weapons)",
    equipment: "Laser weapons",
  prerequisites: "none", },
  {
    title: "Darrel Wallace",
    skillLevel: 0,
    alignment: "Blackhawk Elite",
    cost: 4000000,
    description: "Flew in many fleets, top-notch on-ship security, tough like the Blackhawks.",
    specialty: "Sentry (On-ship security)",
    equipment: 0,
  prerequisites: "none", },
  {
    title: "Rooks King",
    skillLevel: 0,
    alignment: "Gazers",
    cost: 5000000,
    description: "Skilled Gazer operator, hangs with Dustkeepers, his disappearances are ignored.",
    specialty: "Guerilla warfare",
    equipment: 0,
  prerequisites: "none", },
  {
    title: "Livia Amaruq",
    skillLevel: 0,
    alignment: "Federation",
    cost: 5000000,
    description: "Ex-operative from Fed SOF, worked on the same ice planet as Sgt. Raul, looks deadly.",
    specialty: "Hand-to-hand",
    equipment: 0,
  prerequisites: "none", },
  {
    title: "Scot Shephard",
    skillLevel: 0,
    alignment: "Neutral",
    cost: 5000000,
    description: "SWAT in a big city, seen the worst of humanity.",
    specialty: "Storming",
    equipment: 0,
  prerequisites: "none", },
  {
    title: "Alessia",
    skillLevel: 0,
    alignment: "Talons",
    cost: 5000000,
    description: "Hot-headed, wants to strangle her brother Ricce, don't get in her way.",
    specialty: "Long-ranged",
    equipment: 0,
  prerequisites: "none", },
  {
    title: "Ricce",
    skillLevel: 0,
    alignment: "Federation",
    cost: 5000000,
    description: "Stalwart soldier in high-tech armor, a force on the battlefield. Silent about his sister Alessia.",
    specialty: "Front-line assault",
    equipment: "High-tech armor",
  prerequisites: "none", },
  {
    title: "Arabelle Meyer",
    skillLevel: 0,
    alignment: "Neutral",
    cost: 5000000,
    description: "Disciplined, patient, cunning assassin, great at hiding.",
    specialty: "Sniping (Assassin)",
    equipment: 0,
  prerequisites: "none", },
  {
    title: "Marcelo Lee",
    skillLevel: 0,
    alignment: "Talons",
    cost: 6000000,
    description: "Rare Talon for hire, has cool gadgets, solo mission experience.",
    specialty: "Guerilla warfare",
    equipment: "Cool gadgets",
  prerequisites: "none", },
  {
    title: "Lt. Jenny Larue",
    skillLevel: 0,
    alignment: "Federation",
    cost: 6000000,
    description: "Top Fed SOF officer, commands with a valiant heart, known for 'strict kindness,' often works under Tera.",
    specialty: "Point position",
    equipment: 0,
  prerequisites: "none", },
  {
    title: "Martin Jenkins",
    skillLevel: 0,
    alignment: "Blackhawk Elite",
    cost: 6000000,
    description: "Iconic Blackhawk Elite shock trooper, leads conflicts with unstoppable momentum.",
    specialty: "Storming (Shock Trooper)",
    equipment: 0,
  prerequisites: "none", },
  {
    title: "My'hra Jos",
    skillLevel: 0,
    alignment: "Luos Syndicate",
    cost: 7000000,
    description: "Skilled ground officer in a small PMC, helped defend the Abyss system.",
    specialty: "Infiltration",
    equipment: 0,
  prerequisites: "none", },
  {
    title: "Patch Newton",
    skillLevel: 0,
    alignment: "Neutral",
    cost: 7000000,
    description: "Notorious, deadly assassin with a rifle. Built his own unique hardware, 'one with his armor.'",
    specialty: "Sniping (Assassin)",
    equipment: "Rifle, unique hardware",
  prerequisites: "none", },
  {
    title: "Locust",
    skillLevel: 0,
    alignment: "Neutral",
    cost: 14000000,
    description: "'Rider of Famine,' can destroy armies with his blade, from the classified Apocalypse program.",
    specialty: "Hand-to-hand (Blade)",
    equipment: "Blade",
  prerequisites: "none", },
  {
    title: "Plague",
    skillLevel: 0,
    alignment: "Neutral",
    cost: 15000000,
    description: "'Rider of Pestilence,' toughest armor, strongest in brute force, one of the four separated Riders.",
    specialty: "Front-line assault (Brute Force)",
    equipment: "Toughest armor",
  prerequisites: "none", },
  {
    title: "Archangel",
    skillLevel: 0,
    alignment: "Federation",
    cost: 17000000,
    description: "'Rider of War,' wields a unique Ion Cannon, loyal to the Federation.",
    specialty: "Heavy weapons",
    equipment: "Unique Ion Cannon",
  prerequisites: "none", },
  {
    title: "Styx",
    skillLevel: 0,
    alignment: "Herself",
    cost: 18000000,
    description: "'Rider of Death,' holds a terrible grudge against the Federation after defection, respects her siblings.",
    specialty: "Infiltration",
    equipment: 0,
  prerequisites: "none", },

  // --- Cyber Security Officers ---
  {
    title: "Perry West",
    skillLevel: 0,
    alignment: "Neutral",
    cost: 3000000,
    description: "From a big company, great at electronic warfare, your ship will be well defended.",
    specialty: "Electronic warfare",
    equipment: 0,
  prerequisites: "none", },
  {
    title: "Erica \"761\"",
    skillLevel: 0,
    alignment: "Neutral",
    cost: 4000000,
    description: "Dropped out of university, cut ties, now wants to join your crew.",
    specialty: "Cyber Security",
    equipment: 0,
  prerequisites: "none", },
  {
    title: "Damian Galt",
    skillLevel: 0,
    alignment: "Red Daggers",
    cost: 4000000,
    description: "Has an excellent service record and a lot of illegally obtained porn. Will awkwardly hit on female crew over the PA. Constantly.",
    specialty: "Cyber Security",
    equipment: 0,
  prerequisites: "none", },
  {
    title: "Slash Singer",
    skillLevel: 0,
    alignment: "Neutral",
    cost: 4000000,
    description: "Brilliant programmer, can bypass tough security, has lots of 'skeleton key' decryption programs.",
    specialty: "Programmer (Security Bypass)",
    equipment: "'Skeleton key' decryption programs",
  prerequisites: "none", },
  {
    title: "Veslav Smertodov",
    skillLevel: 0,
    alignment: "Talons",
    cost: 6000000,
    description: "Well-known Talon hacker, expert with AI, good at multitasking, often fought 'Arachne' in cyber battles.",
    specialty: "Hacker (AI Expert)",
    equipment: 0,
  prerequisites: "none", },
  {
    title: "Arachne",
    skillLevel: 0,
    alignment: "Federation",
    cost: 6000000,
    description: "Ex-military intelligence officer, can go head-to-head with notorious hackers in cyber warfare.",
    specialty: "Cyber warfare",
    equipment: 0,
  prerequisites: "none", },
  {
    title: "Uplink",
    skillLevel: 0,
    alignment: "Neutral",
    cost: 12000000,
    description: "Expensive to install, one of the few sapient AI androids, wants access to all information.",
    specialty: "AI Android (Information Access)",
    equipment: 0,
  prerequisites: "none", },

  // --- Scientists ---
  {
    title: "Lauren L. Lazuli",
    skillLevel: 0,
    alignment: "Neutral",
    cost: 0,
    description: "Found her in your lab, caffeine packets everywhere, feverishly working on a thesis, sleeps in the lab.",
    specialty: "Scientist (Thesis)",
    equipment: 0,
  prerequisites: "none", },
  {
    title: "Curt Robertson",
    skillLevel: 0,
    alignment: "Federation",
    cost: 1000000,
    description: "Believes you shouldn't abandon your body, human biology specialist, very tall due to his research.",
    specialty: "Human biology",
    equipment: 0,
  prerequisites: "none", },
  {
    title: "Emily Newton",
    skillLevel: 0,
    alignment: "Neutral",
    cost: 1000000,
    description: "Morally against combat ships, expert in xenobiology and terraforming, a bit eccentric.",
    specialty: "Xenobiology, Terraforming",
    equipment: 0,
  prerequisites: "none", },
  {
    title: "Sarah Escher",
    skillLevel: 0,
    alignment: "Red Daggers",
    cost: 2000000,
    description: "Super smart but short attention span, frequent experiments with mana energy gave her an eerie glow.",
    specialty: "Mana energy experiments",
    equipment: 0,
  prerequisites: "none", },
  {
    title: "Shinichi Yagazen",
    skillLevel: 0,
    alignment: "Neutral",
    cost: 3000000,
    description: "Biology, bioengineering, chemistry, and biological warfare expert. Wanted for questionable experiments and creating bioweapons.",
    specialty: "Biology, Bioengineering, Chemistry, Biological Warfare",
    equipment: 0,
  prerequisites: "none", },
  {
    title: "Isaac J. Bidlack",
    skillLevel: 0,
    alignment: "Federation",
    cost: 3000000,
    description: "Years of study, research increased galactic agricultural production by half a percent. Likes candied fish.",
    specialty: "Agricultural production research",
    equipment: 0,
  prerequisites: "none", },
  {
    title: "Wilhelm von Welch",
    skillLevel: 0,
    alignment: "Neutral",
    cost: 5000000,
    description: "Brilliant and mad, strict scientist obsessed with learning about the Heralds.",
    specialty: "Heralds research",
    equipment: 0,
  prerequisites: "none", },

  // --- Production Managers ---
  {
    title: "Sibyl",
    skillLevel: 0,
    alignment: "Red Daggers",
    cost: 1000000,
    description: "Worked in Red Dagger industrial wings for 20+ years, knows lots of mining and manufacturing tricks.",
    specialty: "Mining, Manufacturing",
    equipment: 0,
  prerequisites: "none", },
  {
    title: "Madeline Moran",
    skillLevel: 0,
    alignment: "Blackhawk Elite",
    cost: 2000000,
    description: "Crucial to Blackhawk Elite's hardware might, keeps them going strong.",
    specialty: "Hardware production",
    equipment: 0,
  prerequisites: "none", },
  {
    title: "Wesley Chalmers",
    skillLevel: 0,
    alignment: "Neutral",
    cost: 2000000,
    description: "Always gets the job done, even if your ship is falling apart.",
    specialty: "Production Management",
    equipment: 0,
  prerequisites: "none", },
  {
    title: "Corrine Peyton",
    skillLevel: 0,
    alignment: "Neutral",
    cost: 3000000,
    description: "Serious and authoritative in industrial wings, workers obey or face a long, deafening scolding.",
    specialty: "Industrial Management",
    equipment: 0,
  prerequisites: "none", },
  {
    title: "Ty Piper",
    skillLevel: 0,
    alignment: "Federation",
    cost: 3000000,
    description: "Great production manager, excellent track record from Fed industrial systems, promotes efficiency and work ethics.",
    specialty: "Production Management (Efficiency)",
    equipment: 0,
  prerequisites: "none", },
  {
    title: "May Padilla",
    skillLevel: 0,
    alignment: "Neutral",
    cost: 4000000,
    description: "Hard worker, speeds things up, likes to boast about her strength.",
    specialty: "Production Management",
    equipment: 0,
  prerequisites: "none", },
  {
    title: "Michael Danagger",
    skillLevel: 0,
    alignment: "Neutral",
    cost: 6000000,
    description: "Super successful industrialist, his company fueled shipping businesses in over a dozen systems.",
    specialty: "Industrialist",
    equipment: 0,
  prerequisites: "none", },

  // --- Chefs & Bartenders ---
  {
    title: "Jorgen Masterson",
    skillLevel: 0,
    alignment: "Neutral",
    cost: 1000000,
    description: "Retired merc who became a chef. Served on prison transports, capable and ingenious cook.",
    specialty: "Chef",
    equipment: 0,
  prerequisites: "none", },
  {
    title: "Mikka Akimoto",
    skillLevel: 0,
    alignment: "Red Daggers",
    cost: 1000000,
    description: "Specializes in Japanese and other Asian cuisines. Sushi and ramen are timeless.",
    specialty: "Chef (Japanese/Asian Cuisine)",
    equipment: 0,
  prerequisites: "none", },
  {
    title: "Patricia Cooper",
    skillLevel: 0,
    alignment: "Neutral",
    cost: 2000000,
    description: "Loves to cook, takes charge in the kitchen, enjoys working with European cuisines.",
    specialty: "Chef (European Cuisine)",
    equipment: 0,
  prerequisites: "none", },
  {
    title: "Vito Lozano",
    skillLevel: 0,
    alignment: "Neutral",
    cost: 4000000,
    description: "Will only use a fancy mess hall. Do not disturb when he's cooking. His spaghetti is perfection.",
    specialty: "Chef",
    equipment: 0,
  prerequisites: "none", },
  {
    title: "Laurie Parsons",
    skillLevel: 0,
    alignment: "Federation",
    cost: 1000000,
    description: "Typical bartender, listens to your problems, perfect for standard mixes.",
    specialty: "Bartender",
    equipment: 0,
  prerequisites: "none", },
  {
    title: "Carolyn Brooks",
    skillLevel: 0,
    alignment: "Neutral",
    cost: 2000000,
    description: "Playful and outgoing, aims for smiles with every serve, loves mixing fancy drinks.",
    specialty: "Bartender (Fancy Drinks)",
    equipment: 0,
  prerequisites: "none", },
  {
    title: "Hal",
    skillLevel: 0,
    alignment: "Neutral",
    cost: 4000000,
    description: "Former assassin, has many stories, might have 'special' mixes that need a lab.",
    specialty: "Bartender (Special Mixes)",
    equipment: 0,
  prerequisites: "none", },

  // --- Pilot Archetypes ---
  {
    title: "Wingman",
    skillLevel: 0,
    alignment: "Fighter",
    cost: 1000000,
    description: "Average fighter pilot, best in formations, coordinates well.",
    specialty: "Pilot (Formations)",
    equipment: 0,
  prerequisites: "none", },
  {
    title: "Racer",
    skillLevel: 0,
    alignment: "Fighter",
    cost: 1000000,
    description: "Cares more about speed than fighting, but can still fly well.",
    specialty: "Pilot (Speed)",
    equipment: 0,
  prerequisites: "none", },
  {
    title: "Ace",
    skillLevel: 0,
    alignment: "Frigate",
    cost: 3000000,
    description: "Has combat history, led formations, very skilled in a Fighter.",
    specialty: "Pilot (Combat, Formations)",
    equipment: 0,
  prerequisites: "none", },
  {
    title: "Lieutenant",
    skillLevel: 0,
    alignment: "Destroyer",
    cost: 4000000,
    description: "Can lead a decent crew, responsible, keeps crew in check.",
    specialty: "Pilot (Crew Leadership)",
    equipment: 0,
  prerequisites: "none", },
  {
    title: "Lt. Commander",
    skillLevel: 0,
    alignment: "Cruiser",
    cost: 6000000,
    description: "Made a title for themselves, competent at leading lots of people.",
    specialty: "Pilot (Large Crew Leadership)",
    equipment: 0,
  prerequisites: "none", },
  {
    title: "Commander",
    skillLevel: 0,
    alignment: "Carrier",
    cost: 7000000,
    description: "Trustworthy for big ships, holds the ship together, people follow them.",
    specialty: "Pilot (Large Ship Command)",
    equipment: 0,
  prerequisites: "none", },
  {
    title: "Captain",
    skillLevel: 0,
    alignment: "Dreadnought",
    cost: 8000000,
    description: "The most experienced and capable pilot for the largest ships.",
    specialty: "Pilot (Dreadnought Command)",
    equipment: 0,
  prerequisites: "none", },

  // --- Crew Archetypes ---
  {
    title: "Volunteers",
    skillLevel: 0,
    alignment: 0,
    cost: 0,
    description: "They'll get the job done, but they're not pros.",
    specialty: "General Crew",
    equipment: 0,
  prerequisites: "none", },
  {
    title: "Industry Laborers",
    skillLevel: 0,
    alignment: 0,
    cost: 100000,
    description: "Need work done? These folks will get your mining, manufacturing, and processing needs sorted efficiently.",
    specialty: "Mining, Manufacturing, Processing",
    equipment: 0,
  prerequisites: "none", },
  {
    title: "Civilian Workers",
    skillLevel: 0,
    alignment: 0,
    cost: 100000,
    description: "Plenty of civilians are looking for legit work, and they make great space-faring crew.",
    specialty: "General Crew",
    equipment: 0,
  prerequisites: "none", },
  {
    title: "Researchers",
    skillLevel: 0,
    alignment: 0,
    cost: 100000,
    description: "For science and discovery among endless stars, these researchers make for a super intelligent crew.",
    specialty: "Science, Discovery",
    equipment: 0,
  prerequisites: "none", },
  {
    title: "Bandits",
    skillLevel: 0,
    alignment: 0,
    cost: 100000,
    description: "An average bandit can be a hard-working crew member, as long as you can get them to respect you.",
    specialty: "General Crew",
    equipment: 0,
  prerequisites: "none", },
  {
    title: "Explorers",
    skillLevel: 0,
    alignment: 0,
    cost: 100000,
    description: "These guys are cursed with an endless thirst for exploration and love the stars almost as much as you do.",
    specialty: "Exploration",
    equipment: 0,
  prerequisites: "none", },
  {
    title: "Medics",
    skillLevel: 0,
    alignment: 0,
    cost: 100000,
    description: "Medical knowledge is super valuable. Not everyone's a medic, so why not hire some pros?",
    specialty: "Medical",
    equipment: 0,
  prerequisites: "none", },
  {
    title: "Engineers (Archetype)", // Retitled to differentiate from specific engineers
    skillLevel: 0,
    alignment: 0,
    cost: 100000,
    description: "Need some repairs or maintenance? These engineers can get any ship up and running again, fast.",
    specialty: "Repairs, Maintenance",
    equipment: 0,
  prerequisites: "none", },
  {
    title: "Mercenaries (Archetype)", // Retitled to differentiate from specific mercs
    skillLevel: 0,
    alignment: 0,
    cost: 100000,
    description: "These battle-hardened mercs are ready to take on any combat situation with a strong will and determination.",
    specialty: "Combat",
    equipment: 0,
  prerequisites: "none", },
  {
    title: "Seraphs",
    skillLevel: 0,
    alignment: 0,
    cost: 100000,
    description: "These guys are your regular Blackhawks but they're not really into the whole 'politics' thing. They're just good at fighting.",
    specialty: "Combat",
    equipment: 0,
  prerequisites: "none", },
  {
    title: "Red Dagger Pirates (Archetype)", // Retitled
    skillLevel: 0,
    alignment: 0,
    cost: 100000,
    description: "Some Red Daggers are pretty chill and will join your crew if they think you're cool.",
    specialty: "General Crew",
    equipment: 0,
  prerequisites: "none", },
  {
    title: "Navy Soldiers",
    skillLevel: 0,
    alignment: 0,
    cost: 100000,
    description: "Federation Navy soldiers are well-disciplined and will listen to your every command.",
    specialty: "Military",
    equipment: 0,
  prerequisites: "none", },
  {
    title: "Core Ring Mercs",
    skillLevel: 0,
    alignment: 0,
    cost: 100000,
    description: "These mercs are all about that Core Ring life and just want to get paid.",
    specialty: "Mercenary",
    equipment: 0,
  prerequisites: "none", },
  {
    title: "Dustkeepers",
    skillLevel: 0,
    alignment: 0,
    cost: 100000,
    description: "Dustkeepers are always busy, even when they're not on a job. They can handle pretty much anything thrown their way.",
    specialty: "General Crew",
    equipment: 0,
  prerequisites: "none", },
];