export { crew, archetype, addCrewToSection };
import { appendDropdown, formatterIntl } from "/Script/manaData.js";

const crew = [
  {
    title: "Anna Tse",
    skillLevel: 2,
    alignment: "Neutral",
    cost: 1000000,
    description: "Anna recently graduated from the pilot program at Beatrice Tech. She is incredibly loyal and will follow you wherever you go.",
    specialty: "Pilot",
    equipment: 7,
    image: "Images/Crew/IsekaiLanayaya-civitai.webp",
  },
  {
    title: "Gregor Hunter",
    skillLevel: 7,
    alignment: "Neutral",
    cost: 2000000,
    description: "This guy would give an arm or two for you. He is everything you see in a brother, and has a lot of experience in the outer-rim systems.",
    specialty: "Pilot",
    equipment: 3,
    image: "https://placehold.co/200x200/512929/e7a3a3?text=Gregor+Hunter",
  },
  {
    title: "Pepper",
    skillLevel: 7,
    alignment: "Neutral",
    cost: 1000000,
    description: "Naive but incredibly outgoing, Pepper hasn't had much training, but she loves flying and does it a lot. She wants to try her hand at being a co-pilot.",
    specialty: "Pilot",
    equipment: 2,
    image: "Images/Crew/gothgirl-indotort-civitai.webp",
  },
  {
    title: "Horace Carter",
    skillLevel: 3,
    alignment: "Neutral",
    cost: 2000000,
    description: "He loves his cars, he loves ships, and is passionate about all things vehicles. Horace would kill to get a chance of becoming a pilot-for-hire.",
    specialty: "Pilot",
    equipment: 6,
    image: "https://placehold.co/200x200/512929/e7a3a3?text=Horace+Carter",
  },
  {
    title: "Kay Hunter",
    skillLevel: 2,
    alignment: "Neutral",
    cost: 2000000,
    description: "The younger sister of Gregor, Kay actually took her studies seriously. She also has virtually no experience, and needs you to lead her properly.",
    specialty: "Pilot",
    equipment: 8,
    image: "Images/Crew/reijlita3-civitai.webp",
  },
  {
    title: "Elijah Horton",
    skillLevel: 7,
    alignment: "Neutral",
    cost: 2000000,
    description: "An old fashioned but skilled pilot, Elijah was often offered courier contracts that took him deep into the outer rim systems. Great at negotiating.",
    specialty: "Pilot",
    equipment: 4,
    image: "https://placehold.co/200x200/512929/e7a3a3?text=Elijah+Horton",
  },
  {
    title: "Sgt. Mark LeCruz",
    skillLevel: 5,
    alignment: "Federation",
    cost: 2000000,
    description: "Mark is a sergeant who led his own squad of fighter pilots during the war against the Luos Syndicate. He is an ace pilot, and proves a great asset to any crew.",
    specialty: "Pilot",
    equipment: 6,
    image: "https://placehold.co/200x200/512929/e7a3a3?text=Sgt.+Mark+LeCruz",
  },
  {
    title: "Jacqueline Young",
    skillLevel: 7,
    alignment: "Neutral",
    cost: 2000000,
    description: "Jackie got her flying skills from piloting scouting vessels for Pulsar Inc., having lots of practice dodging dangerous, fast-moving asteroids.",
    specialty: "Pilot",
    equipment: 5,
    image: "Images/Crew/IsekaiLanayaya3-civitai.webp",
  },
  {
    title: "Alvin Reyes",
    skillLevel: 4,
    alignment: "Blackhawk Elite",
    cost: 3000000,
    description: "Often called a \"kid\" by his Blachawk superiors, Alvin longs for proper experience to prove to them he's capable. He assures you he would be a great asset.",
    specialty: "Pilot",
    equipment: 7,
    image: "https://placehold.co/200x200/512929/e7a3a3?text=Alvin+Reyes",
  },
  {
    title: "Tiffany Manson",
    skillLevel: 7,
    alignment: "Neutral",
    cost: 3000000,
    description: "Targeting Beatrice R&D ships is looked down upon by everyone, but it happens. Tiffany often escorted science and exploration vessels in a fighter ship.",
    specialty: "Pilot",
    equipment: 4,
    image: "Images/Crew/spacegirl2-indotort-civitai.webp",
  },
  {
    title: "Susan Zim",
    skillLevel: 7,
    alignment: "Red Daggers",
    cost: 3000000,
    description: "Susie flew with a powerful gang in the Red Daggers. She's as sharp as she looks, and has partaken in very risky heists.",
    specialty: "Pilot",
    equipment: 6,
    image: "Images/Crew/fepirate1-indotort-midjourney.webp",
  },
  {
    title: "Tyler Vaughn",
    skillLevel: 4,
    alignment: "Federation",
    cost: 3000000,
    description: "Tyler comes from a wealthy line and found himself in the Navy. He is regarded as a master tactician, and now wants to put his knowledge to the test.",
    specialty: "Pilot",
    equipment: 7,
    image: "https://placehold.co/200x200/512929/e7a3a3?text=Tyler+Vaughn",
  },
  {
    title: "Ivan Chesnikov",
    skillLevel: 5,
    alignment: "Neutral",
    cost: 4000000,
    description: "He might never take off his mask, but he really is a friendly guy, despite all of his experience flying with mercs. Never take him to a kebab parlour.",
    specialty: "Pilot",
    equipment: 8,
    image: "https://placehold.co/200x200/512929/e7a3a3?text=Ivan+Chesnikov",
  },
  {
    title: "Milka Star",
    skillLevel: 6,
    alignment: "Red Daggers",
    cost: 4000000,
    description: "Milka's polite, shy, and friendly... everything that you wouldn't expect from a Red Dagger. She, as she puts it, \"greatly dislikes\" the Federation. Has a pet dog.",
    specialty: "Pilot",
    equipment: 7,
    image: "Images/Crew/runaheadofme-civitai.webp",
  },
  {
    title: "Royce Kodai",
    skillLevel: 9,
    alignment: "Neutral",
    cost: 4000000,
    description: "Large cities need their police force, and Royce is an exceptional cop. He's chased down criminals in some of the highest speed chas n the galaxy.",
    specialty: "Pilot",
    equipment: 7,
    image: "https://placehold.co/200x200/512929/e7a3a3?text=Royce+Kodai",
  },
  {
    title: "Mokhov Petrovich",
    skillLevel: 5,
    alignment: "Blackhawk Elite",
    cost: 4000000,
    description: "A former drill sergeant from the Blackhawk Elite, Mokhov turned to piloting to search for vengeance. Vengeance for what, he'll only tell thos trusts.",
    specialty: "Pilot",
    equipment: 8,
    image: "https://placehold.co/200x200/512929/e7a3a3?text=Mokhov+Petrovich",
  },
  {
    title: "E.R.I.",
    skillLevel: null,
    alignment: "Neutral",
    cost: 5000000,
    description: "Eri was a maid-purposed android who had a malfunction in the factory, gaining sapience. She doesn't know much about social cues, but she's a great pilot.",
    specialty: "Pilot",
    equipment: 5,
    image: "Images/Crew/robotgirl-3mcg33-civitai.jpeg",
  },
  {
    title: "Wes Lunso",
    skillLevel: null,
    alignment: "Neutral",
    cost: 5000000,
    description: "Wes used to work for a mercenary group, but has since left and is looking for a change in pace. He is very passionate for flying and racing.",
    specialty: "Pilot",
    equipment: null,
    image: "https://placehold.co/200x200/512929/e7a3a3?text=Wes+Lunso",
  },
  {
    title: "Lia Stitt",
    skillLevel: 6,
    alignment: "Neutral",
    cost: 5000000,
    description: "With a thirst for adventure, Lia will hitch on any ride that will take her to the stars. As an opportunist, she'll often take interesting detours if you let her.",
    specialty: "Pilot",
    equipment: 8,
    image: "Images/Crew/corporat3-civitai.webp",
  },
  {
    title: "Hailey",
    skillLevel: null,
    alignment: "Neutral",
    cost: "Special cost",
    description: "While she's not very talkative, Hailey seems to have some sort of psi powers. She knows what you're gonna say efore you do.",
    specialty: "Pilot",
    equipment: null,
    image: "Images/Titles/hailey-crew-midjourney.webp",
  },
  {
    title: "Conrad Byrant",
    skillLevel: 8,
    alignment: "Blackhawk Elite",
    cost: 5000000,
    description: "Conrad is a man who can stay to his duty and really commit to it. As a loyal Blackhawk pilot, he's flown for several days at a time without rest.",
    specialty: "Pilot",
    equipment: null,
    image: "https://placehold.co/200x200/512929/e7a3a3?text=Conrad+Byrant",
  },
  {
    title: "Mikayla Suzuki",
    skillLevel: null,
    alignment: "Gazers",
    cost: 6000000,
    description: "Mikayla is one of the Gazer's elite pilots, and has baited many fleets to their deaths. She's bold and brash, but always keeps her cool, even under high pressure.",
    specialty: "Pilot",
    equipment: null,
    image: "Images/Crew/I_never_Did707-civitai.webp",
  },
  {
    title: 'David "Tabs" Sharp',
    skillLevel: 8,
    alignment: "Talons",
    cost: 6000000,
    description: "A pilot prodigy ever since he could get behind a wheel, Tabs has been a part of some of the Talon's riskiest operations. He's a little haughty, though.",
    specialty: "Pilot",
    equipment: 7,
    image: "https://placehold.co/200x200/512929/e7a3a3?text=David+%22Tabs%22+Sharp",
  },
  {
    title: "Tera en Chasteaux",
    skillLevel: null,
    alignment: "Federation",
    cost: 7000000,
    description: "Tera's been through some of the best pilot training the Federation has to offer, and was in control of her own patrol fleet around Freeport space for awhile.",
    specialty: "Pilot",
    equipment: null,
    image: "Images/Crew/corporat2-civitai.webp",
  },
  {
    title: "Dorian Krueger",
    skillLevel: 8,
    alignment: "Federation",
    cost: 9000000,
    description: "Dorian is a battle-hardened pilot from one of the Federation's SOF. He's a man of few words, but every rare word of his carries intimidating weight.",
    specialty: "Pilot",
    equipment: null,
    image: "https://placehold.co/200x200/512929/e7a3a3?text=Dorian+Krueger",
  },
  {
    title: "Ise Ley'is",
    skillLevel: 10,
    alignment: "Luos Syndicate",
    cost: 9000000,
    description: "Ise was a high-rank in the Core Ring PMC, Dramvel, but it has since dissolved after the war. She's ruthless, and will only respect you if you are, too.",
    specialty: "Pilot",
    equipment: null,
    image: "Images/Crew/matasvolkovas350-civitai.webp",
  },
  {
    title: "Misa",
    skillLevel: null,
    alignment: "Neutral",
    cost: 14000000,
    description: "While Lux is one of the best pilots up for hire, she also has a sense of humor. She doesn't talk about her past very much, and not much of her is known.",
    specialty: "Pilot",
    equipment: null,
    image: "Images/Crew/misa-amane-indotort-civitai.webp",
  },
  {
    title: "Zetta",
    skillLevel: null,
    alignment: "Neutral",
    cost: 18000000,
    description: "His origins unknown, some think he's an Al, others think he's a Herald. He is obedient to those who lead him, but only if you are competent enough.",
    specialty: "Pilot",
    equipment: null,
    image: "https://placehold.co/200x200/512929/e7a3a3?text=Zetta",
  },
  // --- ENGINEERS ---
  {
    title: "Enrico Jourdan",
    skillLevel: null,
    alignment: "Neutral",
    cost: 1000000,
    description: "Kind hearted and loyal, Enrico can do a lot of handiwork for relatively cheap. He doesn't ask many questions either, he just loves doing his job.",
    specialty: "Engineer",
    equipment: null,
    image: "https://placehold.co/200x200/512929/e7a3a3?text=Enrico+Jourdan",
  },
  {
    title: "Derek Windtalker",
    skillLevel: 5,
    alignment: "Neutral",
    cost: 2000000,
    description: "Derek is from a very rare line mechanics. He claims his people were one with nature; he believes that he is one with metal, wires, and static.",
    specialty: "Engineer",
    equipment: null,
    image: "https://placehold.co/200x200/512929/e7a3a3?text=Derek+Windtalker",
  },
  {
    title: "Alena Bach",
    skillLevel: null,
    alignment: "Neutral",
    cost: 2000000,
    description: "Alena was an exceptional inventor from when she was child. She just started her career in starship mechanics, and would like to impress you with her work.",
    specialty: "Engineer",
    equipment: null,
    image: "https://placehold.co/200x200/512929/e7a3a3?text=Alena+Bach",
  },
  {
    title: "Malcolm Red",
    skillLevel: 7,
    alignment: "Neutral",
    cost: 2000000,
    description: "Malcolm blames exploding ships, bandit raids and bounty hunters as to why he has been barely able to actually do his job. Skilled with a crowbar.",
    specialty: "Engineer",
    equipment: null,
    image: "https://placehold.co/200x200/512929/e7a3a3?text=Malcolm+Red",
  },
  {
    title: "Adan Cervantes",
    skillLevel: null,
    alignment: "Neutral",
    cost: 3000000,
    description: "Terrible radiation burns cover his skin, so Adan relies on a life-support suit for his survival. That being said, he's highly intelligent and insightful.",
    specialty: "Nuclear Engineer",
    equipment: null,
    image: "https://placehold.co/200x200/512929/e7a3a3?text=Adan+Cervantes",
  },
  {
    title: "Trainwreck",
    skillLevel: null,
    alignment: "Red Daggers",
    cost: 3000000,
    description: "\"Study for 10 years, toll for 5 more, get passed up in favour of some Fed snot. Sure, I can keep a shit sandwich moving, but sell it and let me build you a tank.\"",
    specialty: "Engineer",
    equipment: null,
    image: "https://placehold.co/200x200/512929/e7a3a3?text=Trainwreck",
  },
  {
    title: 'Trisha "Props" Lim',
    skillLevel: 8,
    alignment: "Neutral",
    cost: 3000000,
    description: "Props is a hobbyist mechanic and loves to tinker. As a kid, she loved gears and wires over dolls. She also has a very active and bubbly personality.",
    specialty: "Mechanic",
    equipment: null,
    image: "Images/Crew/engineer-indotort-civitai.webp",
  },
  {
    title: "Troy Hall",
    skillLevel: 7,
    alignment: "Neutral",
    cost: 3000000,
    description: "With a love for working with machines, Troy could spend many hours inside a workshop. His metal arm can be put to many good uses.",
    specialty: "Engineer",
    equipment: null,
    image: "https://placehold.co/200x200/512929/e7a3a3?text=Troy+Hall",
  },
  {
    title: "Cindy Kayoko",
    skillLevel: null,
    alignment: "Red Daggers",
    cost: 4000000,
    description: "Popular among the Red Daggers, Cindy has worked with an immeasurable amount of questionable machinery. She's not much for politics.",
    specialty: "Engineer",
    equipment: null,
    image: "Images/Crew/liyihao1999-civitai.webp",
  },
  {
    title: "Amy McCartney",
    skillLevel: null,
    alignment: "Federation",
    cost: 4000000,
    description: "While Amy is a revered scientist, she's also graceful and likes to sing as a hobby. While she's a little shy, she would love it if you had a tavern.",
    specialty: "Scientist (Engineer)",
    equipment: null,
    image: "https://placehold.co/200x200/512929/e7a3a3?text=Amy+McCartney",
  },
  {
    title: "Roxanne Gilliam",
    skillLevel: 4,
    alignment: "Talons",
    cost: 4000000,
    description: "Roxanne led the forefront of nuclear research in Talon labs, and has contributed highly to the advancement of anti-matter technology.",
    specialty: "Nuclear Research (Engineer)",
    equipment: null,
    image: "https://placehold.co/200x200/512929/e7a3a3?text=Roxanne+Gilliam",
  },
  {
    title: "Mereille Fairley",
    skillLevel: null,
    alignment: "Federation",
    cost: 4000000,
    description: "Equip a geek with some of the Federation's best gadgets, and you get Mireille. She seems to have a device for almost any situation.",
    specialty: "Gadgeteer (Engineer)",
    equipment: null,
    image: "https://placehold.co/200x200/512929/e7a3a3?text=Mereille+Fairley",
  },
  {
    title: "Arthur Foster",
    skillLevel: null,
    alignment: "Neutral",
    cost: 5000000,
    description: "Studied under big titles, offers skills for a challenge.",
    specialty: "Engineer",
    equipment: null,
    image: "https://placehold.co/200x200/512929/e7a3a3?text=Arthur+Foster",
  },
  {
    title: "Reid Enos",
    skillLevel: null,
    alignment: "Neutral",
    cost: 6000000,
    description: "Mad scientist, knows lots about nuclear tech.",
    specialty: "Nuclear Tech (Engineer)",
    equipment: null,
    image: "https://placehold.co/200x200/512929/e7a3a3?text=Reid+Enos",
  },
  // --- Doctors ---
  {
    title: "Kelly Moss",
    skillLevel: null,
    alignment: "Neutral",
    cost: 0,
    description: "Kelly was part of a volunteer program to aid the unfortunate in poverty-stricken planets. Cannot be alone in an advanced infirmary.",
    specialty: "Medic",
    equipment: null,
    image: "Images/Crew/corporat4-civitai.webp",
  },
  {
    title: "Bethany Parks",
    skillLevel: 5,
    alignment: "Federation",
    cost: 1000000,
    description: "Straight out of medical school, Bethany seeks to get field experience. She would like nothing more than to be a space doctor. Loves cats.",
    specialty: "Medic",
    equipment: null,
    image: "Images/Crew/KandooAI-civitai.webp",
  },
  {
    title: "Ignacio Lopez",
    skillLevel: null,
    alignment: "Neutral",
    cost: 2000000,
    description: "Ignacio cares for nothing more than to study his medical books, and as long as you give him a workplace, he will be a competent medic.",
    specialty: "Medic",
    equipment: null,
    image: "Images/Crew/AIDigitalMediaAgency-civitai.webp",
  },
  {
    title: "Tina Wei",
    skillLevel: null,
    alignment: "Neutral",
    cost: 4000000,
    description: "Former merc medic, used to stress of high demand.",
    specialty: "Merc Medic",
    equipment: null,
    image: "https://placehold.co/200x200/512929/e7a3a3?text=Tina+Wei",
  },
  {
    title: "Lupe",
    skillLevel: 7,
    alignment: "Red Daggers",
    cost: 4000000,
    description: "He's technically a doctor... just don't expect him to be very conventional. He's notorious among the pirates as a miracle worker, however.",
    specialty: "Unconventional Doctor",
    equipment: null,
    image: "https://placehold.co/200x200/512929/e7a3a3?text=Lupe",
  },
  {
    title: "Devon Trice",
    skillLevel: null,
    alignment: "Blackhawk Elite",
    cost: 5000000,
    description: "Stalwart Blackhawk, favors less violent life, skilled in combat.",
    specialty: "Medic (Combat Skilled)",
    equipment: null,
    image: "https://placehold.co/200x200/512929/e7a3a3?text=Devon+Trice",
  },
  {
    title: "Lyra Miralda",
    skillLevel: null,
    alignment: "Neutral",
    cost: 7000000,
    description: "Young, in medical textbooks, quick, efficient, a little awkward.",
    specialty: "Medic",
    equipment: null,
    image: "https://placehold.co/200x200/512929/e7a3a3?text=Lyra+Miralda",
  },
  // --- Ship Gunners ---
  {
    title: "Brian Richardson",
    skillLevel: null,
    alignment: "Neutral",
    cost: 1000000,
    description: "Brian knows everything about ship weapons. While still a student, he'd drop his studies in a heart beat just to be a ship gunner.",
    specialty: "Ship Weapons",
    equipment: null,
    image: "https://placehold.co/200x200/512929/e7a3a3?text=Brian+Richardson",
  },
  {
    title: "Seer",
    skillLevel: null,
    alignment: "Red Daggers",
    cost: 1000000,
    description: "A bad history of theft, murder, and drug addiction, Seer is the prime example of a pirate. Even the Red Daggers see him as unsavoury.",
    specialty: "Ship Gunner",
    equipment: null,
    image: "https://placehold.co/200x200/512929/e7a3a3?text=Seer",
  },
  {
    title: "Elizabeth Tyler",
    skillLevel: null,
    alignment: "Federation",
    cost: 2000000,
    description: "Part of rare Fed patrols, met action but inexperienced.",
    specialty: "Ship Gunner",
    equipment: null,
    image: "Images/Crew/reijlita2-civitai.webp",
  },
  {
    title: "Alton Daniel",
    skillLevel: null,
    alignment: "Neutral",
    cost: 2000000,
    description: "A man who comes from some backwater planet and somehow happens to be skilled in the highly stressful and violent art of ship gunning.",
    specialty: "Ship Gunner",
    equipment: null,
    image: "https://placehold.co/200x200/512929/e7a3a3?text=Alton+Daniel",
  },
  {
    title: "John Pope",
    skillLevel: null,
    alignment: "Neutral",
    cost: 3000000,
    description: "Former merchant, quick aim from bandit attacks.",
    specialty: "Ship Gunner",
    equipment: null,
    image: "https://placehold.co/200x200/512929/e7a3a3?text=John+Pope",
  },
  {
    title: "Theresa Herder",
    skillLevel: null,
    alignment: "Blackhawk Elite",
    cost: 3000000,
    description: "Former Fed gunner, Blackhawk Elite, disciplined but laid-back off work.",
    specialty: "Ship Gunner",
    equipment: null,
    image: "Images/Crew/IsekaiLanayaya4-civitai.webp",
  },
  {
    title: "Vis'yeth",
    skillLevel: null,
    alignment: "Luos Syndicate",
    cost: 4000000,
    description: "Mysterious, took down three cruisers himself in Haven defence.",
    specialty: "Ship Gunner",
    equipment: null,
    image: "https://placehold.co/200x200/512929/e7a3a3?text=Vis%27yeth",
  },
  {
    title: 'Clara "Sun" Howell',
    skillLevel: 8,
    alignment: "Neutral",
    cost: 4000000,
    description: "Fiery and passionate, fun to tease about being a ginger.",
    specialty: "Ship Gunner",
    equipment: null,
    image: "Images/Crew/corporat5-civitai.webp",
  },
  {
    title: "Faith Nichols",
    skillLevel: null,
    alignment: "Federation",
    cost: 4000000,
    description: "From Fed SOF, high-tech equipment, very innocent.",
    specialty: "Ship Gunner",
    equipment: null,
    image: "Images/Crew/we11-civitai.webp",
  },
  {
    title: "Comet",
    skillLevel: 9,
    alignment: "Neutral",
    cost: "Special cost",
    description: "Her body seems to mingle with energy sources whenever she's near them, almost as if it courses through her veins...",
    specialty: "Ship Gunner",
    equipment: null,
    image: "Images/Crew/sorcerer-crew-midjourney.webp",
  },
  {
    title: "Viktor",
    skillLevel: 8,
    alignment: "Neutral",
    cost: 5000000,
    description: "He is very down to earth and simple (in the sense of being a professional ship gunner). He's reliable, and everybody just calls him Viktor.",
    specialty: "Ship Gunner",
    equipment: null,
    image: "https://placehold.co/200x200/512929/e7a3a3?text=Viktor",
  },
  {
    title: 'Tavia "Echo" Tsun',
    skillLevel: 8,
    alignment: "Talons",
    cost: 5000000,
    description: "Echo is of a rare breed from the Talons who offers up her skills for hire. She looks intimidating, but she's actually pretty down-to-earth... just don't call her Tavi.",
    specialty: "Ship Gunner",
    equipment: null,
    image: "Images/Crew/awegirl-reijlita-civitai (1).webp",
  },
  {
    title: "Lt. Bill Smith",
    skillLevel: 8,
    alignment: "Federation",
    cost: 5000000,
    description: "Don't let his boring name fool you-Bill has a track record for being a veteran gunner in the Federation Navy. You can rely on him to hit hard and ruthlessly.",
    specialty: "Ship Gunner",
    equipment: null,
    image: "https://placehold.co/200x200/512929/e7a3a3?text=Lt.+Bill+Smith",
  },
  {
    title: "Amanda Lynch",
    skillLevel: null,
    alignment: "Neutral",
    cost: 6000000,
    description: "She's fast, strong-willed and packs a punch, Amanda has never lost in a fleet fight. Her efforts have defended industrial from bandit incursions.",
    specialty: "Ship Gunner",
    equipment: null,
    image: "https://placehold.co/200x200/512929/e7a3a3?text=Amanda+Lynch",
  },
  // --- Combat & Security ---
  {
    title: "Owen Baker",
    skillLevel: 8,
    alignment: "Neutral",
    cost: 1000000,
    description: "Owen's home world was under constant threat from bandits, and he was part of the planet's resistance force that drove them out for good.",
    specialty: "Guerilla warfare",
    equipment: 4,
    image: "https://placehold.co/200x200/512929/e7a3a3?text=Owen+Baker",
  },
  {
    title: "Sasha Baker",
    skillLevel: null,
    alignment: "Neutral",
    cost: 1000000,
    description: "The younger sister of Owen, Sasha, too, helped drive out the bandits from her homeworld. She's a crack shot with her rifle, and has too many kill notches.",
    specialty: "Sniping",
    equipment: 7,
    image: "Images/Crew/soldiergirl2-indotort-civitai.webp",
  },
  {
    title: "Myrie Shaffer",
    skillLevel: null,
    alignment: "Red Daggers",
    cost: 2000000,
    description: "Myrie worked for a notorious pirate gang that ran the black market in nearly a fifth of the galaxy. When she's present, a deal will go her way.",
    specialty: "Storming",
    equipment: 3,
    image: "Images/Crew/fepirate2-indotort-midjourney.webp",
  },
  {
    title: "Pierre Mikisugi",
    skillLevel: 4,
    alignment: "Neutral",
    cost: 2000000,
    description: "Good cops usually come with a decent set of skills, and Pierre is no exception. He's been a part of plenty of high-stake raids on criminal warehouses.",
    specialty: "Ship security",
    equipment: 8,
    image: "https://placehold.co/200x200/512929/e7a3a3?text=Pierre+Mikisugi",
  },
  {
    title: "Sophie Haynes",
    skillLevel: 6,
    alignment: "Federation",
    cost: 2000000,
    description: "A good friend of Faith Nichols, Sophie came from the same detachment. She's quick and very witty, and has a sixth sense for no-good intentions.",
    specialty: "Covert ops",
    equipment: 5,
    image: "Images/Crew/stu42-civitai.webp",
  },
  {
    title: "Grzegorz Grzegrzółka",
    skillLevel: null,
    alignment: "Neutral",
    cost: 2000000,
    description: "Always seen working together with Pierre, Gregorz is an ex-cop working to pay for his little sister's education. He often does things his own way.",
    specialty: "Ship security",
    equipment: null,
    image: "https://placehold.co/200x200/512929/e7a3a3?text=Grzegorz+Grzegrzółka",
  },
  {
    title: "Ley'ra Laur",
    skillLevel: 8,
    alignment: "Luos Syndicate",
    cost: 3000000,
    description: "A soldier from the Outer Ring. Ley'ra has nerves of steel, always taking point. She lost her high-tech Erinyes armour from the war. Out of work, she's... shy.",
    specialty: "Point position",
    equipment: 6,
    image: "Images/Crew/lou-ll-asuka-079-2.jpg",
  },
  {
    title: 'Dani "Cuts" Laine',
    skillLevel: null,
    alignment: "Blackhawk Elite",
    cost: 3000000,
    description: "Aggressive and blunt, Dani makes a natural, valiant fireteam leader. She helped drive crime rates down hard in 3 star systems.",
    specialty: "Long-range",
    equipment: 6,
    image: "Images/Crew/eagelaxis-civitai.webp",
  },
  {
    title: "Ward Shapiro",
    skillLevel: null,
    alignment: "Neutral",
    cost: 3000000,
    description: "Ward joined a small local security force as a doss to finish writing his book, but got conscripted for combat and shipped out to the front lines.",
    specialty: "Sentry",
    equipment: 4,
    image: "https://placehold.co/200x200/512929/e7a3a3?text=Ward+Shapiro",
  },
  {
    title: "Sgt. Raul Miller",
    skillLevel: 8,
    alignment: "Federation",
    cost: 3000000,
    description: "Raul was stationed on an ice planet for nearly a decade. He's dealt with a lot of pirate and cartel activity, and can navigate across many kinds of terrain.",
    specialty: "Front-line assault",
    equipment: 5,
    image: "https://placehold.co/200x200/512929/e7a3a3?text=Sgt.+Raul+Miller",
  },
  {
    title: 'Erik "Sooter" Burke',
    skillLevel: 5,
    alignment: "Red Daggers",
    cost: 3000000,
    description: "He's not very intelligent in other fields, but give him a weapon and he will make a great rank-and-file pirate. Just don't make him angry.",
    specialty: "Front-line assault",
    equipment: 6,
    image: "Images/Crew/malepirate2-indotort-midjourney.webp",
  },
  {
    title: "Vikram Solar",
    skillLevel: 6,
    alignment: "Neutral",
    cost: 4000000,
    description: "He has a penchant for laser based weapons and a refusal to use conventional ammunition because it's \"messy\". He's a bit of a neat freak that way.",
    specialty: "Long-range (Laser Weapons)",
    equipment: 8,
    image: "https://placehold.co/200x200/512929/e7a3a3?text=Vikram+Solar",
  },
  {
    title: "Darrel Wallace",
    skillLevel: null,
    alignment: "Blackhawk Elite",
    cost: 4000000,
    description: "Darrel has flown in many fleets, making sure that on-ship security is as good as it can be. The Blackhawks are tough, and Darrel mirrors that to a tee.",
    specialty: "Sentry (On-ship security)",
    equipment: null,
    image: "https://placehold.co/200x200/512929/e7a3a3?text=Darrel+Wallace",
  },
  {
    title: "Rooks King",
    skillLevel: null,
    alignment: "Gazers",
    cost: 5000000,
    description: "Rooks is a skilled Gazer operator, but can be found hanging around Dustkeepers often. His comrades learned to ignore his disappearances.",
    specialty: "Guerilla warfare",
    equipment: 10,
    image: "https://placehold.co/200x200/512929/e7a3a3?text=Rooks+King",
  },
  {
    title: "Livia Amaruq",
    skillLevel: 8,
    alignment: "Federation",
    cost: 5000000,
    description: "An ex-operative from a one of the Federation's top SOF groups, Livia worked on the same ice planet Sgt. Raul worked at. She's as deadly as she looks.",
    specialty: "Hand-to-hand",
    equipment: 10,
    image: "https://placehold.co/200x200/512929/e7a3a3?text=Livia+Amaruq",
  },
  {
    title: "Scot Shephard",
    skillLevel: null,
    alignment: "Neutral",
    cost: 5000000,
    description: "SWAT in a big city, seen the worst of humanity.",
    specialty: "Storming",
    equipment: 8,
    image: "https://placehold.co/200x200/512929/e7a3a3?text=Scot+Shephard",
  },
  {
    title: "Alessia",
    skillLevel: 8,
    alignment: "Talons",
    cost: 5000000,
    description: "Hot-headed, Alessia wants nothing more than to strangle her brother, Ricce, to death. She won't say much about it, but you best not get in her way.",
    specialty: "Long-ranged",
    equipment: 6,
    image: "Images/Crew/detective-we11-civitai.webp",
  },
  {
    title: "Ricce",
    skillLevel: 6,
    alignment: "Federation",
    cost: 5000000,
    description: "A stalwart soldier in high tech power armour, Ricce is a force to be reckoned with on the battlefield. When asked about his sister Alessia, he'll remain silent.",
    specialty: "Front-line assault",
    equipment: null,
    image: "https://placehold.co/200x200/512929/e7a3a3?text=Ricce",
  },
  {
    title: "Arabelle Meyer",
    skillLevel: null,
    alignment: "Neutral",
    cost: 5000000,
    description: "It takes discipline, patience and cunning to be a professional assassin, and Arabelle has all of them. She's exceptionally good at hiding out of sight.",
    specialty: "Sniping (Assassin)",
    equipment: 9,
    image: "https://placehold.co/200x200/512929/e7a3a3?text=Arabelle+Meyer",
  },
  {
    title: "Marcelo Lee",
    skillLevel: null,
    alignment: "Talons",
    cost: 6000000,
    description: "Talons up for hire are very rare, and Marcelo is one of the few. He is equipped with lots of nifty gadgets, and has experience in running solo missions.",
    specialty: "Guerilla warfare",
    equipment: 7,
    image: "https://placehold.co/200x200/512929/e7a3a3?text=Marcelo+Lee",
  },
  {
    title: "Lt. Jenny Larue",
    skillLevel: null,
    alignment: "Federation",
    cost: 6000000,
    description: "A top tier officer in the Federation SOF, Jen commands with a valiant heart, and is known for her \"strict kindness.\" Often finds herself working under Tera.",
    specialty: "Point position",
    equipment: 8,
    image: "Images/Crew/Maggs-civitai.webp",
  },
  {
    title: "Martin Jenkins",
    skillLevel: null,
    alignment: "Blackhawk Elite",
    cost: 6000000,
    description: "One of the iconic Blackhawk Elite shock troopers, Martin leads the charge into all of his conflicts with an unstoppable momentum.",
    specialty: "Storming (Shock Trooper)",
    equipment: 10,
    image: "https://placehold.co/200x200/512929/e7a3a3?text=Martin+Jenkins",
  },
  {
    title: "My'hra Jos",
    skillLevel: null,
    alignment: "Luos Syndicate",
    cost: 7000000,
    description: "My'hra was a skilled ground officer in the small Outer Ring PMC, the Cerberus Legion. She helped defend the Abyss system from the Federation onslaught.",
    specialty: "Infiltration",
    equipment: null,
    image: "https://placehold.co/200x200/512929/e7a3a3?text=My%27hra+Jos",
  },
  {
    title: "Patch Newton",
    skillLevel: null,
    alignment: "Neutral",
    cost: 7000000,
    description: "A notorious assassin who's very deadly behind a rifle. His unique hardware was built by himself; It's often said that he's \"one with his armour.\"",
    specialty: "Sniping (Assassin)",
    equipment: null,
    image: "https://placehold.co/200x200/512929/e7a3a3?text=Patch+Newton",
  },
  {
    title: "Locust",
    skillLevel: null,
    alignment: "Neutral",
    cost: 14000000,
    description: "\"Rider of Famine.\" Locust can rend armies with his blade. The highly classified Apocalypse program produced four of the greatest soldiers in the galaxy.",
    specialty: "Hand-to-hand (Blade)",
    equipment: null,
    image: "https://placehold.co/200x200/512929/e7a3a3?text=Locust",
  },
  {
    title: "Plague",
    skillLevel: null,
    alignment: "Neutral",
    cost: 15000000,
    description: "\"Rider of Pestilence.\" Plague has the toughest armour of the four, and is also the strongest in brute force. The four Riders have since separated.",
    specialty: "Front-line assault (Brute Force)",
    equipment: 9,
    image: "https://placehold.co/200x200/512929/e7a3a3?text=Plague",
  },
  {
    title: "Archangel",
    skillLevel: null,
    alignment: "Federation",
    cost: 17000000,
    description: "\"Rider of War.\" Archangel wields a one-of-a-kind, hand-held lon Cannon, capable of leveling city blocks. She is still loyal to the Federation.",
    specialty: "Heavy weapons",
    equipment: null,
    image: "https://placehold.co/200x200/512929/e7a3a3?text=Archangel",
  },
  {
    title: "Styx",
    skillLevel: null,
    alignment: "Herself",
    cost: 18000000,
    description: "\"Rider of Death.\" No one knows why, but Styx holds a terrible grudge against the Federation after her defection. She still respects her siblings, though.",
    specialty: "Infiltration",
    equipment: null,
    image: "https://placehold.co/200x200/512929/e7a3a3?text=Styx",
  },
  // --- CYBER SECURITY OFFICERS ---
  {
    title: "Perry West",
    skillLevel: 8,
    alignment: "Neutral",
    cost: 3000000,
    description: "Hailing from a large company, Perry is perfectly capable at handling most electronic warfare. Your ship should be well defended with him.",
    specialty: "Electronic warfare",
    equipment: null,
    image: "https://placehold.co/200x200/512929/e7a3a3?text=Perry+West",
  },
  {
    title: "Erica Chung",
    skillLevel: null,
    alignment: "Neutral",
    cost: 4000000,
    description: "After dropping out of university, Erica cut ties to everyone, stopped drinking replicated water, and now wants to join your ship crew.",
    specialty: "Cyber Security",
    equipment: null,
    image: "Images/Crew/asianwoman-indotort-midjourney.png",
  },
  {
    title: "Damian Galt",
    skillLevel: null,
    alignment: "Red Daggers",
    cost: 4000000,
    description: "This man brings an excellent service record and forty exobytes of illegally-obtained porn. Will awkwardly hit on female crew. Constantly. Over the PA.",
    specialty: "Cyber Security",
    equipment: null,
    image: "https://placehold.co/200x200/512929/e7a3a3?text=Damian+Galt",
  },
  {
    title: "Slash Singer",
    skillLevel: null,
    alignment: "Neutral",
    cost: 4000000,
    description: "An ex-military intelligence officer who can go head to head with some of the most notorious hackers in the galaxy in cyberwarfare.",
    specialty: "Programmer (Security Bypass)",
    equipment: null,
    image: "https://placehold.co/200x200/512929/e7a3a3?text=Slash+Singer",
  },
  {
    title: "Veslav Smertodov",
    skillLevel: 9,
    alignment: "Talons",
    cost: 6000000,
    description: "A well-known Talon hacker who's an expert with Al and is extremely good at multitasking. She's often encountered Veslav in fierce cyber battles.",
    specialty: "Hacker (AI Expert)",
    equipment: null,
    image: "https://placehold.co/200x200/512929/e7a3a3?text=Veslav+Smertodov",
  },
  {
    title: "Arachne",
    skillLevel: null,
    alignment: "Federation",
    cost: 6000000,
    description: "Ex-military intelligence officer, can go head-to-head with notorious hackers in cyber warfare.",
    specialty: "Cyber warfare",
    equipment: null,
    image: "https://placehold.co/200x200/512929/e7a3a3?text=Arachne",
  },
  {
    title: "Uplink",
    skillLevel: null,
    alignment: "Neutral",
    cost: 12000000,
    description: "Installing her isn't cheap, but she's one of the very few Al androids with sapience, Uplink wants nothing more than more access to information. All of it.",
    specialty: "AI Android (Information Access)",
    equipment: null,
    image: "https://placehold.co/200x200/512929/e7a3a3?text=Uplink",
  },
  // --- SCIENTISTS ---
  {
    title: "Lauren L. Lazuli",
    skillLevel: 4,
    alignment: "Neutral",
    cost: 0,
    description: "Your crew found her in your lab after leaving a port once, caffeine packets everywhere while she was feverishly working on a thesis. She sleeps in the lab.",
    specialty: "Scientist (Thesis)",
    equipment: null,
    image: "Images/Crew/IsekaiLanayaya2-civitai.webp",
  },
  {
    title: "Curt Robertson",
    skillLevel: 6,
    alignment: "Federation",
    cost: 1000000,
    description: "Curt believes that you should never abandon your own body. He's a specialist in human biology, and is very tall at the result of his biological research.",
    specialty: "Human biology",
    equipment: null,
    image: "https://placehold.co/200x200/512929/e7a3a3?text=Curt+Robertson",
  },
  {
    title: "Emily Park",
    skillLevel: null,
    alignment: "Neutral",
    cost: 1000000,
    description: "Morally opposed to combat-purpose vessels, Dr. Newton is an expert at xenobiology and terraforming. She's a bit eccentric, though.",
    specialty: "Xenobiology, Terraforming",
    equipment: null,
    image: "Images/Crew/reijlita4-civitai.webp",
  },
  {
    title: "Sarah Escher",
    skillLevel: 6,
    alignment: "Red Daggers",
    cost: 2000000,
    description: "Incredibly intelligent, but with a very short attention span. Her frequent experiments with mana energy has earned her an eerie, permanent glow.",
    specialty: "Mana energy experiments",
    equipment: null,
    image: "https://placehold.co/200x200/512929/e7a3a3?text=Sarah+Escher",
  },
  {
    title: "Shinichi Yagazen",
    skillLevel: null,
    alignment: "Neutral",
    cost: 3000000,
    description: "With numerous years of study, his research has made an increase in the agricultural production of the galaxy by half a percent. Likes candied fish.",
    specialty: "Agricultural production research",
    equipment: null,
    image: "https://placehold.co/200x200/512929/e7a3a3?text=Shinichi+Yagazen",
  },
  {
    title: "Isaac J. Bidlack",
    skillLevel: null,
    alignment: "Federation",
    cost: 3000000,
    description: "Expert in biology, bioengineering, chemistry and biological warfare. Wanted for morally ambiguous experiments and creation of biological weapons.",
    specialty: "Biology, Bioengineering, Chemistry, Biological Warfare",
    equipment: null,
    image: "https://placehold.co/200x200/512929/e7a3a3?text=Isaac+J.+Bidlack",
  },
  {
    title: "Wilhelm von Welch",
    skillLevel: 8,
    alignment: "Neutral",
    cost: 5000000,
    description: "Both brilliant and a mad man at the same time, Wilhelm is a strict scientist who has an obsession with the pursuit of knowledge about the Heralds.",
    specialty: "Heralds research",
    equipment: null,
    image: "https://placehold.co/200x200/512929/e7a3a3?text=Wilhelm+von+Welch",
  },
  // --- PRODUCTION MANAGERS ---
  {
    title: "Sibyl",
    skillLevel: null,
    alignment: "Red Daggers",
    cost: 1000000,
    description: "Sibyl has worked in industrial wings for the Red Daggers for over 20 years. He knows lots of tricks and methods on mining and manufacturing.",
    specialty: "Mining, Manufacturing",
    equipment: null,
    image: "https://placehold.co/200x200/512929/e7a3a3?text=Sibyl",
  },
  {
    title: "Madeline Moran",
    skillLevel: null,
    alignment: "Blackhawk Elite",
    cost: 2000000,
    description: "The Blackhawk Elite's might is largely due to their hardware, and with production managers like Madeline, they're set for a long, long time.",
    specialty: "Hardware production",
    equipment: null,
    image: "Images/Crew/female-engineer-indotort-midjourney.webp",
  },
  {
    title: "Wesley Chalmers",
    skillLevel: 6,
    alignment: "Neutral",
    cost: 2000000,
    description: "Wesley will always get the job done, even if your ship is falling apart at the seams.",
    specialty: "Production Management",
    equipment: null,
    image: "https://placehold.co/200x200/512929/e7a3a3?text=Wesley+Chalmers",
  },
  {
    title: "Corrine Peyton",
    skillLevel: null,
    alignment: "Neutral",
    cost: 3000000,
    description: "Serious and authoritative in industrial wings, workers obey or face a long, deafening scolding.",
    specialty: "Industrial Management",
    equipment: null,
    image: "Images/Crew/LordTerror-civitai.webp",
  },
  {
    title: "Ty Piper",
    skillLevel: 7,
    alignment: "Federation",
    cost: 3000000,
    description: "Great production manager, excellent track record from Fed industrial systems, promotes efficiency and work ethics.",
    specialty: "Production Management (Efficiency)",
    equipment: null,
    image: "https://placehold.co/200x200/512929/e7a3a3?text=Ty+Piper",
  },
  {
    title: "May Padilla",
    skillLevel: 8,
    alignment: "Neutral",
    cost: 4000000,
    description: "Hard worker, speeds things up, likes to boast about her strength.",
    specialty: "Production Management",
    equipment: null,
    image: "https://placehold.co/200x200/512929/e7a3a3?text=May+Padilla",
  },
  {
    title: "Michael Danagger",
    skillLevel: null,
    alignment: "Neutral",
    cost: 6000000,
    description: "An extremely successful industrialist, Danagger's company provided fuel for the shipping businesses over a dozen systems.",
    specialty: "Industrialist",
    equipment: null,
    image: "https://placehold.co/200x200/512929/e7a3a3?text=Michael+Danagger",
  },
  // --- CHEFS & BARTENDERS ---
  {
    title: "Jorgen Masterson",
    skillLevel: null,
    alignment: "Neutral",
    cost: 1000000,
    description: "A retired mercenary who decided to become a chef. Having served on several prison transports, he is a capable and ingenious cook.",
    specialty: "Chef",
    equipment: null,
    image: "https://placehold.co/200x200/512929/e7a3a3?text=Jorgen+Masterson",
  },
  {
    title: "Mikka Akimoto",
    skillLevel: null,
    alignment: "Red Daggers",
    cost: 1000000,
    description: "Mikka specializes in Japanese and some other Asian cuisines. Sushi and ramen never went out of fashion after thousands of years.",
    specialty: "Chef (Japanese/Asian Cuisine)",
    equipment: null,
    image: "Images/Crew/chef-indotort-civitai.webp",
  },
  {
    title: "Patricia Cooper",
    skillLevel: null,
    alignment: "Neutral",
    cost: 2000000,
    description: "Patricia loves to cook, and when she's in a kitchen, she's the one who's in charge. She loves working with European cuisines.",
    specialty: "Chef (European Cuisine)",
    equipment: null,
    image: "https://placehold.co/200x200/512929/e7a3a3?text=Patricia+Cooper",
  },
  {
    title: "Vito Lozano",
    skillLevel: null,
    alignment: "Neutral",
    cost: 4000000,
    description: "Do not disturb; Chef at work. Nobody dares get in Vito's way when he's cooking. His spaghetti is perfection. *Will only use a fancy mess hall",
    specialty: "Chef",
    equipment: null,
    image: "Images/Crew/Italianchef-indotort-midjourney.webp",
  },
  {
    title: "Laura Sofía - Pérez Gómez",
    skillLevel: null,
    alignment: "Federation",
    cost: 1000000,
    description: "Typical bartender, listens to your problems, perfect for standard mixes.",
    specialty: "Bartender",
    equipment: null,
    image: "Images/Crew/female-chef-indotort-midjourney.webp",
  },
  {
    title: "Carolyn Brooks",
    skillLevel: null,
    alignment: "Neutral",
    cost: 2000000,
    description: "Playful and outgoing, always aiming to earn a smile with every serve. She's a great bartender who loves mixing the fancier drinks.",
    specialty: "Bartender (Fancy Drinks)",
    equipment: null,
    image: "https://placehold.co/200x200/512929/e7a3a3?text=Carolyn+Brooks",
  },
  {
    title: "Hal",
    skillLevel: null,
    alignment: "Neutral",
    cost: 4000000,
    description: "Former assassin, has many stories, might have 'special' mixes that need a lab.",
    specialty: "Bartender",
    equipment: null,
    image: "https://placehold.co/200x200/512929/e7a3a3?text=Hal",
  },
  {
    title: "Nettie",
    image: "https://placehold.co/250x250/20344d/F2E9E4?text=Nettie",
    cost: 0,
    specialty: "Survival",
    equipment: 2,
    skillLevel: 1,
    alignment: "Neutral",
    description: "A young girl found wandering the streets of an abandoned city in Faraday. She claims to not know her title nor her family. She survived for years, alone."
  },
  {
    title: "Kristina Hines",
    image: "https://placehold.co/250x250/20344d/F2E9E4?text=Kristina+Hines",
    cost: 1000000,
    specialty: "Long-range",
    equipment: 3,
    skillLevel: 4,
    alignment: 'Red Dagger Pirates',
    description: "A new recruit in the Wolf Hunt gang who has shown promise in her marksmanship. She's becoming a quick favourite to Yula, the gang leader."
  },
  {
    title: "Robby Delgarv",
    image: "https://placehold.co/250x250/20344d/F2E9E4?text=Robby+Delgarv",
    cost: 2000000,
    specialty: "Survival",
    equipment: 3,
    skillLevel: 5,
    alignment: "Neutral",
    description: "A Dustkeeper who likes to keep his gear modest. Has extensive knowledge on survival skills in harsh environments. Always seems to know what he's doing."
  },
  {
    title: "Maxim Cyril",
    image: "https://placehold.co/250x250/20344d/F2E9E4?text=Maxim+Cyril",
    cost: 2000000,
    specialty: "Medic",
    equipment: 6,
    skillLevel: 3,
    alignment: "Federation",
    description: "A field medic fresh out of med school, looking to bolster his battlefield experience. He's self-funded his own equipment, which is fairly expensive. His equipment is 'DOOSE'."
  },
  {
    title: "Francesca Osvalt",
    image: "https://placehold.co/250x250/20344d/F2E9E4?text=Francesca+Osvalt",
    cost: 2000000,
    specialty: "Front-line assault",
    equipment: 5,
    skillLevel: 5,
    alignment: 'Blackhawk Elite',
    description: "A Seraph employee who has worked on Fenris for several years. Her adventurous attitude eggs her to do something else. Her equipment is 'D0000 Blackhawk Elite'."
  },
  {
    title: "Moya LaCroix",
    image: "https://placehold.co/250x250/20344d/F2E9E4?text=Moya+LaCroix",
    cost: 3000000,
    specialty: "Front-line assault",
    equipment: 6,
    skillLevel: 5,
    alignment: "Neutral",
    description: "Moya is a dedicated lo Security veteran who's both a top fighter and is very knowledgable about his high-tech gear. He searches for his long lost twin, Faulka. His equipment is '00000SS'."
  },
  {
    title: "Faulka LaCroix",
    image: "https://placehold.co/250x250/20344d/F2E9E4?text=Faulka+LaCroix",
    cost: 3000000,
    specialty: "Sniping",
    equipment: 5,
    skillLevel: 6,
    alignment: "Neutral",
    description: "Faulka was an ex-lo Security operant, but has left for unknown reasons. Since then, she joined the Dustkeepers on Faraday as a skilled marksman."
  },
  {
    title: "'Ms. Green'",
    image: "https://placehold.co/250x250/20344d/F2E9E4?text=Ms.+Green",
    cost: 3000000,
    specialty: "Guerilla warfare",
    equipment: 5,
    skillLevel: 7,
    alignment: "Gazers",
    description: "Shady and mysterious, like all of the Gazers. She usually relays intel and orders to her comrades, but is known to take matters into her own hands."
  },
  {
    title: "Sya'ra Degala",
    image: "https://placehold.co/250x250/20344d/F2E9E4?text=Sya'ra+Degala",
    cost: 3000000,
    specialty: "Demolition",
    equipment: 6,
    skillLevel: 6,
    alignment: "Luos Syndicate",
    description: "Called the Mad Roller friends, Sya'ra has a love for weapons. She'll follow you around if you show any interest in weaponry. Likes to wear roller blades."
  },
  {
    title: "Jerilyn Hyata",
    image: "https://placehold.co/250x250/20344d/F2E9E4?text=Jerilyn+Hyata",
    cost: 5000000,
    specialty: "Infiltration",
    equipment: 6,
    skillLevel: 8,
    alignment: "Talons",
    description: "A Talon at the top of her class. She's snuck through some of the most complex security systems in the galaxy, most of them owned by the Blackhawk Elite."
  },
  {
    title: "Connell Xuan",
    image: "https://placehold.co/250x250/20344d/F2E9E4?text=Connell+Xuan",
    cost: 6000000,
    specialty: "Front-line assault",
    equipment: 8,
    skillLevel: 7,
    alignment: "Neutral",
    description: "It's thanks to men like Connell why the Dustkeeper base on Faraday has not been breached by the mutants. His valiant battlecry rallies his comrades. His equipment is '0000000'."
  },
  {
    title: "Maren Krause",
    image: "https://placehold.co/250x250/20344d/F2E9E4?text=Maren+Krause",
    cost: 7000000,
    specialty: "Hand-to-hand",
    equipment: 7,
    skillLevel: 9,
    alignment: "Federation",
    description: "Seeing Maren on the opposite end of your barrel means it's already too late. She prioritizes efficiency above all else, and she's very good at its practice."
  },
  {
    title: "Ley'ra Laur",
    image: "https://placehold.co/250x250/20344d/F2E9E4?text=Ley'ra+Laur",
    cost: 3000000,
    specialty: "Point position",
    equipment: 9,
    skillLevel: 8,
    alignment: "Luos Syndicate",
    description: "A soldier from the Outer Ring. Ley'ra has nerves of steel, always taking point. She lost her high-tech Erinyes armour from the war. Out of work, she's... shy. Her equipment is 'EEEEEEE.'.",
  },
  {
    title: "Lex StPierre",
    image: "https://placehold.co/250x250/20344d/F2E9E4?text=Lex+StPierre",
    cost: 7000000,
    specialty: "Sentry?",
    equipment: 9,
    skillLevel: 8,
    alignment: "Neutral",
    description: "He (or she) bolsters some of the greatest fighting skills and equipment in the galaxy... but he (or she) tends to not move until he (or she) is really needed."
  },
  {
    title: "'Begger'",
    image: "https://placehold.co/250x250/20344d/F2E9E4?text=Begger",
    cost: 20000000,
    specialty: "Heavy weapons",
    equipment: 10,
    skillLevel: 9,
    alignment: "Himself",
    description: "Some say he's a fifth Apoc, but he openly hates them with a passion. No one knows where he came from, only that he's bloodthirsty and lives for conflict."
  }
];


const archetype = [
  {
    title: "Volunteers",
    skillLevel: 0,
    alignment: "Neutral",
    cost: {
      x1: 0,
      x5: 0,
      x10: 0,
      x50: 0,
      x100: 0,
      x500: 0,
    },
    description:
      "Many people volunteer to be a part of a ship crew. These people can get the job done, but they're not professionals.",
  },
  {
    title: "Civilian Workers",
    skillLevel: 0,
    alignment: "Neutral",
    cost: {
      x1: 100000,
      x5: 300000,
      x10: 500000,
      x50: 1000000,
      x100: 2000000,
      x500: 9000000,
    },
    description:
      "Plenty of civilians are looking for legitimate work, and many of them qualify as space-faring crew members.",
  },
  {
    title: "Industry Labourers",
    skillLevel: 0,
    alignment: "Neutral",
    cost: {
      x1: 100000,
      x5: 300000,
      x10: 500000,
      x50: 1000000,
      x100: 2000000,
      x500: 9000000,
    },
    description:
      "Looking to get work done? No other crew can get your mining, manufacturing, and processing needs finished as efficiently.",
  },
  {
    title: "Researchers",
    skillLevel: 0,
    alignment: "Neutral",
    cost: {
      x1: 100000,
      x5: 300000,
      x10: 500000,
      x50: 1000000,
      x100: 2000000,
      x500: 9000000,
    },
    description:
      "For the pursuit of science and discovery among endless amount of stars, researchers make for a very intelligent crew.",
  },
  {
    title: "Bandits",
    image: "Images/Crew/cyber-samurai-indotort-midjourney.webp",
    skillLevel: 0,
    alignment: "Pirates",
    cost: {
      x1: 100000,
      x5: 300000,
      x10: 500000,
      x50: 1000000,
      x100: 2000000,
      x500: 9000000,
    },
    description:
      "The average bandit can make a hard working crew member, provided you can get them to respect you.",
  },
  {
    title: "Explorers",
    skillLevel: 0,
    alignment: "Neutral",
    cost: {
      x1: 100000,
      x5: 300000,
      x10: 500000,
      x50: 1000000,
      x100: 2000000,
      x500: 9000000,
    },
    description:
      "Cursed with an endless thing for exploration, explorers long for the stars as much as you do. Almost.",
  },
  {
    title: "Medics",
    skillLevel: 0,
    alignment: "Neutral",
    cost: {
      x1: 100000,
      x5: 300000,
      x10: 500000,
      x50: 1000000,
      x100: 2000000,
      x500: 9000000,
    },
    description:
      "Medical knowledge is a valuable asset. Unfortunately, not every one's a medic, so why not hire some professionals?",
  },
  {
    title: "Engineers",
    skillLevel: 0,
    alignment: "Neutral",
    cost: {
      x1: 100000,
      x5: 300000,
      x10: 500000,
      x50: 1000000,
      x100: 2000000,
      x500: 9000000,
    },
    description:
      "It's usually wise to have a good amount of engineers available. No one's better at maintaining your vessel and its machinery.",
  },
  {
    title: "Mercenaries",
    skillLevel: 0,
    alignment: "Neutral",
    cost: {
      x1: 100000,
      x5: 300000,
      x10: 500000,
      x50: 1000000,
      x100: 2000000,
      x500: 9000000,
    },
    description:
      "Mercenaries make up the majority of the galaxy's ship crews that aren't pirates or part of the Federation.",
  },
  {
    title: "Seraphs",
    skillLevel: 0,
    alignment: "Blackhawk Elite",
    cost: {
      x1: 100000,
      x5: 300000,
      x10: 500000,
      x50: 1000000,
      x100: 2000000,
      x500: 9000000,
    },
    description:
      "Essentially Blackhawks-in-training, the Seraphs is where they all start. While relatively inexperienced, they show promise.",
  },
  {
    title: "Red Dagger Pirates",
    image: "Images/Crew/future-akatsuki-indotort-midjourney.webp",
    skillLevel: 0,
    alignment: "Red Daggers",
    cost: {
      x1: 100000,
      x5: 300000,
      x10: 500000,
      x50: 1000000,
      x100: 2000000,
      x500: 9000000,
    },
    description:
      "Above the average pirate and bandit lies the average Red Dagger. Their cunning and hardy instincts are exceptional.",
  },
  {
    title: "Navy Soldiers",
    skillLevel: 0,
    alignment: "Federation",
    cost: {
      x1: 100000,
      x5: 300000,
      x10: 500000,
      x50: 1000000,
      x100: 2000000,
      x500: 9000000,
    },
    description:
      "The Federation trains decent and disciplined crew members. They will give to you you are a valiant and capable leader.",
  },
  {
    title: "Core Ring Mercs",
    skillLevel: 0,
    alignment: "Luos Syndicate",
    cost: {
      x1: 100000,
      x5: 300000,
      x10: 500000,
      x50: 1000000,
      x100: 2000000,
      x500: 9000000,
    },
    description:
      "Luos Core Ring mercs are both fearsome and sinister, and deathly loyal to those who prove their strength.",
  },
  {
    title: "Dustkeepers",
    skillLevel: 0,
    alignment: "Neutral",
    cost: {
      x1: 100000,
      x5: 300000,
      x10: 500000,
      x50: 1000000,
      x100: 2000000,
      x500: 9000000,
    },
    description:
      "Highly skilled with a very rich variety of talents, Dustkeepers can make a very capable crew for almost any job.",
  },
];

function addCrewToSection(crewArray, choicePrefix, sectionID, dataType) {
  const targetSection = document.getElementById(sectionID);

  if (!targetSection) {
    console.error(`Target section with ID "${sectionID}" not found.`);
    return;
  }

  if (!Array.isArray(crewArray)) {
    console.error(
      `Global variable "${crewArray}" is not an array or does not exist.`
    );
    return;
  }

  // Check if the section already has population to prevent duplicate entries
  // Assuming the first item's title is representative for checking
  if (crewArray.length > 0) {
    // Sanitize the title for use as an ID
    const checkDiv = document.getElementById(
      `${choicePrefix}-${crewArray[0].title
        .replace(/\s/g, "-")
        .replace(/[^a-zA-Z0-9-]/g, "")}`
    );
    if (document.contains(checkDiv)) {
      return; // Section already populated, do nothing
    }
  }

  // If not populated, create new divs to populate choices
  crewArray.forEach((item) => {
    const newDiv = document.createElement("div");
    newDiv.classList.add("choice");
    // Ensure unique ID for each choice element, sanitize title for ID
    newDiv.id = `${choicePrefix}-${item.title
      .replace(/\s/g, "-")
      .replace(/[^a-zA-Z0-9-]/g, "")}`;

    const newSpan = document.createElement("span");
    newDiv.appendChild(newSpan);

    // Image element - common to all
    const imgElement = document.createElement("img");
    imgElement.src =
      item.image || "https://placehold.co/100x100/eeeeee/ffffff?text=NoImage";
    imgElement.alt = `${item.title} image`;
    newSpan.appendChild(imgElement); // Image added after newSpan

    // Create an h3 element for the title
    const h3Element = document.createElement("h3");
    h3Element.style.marginTop = "0px";
    h3Element.style.marginBottom = "0px";
    h3Element.textContent = item.title || "No Title";
    newSpan.appendChild(h3Element);

    // Cost
    if (dataType === "archetype") {
      appendDropdown(newSpan, 5);

      const costP = document.createElement("p");
      costP.innerHTML = "Cost: ";
      newSpan.appendChild(costP);

      Object.keys(item.cost).forEach((key) => {
        let costPerCrew = document.createElement("p");
        costPerCrew.innerHTML = `${key}: ${formatterIntl.format(item.cost[key])}`;
        newSpan.appendChild(costPerCrew);
      });
    } else {
      const costP = document.createElement("p");
      costP.innerHTML = `Cost: ${formatterIntl.format(item.cost)}`;
      newSpan.appendChild(costP);
    }

    // Specialty
    if (item.specialty !== undefined) {
      const specialtyP = document.createElement("p");
      specialtyP.textContent = `Specialty: ${item.specialty}`;
      newSpan.appendChild(specialtyP);
    }

    if (item.equipment !== undefined) {
      const equipmentP = document.createElement("p");
      equipmentP.textContent = `Equipment: ${item.equipment}`;
      newSpan.appendChild(equipmentP);
    }
    // Skill Level
    if (item.skillLevel !== undefined) {
      const skillLevelP = document.createElement("p");
      skillLevelP.textContent = `Skill Level: ${item.skillLevel}`;
      newSpan.appendChild(skillLevelP);
    }

    // Alignment
    if (item.alignment !== undefined) {
      const alignmentP = document.createElement("p");
      alignmentP.textContent = `Alignment: ${item.alignment}`;
      newSpan.appendChild(alignmentP);
    }

    // Description
    if (item.description !== undefined) {
      const descriptionP = document.createElement("p");
      descriptionP.textContent = `Description: ${item.description}`;
      newSpan.appendChild(descriptionP);
    }

    targetSection.before(newDiv); // Append to the target section
  });
}
