// This array contains all equipment objects with their attributes.
// Blank attributes are set to '0'.
// Costs are converted to numerical values (k = thousand, m = million).
export const equipment = [ //change to weapons later
  {
    name: ".362 Snub Lawmaker",
    type: "Kinetic",
    cost: 50000,
    equipmentLevel: 1,
    stoppingPower: 5,
    piercingPower: 2,
    rateOfFire: 3,
    range: 3,
    accuracy: 2,
    handling: 10,
    roundCapacity: 7,
    action: "Revolver",
    calibre: ".362 LCat",
    
    description: "A snub-nosed revolver, perfect for concealment while still being able to pack a punch."
  },
  {
    name: "KML Compact",
    type: "Kinetic",
    cost: 50000,
    equipmentLevel: 1,
    stoppingPower: 3,
    piercingPower: 2,
    rateOfFire: 5,
    range: 3,
    accuracy: 3,
    handling: 10,
    roundCapacity: 12,
    action: "Semi-auto",
    calibre: "8.8mm PIL",
    
    description: "Extremely popular for concealed carry. Perfect for those who don't want to attract attention."
  },
  {
    name: "Forcify MK VII",
    type: "Plasma",
    cost: 100000,
    equipmentLevel: 1,
    stoppingPower: 5,
    piercingPower: 1,
    rateOfFire: 5,
    range: 3,
    accuracy: 2,
    handling: 10,
    roundCapacity: 0,
    action: "Semi-auto",
    calibre: "980nm",
    
    description: "A compact plasma gun. Energy guns need no reload, but overheat, and need regular battery changes."
  },
  {
    name: "Bandit-12",
    type: "Kinetic",
    cost: 400000,
    equipmentLevel: 2,
    stoppingPower: 8,
    piercingPower: 6,
    rateOfFire: 2,
    range: 5,
    accuracy: 4,
    handling: 6,
    roundCapacity: 6,
    action: "Revolver",
    calibre: ".48 RE",
    
    description: "A favourite of bandits, this revolver can take off arms. Hold it well, as the recoil could take off your own."
  },
  {
    name: ".362 Deputy",
    type: "Kinetic",
    cost: 500000,
    equipmentLevel: 2,
    stoppingPower: 6,
    piercingPower: 7,
    rateOfFire: 2,
    range: 6,
    accuracy: 7,
    handling: 7,
    roundCapacity: 6,
    action: "Revolver",
    calibre: ".362 LCat",
    
    description: "These handguns bolster accuracy with a hard hitting calibre. Usually owned by badasses."
  },
  {
    name: "C 2911",
    type: "Kinetic",
    cost: 100000,
    equipmentLevel: 1,
    stoppingPower: 6,
    piercingPower: 4,
    rateOfFire: 5,
    range: 4,
    accuracy: 4,
    handling: 8,
    roundCapacity: 9,
    action: "Semi-auto",
    calibre: "11mm FR",
    
    description: "Been in use for a long time, but never discarded for its iconic rep. Still shoots bullets, so it kills."
  },
  {
    name: "FD17 Daybreak",
    type: "Kinetic",
    cost: 100000,
    equipmentLevel: 1,
    stoppingPower: 4,
    piercingPower: 5,
    rateOfFire: 5,
    range: 4,
    accuracy: 5,
    handling: 9,
    roundCapacity: 15,
    action: "Semi-auto",
    calibre: "8.8mm Pil",
    
    description: "A lightweight calibre in a double-stacked magazine is perfect for a well balanced handgun."
  },
  {
    name: "Sabre 6",
    type: "Plasma",
    cost: 150000,
    equipmentLevel: 1,
    stoppingPower: 7,
    piercingPower: 2,
    rateOfFire: 5,
    range: 3,
    accuracy: 2,
    handling: 9,
    roundCapacity: 0,
    action: "Semi-auto",
    calibre: "1025nm",
    
    description: "A popular plasma gun that hits hard. This model is known to have good heat sinks."
  },
  {
    name: "Pallach Or2",
    type: "Laser",
    cost: 200000,
    equipmentLevel: 2,
    stoppingPower: 1,
    piercingPower: 7,
    rateOfFire: 2,
    range: 6,
    accuracy: 10,
    handling: 8,
    roundCapacity: 0,
    action: "Full-auto",
    calibre: "405nm",
    
    description: "Shoots brief, high-powered pulses of laser, reaching temperatures hotter than the surface of a star."
  },
  {
    name: "H56",
    type: "Kinetic",
    cost: 200000,
    equipmentLevel: 2,
    stoppingPower: 3,
    piercingPower: 4,
    rateOfFire: 8,
    range: 3,
    accuracy: 3,
    handling: 9,
    roundCapacity: 24,
    action: "Full-auto",
    calibre: "8.8mm PIL",
    
    description: "A simple machine pistol with a high rate of fire. Its low calibre has low recoil."
  },
  {
    name: "FD9 Judge",
    type: "Kinetic",
    cost: 500000,
    equipmentLevel: 3,
    stoppingPower: 4,
    piercingPower: 5,
    rateOfFire: 7,
    range: 4,
    accuracy: 5,
    handling: 7,
    roundCapacity: 18,
    action: "Select-fire",
    calibre: "10mm INF",
    
    description: "Perfect in the hands of those who love versatility. Can select to be semi, full, or burst. Silenced."
  },
  {
    name: "Gretel MK III",
    type: "Rail",
    cost: 800000,
    equipmentLevel: 3,
    stoppingPower: 7,
    piercingPower: 9,
    rateOfFire: 1,
    range: 6,
    accuracy: 9,
    handling: 5,
    roundCapacity: 4,
    action: "Semi-auto",
    calibre: "22mm",
    
    description: "Essentially a portable rail-gun. Known to pierce through tank armour."
  },
  {
    name: "Kayta F5",
    type: "Kinetic",
    cost: 200000,
    equipmentLevel: 2,
    stoppingPower: 4,
    piercingPower: 4,
    rateOfFire: 8,
    range: 3,
    accuracy: 3,
    handling: 7,
    roundCapacity: 30,
    action: "Full-auto",
    calibre: "8.8mm PIL",
    
    description: "Mass produced and found virtually everywhere, this balanced SMG is universally loved for its simplicity."
  },
  {
    name: "Rinn-J",
    type: "Plasma",
    cost: 200000,
    equipmentLevel: 2,
    stoppingPower: 4,
    piercingPower: 1,
    rateOfFire: 9,
    range: 3,
    accuracy: 2,
    handling: 8,
    roundCapacity: 0,
    action: "Full-auto",
    calibre: "980nm",
    
    description: "If you want to rain hundreds of burning-hot plasma on your enemies, look no further."
  },
  {
    name: "Hellfang",
    type: "Laser",
    cost: 500000,
    equipmentLevel: 3,
    stoppingPower: 1,
    piercingPower: 7,
    rateOfFire: 6,
    range: 6,
    accuracy: 9,
    handling: 5,
    roundCapacity: 16,
    action: "Full-auto",
    calibre: "320nm",
    
    description: "Nothing is scarier than the rapid fire of deadly red laser pulses. Has the highest PTSD-inducing rate. Loved by spec-ops."
  },
  {
    name: "FD39 Echo",
    type: "Kinetic",
    cost: 550000,
    equipmentLevel: 3,
    stoppingPower: 5,
    piercingPower: 4,
    rateOfFire: 7,
    range: 4,
    accuracy: 4,
    handling: 6,
    roundCapacity: 28,
    action: "Full-auto",
    calibre: "10mm INF",
    
    description: "Very wieldly with all of the aspects of an SMG perfected to a tee."
  },
  {
    name: "LK Banshee",
    type: "Plasma",
    cost: 700000,
    equipmentLevel: 3,
    stoppingPower: 6,
    piercingPower: 2,
    rateOfFire: 6,
    range: 4,
    accuracy: 3,
    handling: 5,
    roundCapacity: 16,
    action: "Full-auto/chg",
    calibre: "1025nm",
    
    description: "You can either go full-auto with torrents of hot plasma, or charged burst shots for more destruction."
  },
  {
    name: "H \"Frill\"",
    type: "Special",
    cost: 800000,
    equipmentLevel: 3,
    stoppingPower: 5,
    piercingPower: 3,
    rateOfFire: 8,
    range: 4,
    accuracy: 3,
    handling: 5,
    roundCapacity: 0,
    action: "Full-auto",
    calibre: "Unknown",
    
    description: "Experimental reverse-engineered tech from the Heralds. Rapidly shoots volatile mana bolts."
  },
  {
    name: "Spatha 2100FP",
    type: "Kinetic",
    cost: 100000,
    equipmentLevel: 3,
    stoppingPower: 9,
    piercingPower: 5,
    rateOfFire: 2,
    range: 4,
    accuracy: 3,
    handling: 6,
    roundCapacity: 9,
    action: "Pump",
    calibre: "10ga",
    
    description: "A reliable pump-action that's used in virtually every security and military doctrine."
  },
  {
    name: "Espingarda Model 80",
    type: "Kinetic",
    cost: 150000,
    equipmentLevel: 3,
    stoppingPower: 7,
    piercingPower: 5,
    rateOfFire: 4,
    range: 4,
    accuracy: 3,
    handling: 7,
    roundCapacity: 8,
    action: "Semi-auto",
    calibre: "12ga",
    
    description: "One of the best weapons for storming and taking out hostiles in tight spaces, like ship interiors."
  },
  {
    name: "Starburst MK VI",
    type: "Laser",
    cost: 200000,
    equipmentLevel: 3,
    stoppingPower: 1,
    piercingPower: 8,
    rateOfFire: 4,
    range: 5,
    accuracy: 9,
    handling: 5,
    roundCapacity: 0,
    action: "Semi-auto",
    calibre: "80nm x6",
    
    description: "A more experimental weapon that utilizes multiple diodes to burst out a 'fan' of high-powered lasers."
  },
  {
    name: "Ogoun M31",
    type: "Plasma",
    cost: 400000,
    equipmentLevel: 3,
    stoppingPower: 9,
    piercingPower: 3,
    rateOfFire: 5,
    range: 3,
    accuracy: 3,
    handling: 7,
    roundCapacity: 0,
    action: "Semi-auto",
    calibre: "4x675nm",
    
    description: "Delivers a face-full of piping hot plasma. One of the more cruel weapons out there."
  },
  {
    name: "AS-12/45",
    type: "Kinetic",
    cost: 400000,
    equipmentLevel: 3,
    stoppingPower: 7,
    piercingPower: 5,
    rateOfFire: 6,
    range: 3,
    accuracy: 2,
    handling: 5,
    roundCapacity: 8,
    action: "Full-auto",
    calibre: "12ga",
    
    description: "Not often used despite its full-auto capabilities, but a favourite for outer-rim bandits."
  },
  {
    name: "Wraithsong A4",
    type: "Rail",
    cost: 800000,
    equipmentLevel: 4,
    stoppingPower: 7,
    piercingPower: 8,
    rateOfFire: 2,
    range: 6,
    accuracy: 6,
    handling: 4,
    roundCapacity: 4,
    action: "Burst",
    calibre: "4mm x3",
    
    description: "Shoots an insanely fast burst of 3 high-velocity darts, which is known to make a ghostly whistling sound."
  },
  {
    name: "UN200-42",
    type: "Plasma",
    cost: 400000,
    equipmentLevel: 3,
    stoppingPower: 5,
    piercingPower: 1,
    rateOfFire: 7,
    range: 4,
    accuracy: 3,
    handling: 6,
    roundCapacity: 0,
    action: "Full-auto",
    calibre: "980nm",
    
    description: "A standard full-auto plasma gun... until you mark a target with the tag that the plasma orbs follow."
  },
  {
    name: "FD49 Reverb",
    type: "Kinetic",
    cost: 500000,
    equipmentLevel: 3,
    stoppingPower: 5,
    piercingPower: 4,
    rateOfFire: 7,
    range: 5,
    accuracy: 5,
    handling: 6,
    roundCapacity: 30,
    action: "Semi-auto",
    calibre: "5.91mm IN",
    
    description: "A very niche gun usually only found with bodyguards. Has an underslug ranged taser."
  },
  {
    name: "Angel",
    type: "Kinetic",
    cost: 700000,
    equipmentLevel: 4,
    stoppingPower: 5,
    piercingPower: 5,
    rateOfFire: 6,
    range: 5,
    accuracy: 6,
    handling: 5,
    roundCapacity: 28,
    action: "Select-fire",
    calibre: "6.4mm Ws",
    
    description: "The PDW improvement over the FD39 with a harder hitting and longer-ranged cartridge."
  },
  {
    name: "Devil's Kiss",
    type: "Plasma",
    cost: 1000000,
    equipmentLevel: 4,
    stoppingPower: 6,
    piercingPower: 3,
    rateOfFire: 6,
    range: 6,
    accuracy: 5,
    handling: 5,
    roundCapacity: 0,
    action: "Full-auto/alt",
    calibre: "995nm",
    
    description: "Unknown origin. Has a secondary firing mode that overheats more but shoots explosive plasma shots."
  },
  {
    name: "Bastard-21",
    type: "Kinetic",
    cost: 200000,
    equipmentLevel: 3,
    stoppingPower: 5,
    piercingPower: 5,
    rateOfFire: 7,
    range: 6,
    accuracy: 6,
    handling: 6,
    roundCapacity: 30,
    action: "Select-fire",
    calibre: "6.16mm UNI",
    
    description: "Extremely cheap and shoddy, but that's its charm. Usually only found in the outer rim systems."
  },
  {
    name: "The Ivan",
    type: "Kinetic",
    cost: 250000,
    equipmentLevel: 4,
    stoppingPower: 6,
    piercingPower: 5,
    rateOfFire: 6,
    range: 6,
    accuracy: 4,
    handling: 5,
    roundCapacity: 30,
    action: "Full-auto",
    calibre: "7.75mm SV",
    
    description: "A popular, cheap, and highly customizable assault rifle made in surplus for a war, long ago."
  },
  {
    name: "Sharktooth-T751",
    type: "Plasma",
    cost: 400000,
    equipmentLevel: 4,
    stoppingPower: 7,
    piercingPower: 3,
    rateOfFire: 6,
    range: 5,
    accuracy: 4,
    handling: 5,
    roundCapacity: 0,
    action: "Full-auto",
    calibre: "1155nm",
    
    description: "Looks cheaply put together, but is known to be one of the most well balanced plasma guns made."
  },
  {
    name: "FD22 Sprint",
    type: "Kinetic",
    cost: 450000,
    equipmentLevel: 4,
    stoppingPower: 6,
    piercingPower: 7,
    rateOfFire: 5,
    range: 7,
    accuracy: 8,
    handling: 5,
    roundCapacity: 22,
    action: "Semi-auto",
    calibre: "6.16mm UNI",
    
    description: "A lightweight scout rifle, perfect for precision shooting and general recon."
  },
  {
    name: "LK Scarlet",
    type: "Laser",
    cost: 650000,
    equipmentLevel: 4,
    stoppingPower: 2,
    piercingPower: 9,
    rateOfFire: 6,
    range: 7,
    accuracy: 10,
    handling: 4,
    roundCapacity: 0,
    action: "Semi-auto",
    calibre: "405nm",
    
    description: "A versatile and effective laser rifle for scouting and recon. Perfect against armoured personnel."
  },
  {
    name: "The EVI Platform",
    type: "Kinetic",
    cost: 700000,
    equipmentLevel: 4,
    stoppingPower: 5,
    piercingPower: 7,
    rateOfFire: 6,
    range: 6,
    accuracy: 7,
    handling: 5,
    roundCapacity: 32,
    action: "Select-fire",
    calibre: "6.16mm UNI",
    
    description: "A favourite for gun nuts, mainly due to the high availability of after market parts for customization."
  },
  {
    name: "H23",
    type: "Kinetic",
    cost: 800000,
    equipmentLevel: 4,
    stoppingPower: 6,
    piercingPower: 6,
    rateOfFire: 5,
    range: 7,
    accuracy: 7,
    handling: 4,
    roundCapacity: 28,
    action: "Select-fire",
    calibre: "6.8mm BH",
    
    description: "An elite bullpup with a unique, hard-hitting calibre. Some say it's the perfect assault rifle."
  },
  {
    name: "Gloom MK III",
    type: "Plasma/Laser",
    cost: 1000000,
    equipmentLevel: 4,
    stoppingPower: 5,
    piercingPower: 6,
    rateOfFire: 7,
    range: 6,
    accuracy: 6,
    handling: 4,
    roundCapacity: 0,
    action: "Select-fire",
    calibre: "995+440nm",
    
    description: "A plasma and laser gun put into one; plasma for full-auto punches and laser for semi-auto piercing."
  },
  {
    name: "H \"Mantis\"",
    type: "Special",
    cost: 1400000,
    equipmentLevel: 4,
    stoppingPower: 7,
    piercingPower: 5,
    rateOfFire: 5,
    range: 6,
    accuracy: 6,
    handling: 4,
    roundCapacity: 0,
    action: "Burst",
    calibre: "Unknown",
    
    description: "Experimental Herald tech. Shoots a quick burst of 3 mana bolts that uncharacteristically move quickly."
  },
  {
    name: "Burial M55",
    type: "Kinetic",
    cost: 700000,
    equipmentLevel: 4,
    stoppingPower: 9,
    piercingPower: 8,
    rateOfFire: 3,
    range: 9,
    accuracy: 8,
    handling: 4,
    roundCapacity: 12,
    action: "Semi-auto",
    calibre: "8.02mm TB",
    
    description: "Used in some of the most famous assassinations in history. High-powered and deadly accurate."
  },
  {
    name: "Atrophy",
    type: "Laser",
    cost: 1000000,
    equipmentLevel: 4,
    stoppingPower: 6,
    piercingPower: 10,
    rateOfFire: 2,
    range: 9,
    accuracy: 10,
    handling: 3,
    roundCapacity: 0,
    action: "Semi-auto",
    calibre: "625nm",
    
    description: "It is said that the victims don't even feel the pain, dropping dead as if it had come from nowhere..."
  },
  {
    name: "Orca A7",
    type: "Rail",
    cost: 1800000,
    equipmentLevel: 4,
    stoppingPower: 9,
    piercingPower: 9,
    rateOfFire: 2,
    range: 10,
    accuracy: 9,
    handling: 3,
    roundCapacity: 6,
    action: "Semi-auto",
    calibre: "28mm",
    
    description: "A skilled shooter with this weapon can become one of the deadliest people in the galaxy."
  },
  {
    name: "Hail-92",
    type: "Kinetic",
    cost: 650000,
    equipmentLevel: 4,
    stoppingPower: 5,
    piercingPower: 4,
    rateOfFire: 9,
    range: 6,
    accuracy: 5,
    handling: 2,
    roundCapacity: 200,
    action: "Full-auto",
    calibre: "6.16mm UNI",
    
    description: "A light machine gun that's often used by bandits. Uses two barrels to unleash a torrent of bullets."
  },
  {
    name: "FD7 Optimum",
    type: "Kinetic",
    cost: 900000,
    equipmentLevel: 5,
    stoppingPower: 7,
    piercingPower: 7,
    rateOfFire: 5,
    range: 6,
    accuracy: 6,
    handling: 2,
    roundCapacity: 80,
    action: "Full-auto",
    calibre: "8.02mm TB",
    
    description: "A medium machine gun that can punch holes in armour and is perfect for suppressive fire."
  },
  {
    name: "Salamander Or2",
    type: "Special",
    cost: 800000,
    equipmentLevel: 4,
    stoppingPower: 9,
    piercingPower: 1,
    rateOfFire: 10,
    range: 3,
    accuracy: 2,
    handling: 1,
    roundCapacity: 0,
    action: "Thrower",
    calibre: "n/a",
    
    description: "A flamethrower often employed by the Dustkeepers. Perfect for burning away biomass."
  },
  {
    name: "H \"Flare\"",
    type: "Special",
    cost: 1600000,
    equipmentLevel: 5,
    stoppingPower: 6,
    piercingPower: 5,
    rateOfFire: 10,
    range: 5,
    accuracy: 7,
    handling: 1,
    roundCapacity: 0,
    action: "Continuous",
    calibre: "Unknown",
    
    description: "Fires a deadly continuous beam of mana that intensifies the longer you hold it. Overheats quickly."
  },
  {
    name: "Ratio MK II",
    type: "Rail",
    cost: 2000000,
    equipmentLevel: 5,
    stoppingPower: 9,
    piercingPower: 10,
    rateOfFire: 2,
    range: 10,
    accuracy: 9,
    handling: 2,
    roundCapacity: 4,
    action: "Bolt-action",
    calibre: "42mm",
    
    description: "Accelerates particles at a very high speed, creating rays of super-charged, volatile particles. A magnetic anti-materiel weapon that uses coils instead of rails."
  },
  {
    name: "Sardonic 9",
    type: "Plasma",
    cost: 2200000,
    equipmentLevel: 5,
    stoppingPower: 10,
    piercingPower: 9,
    rateOfFire: 2,
    range: 10,
    accuracy: 10,
    handling: 4,
    roundCapacity: 0,
    action: "Semi-auto",
    calibre: "1990nm",
    
    description: "Unknown."
  },
  {
    name: "H12",
    type: "Explosive",
    cost: 500000,
    equipmentLevel: 4,
    stoppingPower: 6,
    piercingPower: 4,
    rateOfFire: 4,
    range: 3,
    accuracy: 3,
    handling: 2,
    roundCapacity: 1,
    action: "Launcher",
    calibre: "82mm",
    
    description: "Can launch any type of grenade. Used for destructive purposes as well as crowd control."
  },
  {
    name: "Stark-4",
    type: "Explosive",
    cost: 700000,
    equipmentLevel: 5,
    stoppingPower: 8,
    piercingPower: 7,
    rateOfFire: 1,
    range: 6,
    accuracy: 6,
    handling: 2,
    roundCapacity: 8,
    action: "Semi-auto",
    calibre: "28mm",
    
    description: "Cheap for a rocket launcher but effective at taking out heavy and expensive targets."
  },
  {
    name: "KM Swarm",
    type: "Explosive",
    cost: 1200000,
    equipmentLevel: 5,
    stoppingPower: 5,
    piercingPower: 6,
    rateOfFire: 6,
    range: 4,
    accuracy: 5,
    handling: 2,
    roundCapacity: 1,
    action: "Launcher",
    calibre: "110mm",
    
    description: "A launcher that's more focused for taking out personnel, rather than materiel."
  },
  {
    name: "FD102 Toler",
    type: "Explosive",
    cost: 2000000,
    equipmentLevel: 5,
    stoppingPower: 10,
    piercingPower: 7,
    rateOfFire: 1,
    range: 9,
    accuracy: 9,
    handling: 1,
    roundCapacity: 12,
    action: "Semi-auto",
    calibre: "40mm",
    
    description: "Locks onto targets and launches high-destructive missiles which seek them."
  },
  {
    name: "Explody Thing",
    type: "Explosive",
    cost: 2200000,
    equipmentLevel: 5,
    stoppingPower: 8,
    piercingPower: 6,
    rateOfFire: 4,
    range: 6,
    accuracy: 5,
    handling: 1,
    roundCapacity: 4,
    action: "Semi-auto",
    calibre: "82mm",
    
    description: "The weapon used by Sya'ra the Mad Roller to repel a small Black-hawk convoy during the Luos wars."
  },
  {
    name: "Moses Or19",
    type: "Laser/Plasma",
    cost: 3000000,
    equipmentLevel: 5,
    stoppingPower: 7,
    piercingPower: 10,
    rateOfFire: 2,
    range: 9,
    accuracy: 10,
    handling: 1,
    roundCapacity: 0,
    action: "Burst",
    calibre: "720nm x4",
    
    description: "A specialized heavy laser gun that fires volatile ion particles, causing explosions."
  },
  {
    name: "Hel",
    type: "Special",
    cost: 4000000,
    equipmentLevel: 6,
    stoppingPower: 10,
    piercingPower: 9,
    rateOfFire: 10,
    range: 6,
    accuracy: 5,
    handling: 0,
    roundCapacity: 0,
    action: "Thrower",
    calibre: "n/a",
    
    description: "Spews a burning chemical liquid solution that can instantaneously melt through rock."
  },
  {
    name: "FD99x Perfection",
    type: "Kinetic",
    cost: 6000000,
    equipmentLevel: 7,
    stoppingPower: 10,
    piercingPower: 9,
    rateOfFire: 10,
    range: 9,
    accuracy: 8,
    handling: 0,
    roundCapacity: 1000,
    action: "Gatling",
    calibre: "45mm Qn",
    
    description: "Usually mounted on vehicles, this monster's roar can be heard from many kilometers away."
  }
];

export const vehicles = [
  {
    name: "AT Dunebuggy",
    cost: 500000,
    hangarSpaceUse: 1,
    crew: 4,
    T1WeaponSlots: 2,
    T2WeaponSlots: 0,
    Mobility: "000000000",
    Armour: "8m",
    Length: "4m",
    Description: "The all-terrain dunebuggy allows for great ground coverage. Its high-traction wheels can be replaced with skates or skiis. +Comes with a free machine gun"
  },
  {
    name: "MLUV",
    cost: 1000000,
    hangarSpaceUse: 1,
    crew: 6,
    T1WeaponSlots: 2,
    T2WeaponSlots: 0,
    Mobility: "D0000",
    Armour: "E", // Assuming 'E' is a string value for Armour
    Length: "4m",
    Description: "This mlitary light utility vehicle has a good balance of mobility, armour, and firepower, perfect for troop transportation and support. +Comes with a free T1 weapon"
  },
  {
    name: "APC",
    cost: 2000000,
    hangarSpaceUse: 2,
    crew: 12,
    T1WeaponSlots: 2,
    T2WeaponSlots: 0,
    Mobility: "D0000",
    Armour: "4m",
    Length: "6m",
    Description: "Large and bulky, these Armoured Personnel Carriers can transport a good handful of troops or VIPs and protect them with thick armour. +Comes with a free T1 weapon"
  },
  {
    name: "Terrain Tank",
    cost: 3000000,
    hangarSpaceUse: 2,
    crew: 5,
    T1WeaponSlots: 2,
    T2WeaponSlots: 1,
    Mobility: "", // Mobility value was blank in source for this item
    Armour: "6m",
    Length: "6m",
    Description: "These tanks are light armoured, but with their special quarduped tank treads, they can cover many kinds of terrain with good speed. +Comes with a free T2 weapon"
  },
  {
    name: "Heavy Tank",
    cost: 4000000,
    hangarSpaceUse: 2,
    crew: 6,
    T1WeaponSlots: 4,
    T2WeaponSlots: 1,
    Mobility: "", // Mobility value was blank in source for this item
    Armour: "8m",
    Length: "11m",
    Description: "Fit for convoys, heavy firepower, artillery support, and everything tank-like, these beasts can lead the charge into combat. +Comes with a free T2 weapon"
  },
  {
    name: "Spider Tank",
    cost: 6000000,
    hangarSpaceUse: 2,
    crew: 4,
    T1WeaponSlots: 3,
    T2WeaponSlots: 1,
    Mobility: "", // Mobility value was blank in source for this item
    Armour: "5m",
    Length: "9m",
    Description: "Spider tanks are a more experi- mental platform, but unlike tradi- tional tanks, they have less trouble overcoming terrain. +Comes with a free T2 weapon"
  },
  {
    name: "Ground Mech",
    cost: 1000000,
    hangarSpaceUse: 1,
    crew: 1,
    T1WeaponSlots: 2,
    T2WeaponSlots: 0,
    Mobility: "0000000",
    Armour: "5m",
    Length: "5m",
    Description: "This personal ground mech has ample firepower with versatile movement. The perfect firepower support platform for your troops. +Comes with a free T1 weapon"
  },
  {
    name: "Heavy Ground Mech",
    cost: 4000000,
    hangarSpaceUse: 2,
    crew: 2,
    T1WeaponSlots: 3,
    T2WeaponSlots: 1,
    Mobility: "000000SS",
    Armour: "8m",
    Length: "8m",
    Description: "These mechs are equipped with extremely hard hitting ordnance, particularily against air targets and other vehicles. +Comes with a free T2 weapon"
  },
  {
    name: "OG Mobile Suit",
    cost: 7000000,
    hangarSpaceUse: 2,
    crew: 8,
    T1WeaponSlots: 1,
    T2WeaponSlots: 0,
    Mobility: "0000000",
    Armour: "10m",
    Length: "10m",
    Description: "Single-piloted, but extremely versatile. An upgrade from your standard power armour, these can fly in atmosphere or space. +Comes with a free T2 weapon"
  },
  {
    name: "Submarine",
    cost: 3000000,
    hangarSpaceUse: 3,
    crew: 12,
    T1WeaponSlots: 1,
    T2WeaponSlots: 0,
    Mobility: "0000000000",
    Armour: "25m",
    Length: "25m",
    Description: "These submarines can withstand extreme temperatures and pres- sures, and can withstand many liquids. +Comes with a free T1 weapon"
  },
  {
    name: "Lamprey Boarding Ship",
    cost: 5000000,
    hangarSpaceUse: 4,
    crew: 12,
    T1WeaponSlots: 2,
    T2WeaponSlots: 0,
    Mobility: "000000SS",
    Armour: "12m",
    Length: "12m",
    Description: "This ship uses high-powered lasers to cut through hulls to allow its boarding party inside. However, it cannot fly through ship shields. +Has 2 hangar space capacity"
  },
  {
    name: "Drop Ship",
    cost: 5000000,
    hangarSpaceUse: 2,
    crew: 12,
    T1WeaponSlots: 3,
    T2WeaponSlots: 0,
    Mobility: "0000000",
    Armour: "15m",
    Length: "15m",
    Description: "Heavily armoured and perfectly capable of transporting troops and vehicles. +Comes with a free T1 weapon +Has 3 hangar space capacity"
  }
];
