// This array contains all equipment objects with their attributes.
// Blank attributes are set to '0'.
// Costs are converted to numerical values (k = thousand, m = million).
export const equipment = [ //change to weapons later
  {
    name: ".362 Deputy",
    type: "Kinetic",
    cost: 500000,
    equipmentLevel: 2,
    kineticDefence: 0,
    energyDefence: 0,
    mobility: 0,
    stoppingPower: 0,
    piercingPower: 0,
    rateOfFire: 0,
    range: 0,
    accuracy: 0,
    handling: 0,
    roundCapacity: 0,
    action: "Revolver",
    calibre: "362 LCat"
  },
  {
    name: ".362 Snub Lawmaker",
    type: "Kinetic",
    cost: 50000,
    equipmentLevel: 1,
    kineticDefence: 0,
    energyDefence: 0,
    mobility: 0,
    stoppingPower: 0,
    piercingPower: 0,
    rateOfFire: 0,
    range: 0,
    accuracy: 0,
    handling: 0,
    roundCapacity: "7",
    action: "Revolver",
    calibre: ".362 LCat"
  },
  {
    name: "AS-12/45",
    type: "Kinetic",
    cost: 400000,
    equipmentLevel: 3,
    kineticDefence: 0,
    energyDefence: 0,
    mobility: 0,
    stoppingPower: 0,
    piercingPower: 0,
    rateOfFire: 0,
    range: 0,
    accuracy: 0,
    handling: 0,
    roundCapacity: 4,
    action: "Burst",
    calibre: "12ga"
  },
  {
    name: "Angel",
    type: "Kinetic",
    cost: 700000,
    equipmentLevel: 4,
    kineticDefence: 0,
    energyDefence: 0,
    mobility: 0,
    stoppingPower: 0,
    piercingPower: 0,
    rateOfFire: 0,
    range: 0,
    accuracy: 0,
    handling: 0,
    roundCapacity: 28,
    action: "Select-fire",
    calibre: "6.4mm Ws"
  },
  {
    name: "Atrophy",
    type: "Plasma",
    cost: 1400000,
    equipmentLevel: 4,
    kineticDefence: 0,
    energyDefence: 0,
    mobility: 0,
    stoppingPower: 0,
    piercingPower: 0,
    rateOfFire: 0,
    range: 0,
    accuracy: 0,
    handling: 0,
    roundCapacity: "~8",
    action: "Semi-auto",
    diode: "625nm"
  },
  {
    name: "Bandit-12",
    type: "Kinetic",
    cost: 400000,
    equipmentLevel: 2,
    kineticDefence: 0,
    energyDefence: 0,
    mobility: 0,
    stoppingPower: 0,
    piercingPower: 0,
    rateOfFire: 0,
    range: 0,
    accuracy: 0,
    handling: 0,
    roundCapacity: 6,
    action: "Revolver",
    calibre: ".48 RE"
  },
  {
    name: "Bastard-21",
    type: "Kinetic",
    cost: 200000,
    equipmentLevel: 3,
    kineticDefence: 0,
    energyDefence: 0,
    mobility: 0,
    stoppingPower: 0,
    piercingPower: 0,
    rateOfFire: 0,
    range: 0,
    accuracy: 0,
    handling: 0,
    roundCapacity: 30,
    action: "Select-fire",
    calibre: "6.16mm UNI"
  },
  {
    name: "Breacher",
    type: "Grenade",
    cost: 700000,
    equipmentLevel: 2,
    kineticDefence: 0,
    energyDefence: 0,
    mobility: 0,
    stoppingPower: 0,
    piercingPower: 0,
    rateOfFire: 0,
    range: 0,
    handling: "00000888SS"
  },
  {
    name: "Bulletproof Vest",
    type: "Armour",
    cost: 50000,
    equipmentLevel: 2,
    kineticDefence: "00000082SS",
    energyDefence: 0,
    mobility: 0,
    stoppingPower: 0,
    piercingPower: 0,
    rateOfFire: 0,
    range: 0
  },
  {
    name: "Burial M55",
    type: "Kinetic",
    cost: 700000,
    equipmentLevel: 4,
    kineticDefence: 0,
    energyDefence: 0,
    mobility: 0,
    stoppingPower: 0,
    piercingPower: 0,
    rateOfFire: 0,
    range: 0,
    accuracy: 0,
    handling: 0,
    roundCapacity: 12,
    action: "Semi-auto",
    calibre: "8.02mm TB"
  },
  {
    name: "C 2911",
    type: "Kinetic",
    cost: 100000,
    equipmentLevel: 1,
    kineticDefence: 0,
    energyDefence: 0,
    mobility: 0,
    stoppingPower: 0,
    piercingPower: 0,
    rateOfFire: 0,
    range: 0,
    accuracy: 0,
    handling: 0,
    roundCapacity: "9",
    action: "Semi-auto",
    calibre: "11mm FR"
  },
  {
    name: "Clothing",
    type: "Armour",
    cost: 0,
    equipmentLevel: 0,
    kineticDefence: "0000000",
    energyDefence: "0000000",
    mobility: "0000000",
    stoppingPower: 0,
    piercingPower: 0,
    rateOfFire: 0,
    range: 0
  },
  {
    name: "Combat Knife",
    type: "Melee",
    cost: 50000,
    equipmentLevel: 1,
    kineticDefence: 0,
    energyDefence: 0,
    mobility: 0,
    stoppingPower: 0,
    piercingPower: 0,
    rateOfFire: 0,
    range: 0,
    handling: "0000000000"
  },
  {
    name: "Crown Mk3",
    type: "Armour",
    cost: 4000000,
    equipmentLevel: 7,
    kineticDefence: 0,
    energyDefence: 0,
    mobility: 0,
    stoppingPower: 0,
    piercingPower: 0,
    rateOfFire: 0,
    range: 0
  },
  {
    name: "Devil's Kiss",
    type: "Plasma",
    cost: 1000000,
    equipmentLevel: 4,
    kineticDefence: 0,
    energyDefence: 0,
    mobility: 0,
    stoppingPower: 0,
    piercingPower: 0,
    rateOfFire: 0,
    range: 0,
    accuracy: 0,
    handling: 0,
    roundCapacity: 0,
    action: "Full-auto/alt",
    diode: "995nm?"
  },
  {
    name: "EMP",
    type: "Grenade",
    cost: 300000,
    equipmentLevel: 1,
    kineticDefence: 0,
    energyDefence: 0,
    mobility: 0,
    stoppingPower: 0,
    piercingPower: 0,
    rateOfFire: 0,
    range: 0,
    handling: 0
  },
  {
    name: "Energy Sword",
    type: "Melee",
    cost: 900000,
    equipmentLevel: 3,
    kineticDefence: 0,
    energyDefence: 0,
    mobility: 0,
    stoppingPower: 0,
    piercingPower: 0,
    rateOfFire: 0,
    range: 0,
    handling: "DO000000"
  },
  {
    name: "Erinyes",
    type: "Armour",
    cost: 3000000,
    equipmentLevel: 7,
    kineticDefence: 0,
    energyDefence: 0,
    mobility: 0,
    stoppingPower: 0,
    piercingPower: 0,
    rateOfFire: 0,
    range: 0
  },
  {
    name: "Espingarda Model 80",
    type: "Kinetic",
    cost: 150000,
    equipmentLevel: 3,
    kineticDefence: 0,
    energyDefence: 0,
    mobility: 0,
    stoppingPower: 0,
    piercingPower: 0,
    rateOfFire: 0,
    range: 0,
    accuracy: 0,
    handling: 0,
    roundCapacity: 12,
    action: "Semi-auto",
    calibre: "12ga"
  },
  {
    name: "Exo-Skeleton",
    type: "Armour",
    cost: 700000,
    equipmentLevel: 5,
    kineticDefence: "000000000",
    energyDefence: 0,
    mobility: 0,
    stoppingPower: 0,
    piercingPower: 0,
    rateOfFire: 0,
    range: 0
  },
  {
    name: "Explody Thing",
    type: "Explosive",
    cost: 2200000,
    equipmentLevel: 5,
    kineticDefence: 0,
    energyDefence: 0,
    mobility: 0,
    stoppingPower: 0,
    piercingPower: 0,
    rateOfFire: 0,
    range: 0,
    accuracy: 0,
    handling: 0,
    roundCapacity: 4,
    action: "Semi-auto",
    ordnance: "82mm"
  },
  {
    name: "Explosive Charge",
    type: "Melee",
    cost: 800000,
    equipmentLevel: 2,
    kineticDefence: 0,
    energyDefence: 0,
    mobility: 0,
    stoppingPower: 0,
    piercingPower: 0,
    rateOfFire: 0,
    range: 0,
    handling: "DDDD0000"
  },
  {
    name: "FD102 Toler",
    type: "Explosive",
    cost: 2000000,
    equipmentLevel: 5,
    kineticDefence: 0,
    energyDefence: 0,
    mobility: 0,
    stoppingPower: 0,
    piercingPower: 0,
    rateOfFire: 0,
    range: 0,
    accuracy: 0,
    handling: 0,
    roundCapacity: 1,
    action: "Launcher",
    ordnance: "110mm"
  },
  {
    name: "FD17 Daybreak",
    type: "Kinetic",
    cost: 100000,
    equipmentLevel: 1,
    kineticDefence: 0,
    energyDefence: 0,
    mobility: 0,
    stoppingPower: 0,
    piercingPower: 0,
    rateOfFire: 0,
    range: 0,
    accuracy: 0,
    handling: 0,
    roundCapacity: 15,
    action: "Semi-auto",
    calibre: "8.8mm Pil"
  },
  {
    name: "FD22 Sprint",
    type: "Kinetic",
    cost: 450000,
    equipmentLevel: 4,
    kineticDefence: 0,
    energyDefence: 0,
    mobility: 0,
    stoppingPower: 0,
    piercingPower: 0,
    rateOfFire: 0,
    range: 0,
    accuracy: 0,
    handling: 0,
    roundCapacity: "~20",
    action: "Semi-auto",
    calibre: "6.16mm UNI"
  },
  {
    name: "FD39 Echo",
    type: "Kinetic",
    cost: 550000,
    equipmentLevel: 3,
    kineticDefence: 0,
    energyDefence: 0,
    mobility: 0,
    stoppingPower: 0,
    piercingPower: 0,
    rateOfFire: 0,
    range: 0,
    accuracy: 0,
    handling: 0,
    roundCapacity: 28,
    action: "Full-auto",
    calibre: "10mm INF"
  },
  {
    name: "FD49 Reverb",
    type: "Kinetic",
    cost: 500000,
    equipmentLevel: 3,
    kineticDefence: 0,
    energyDefence: 0,
    mobility: 0,
    stoppingPower: 0,
    piercingPower: 0,
    rateOfFire: 0,
    range: 0,
    accuracy: 0,
    handling: 0,
    roundCapacity: 28,
    action: "Semi-auto",
    calibre: "5.91mm IN"
  },
  {
    name: "FD7 Optimum",
    type: "Kinetic",
    cost: 900000,
    equipmentLevel: 5,
    kineticDefence: 0,
    energyDefence: 0,
    mobility: 0,
    stoppingPower: 0,
    piercingPower: 0,
    rateOfFire: 0,
    range: 0,
    accuracy: 0,
    handling: 0,
    roundCapacity: "80",
    action: "Full-auto",
    calibre: "7.75mm SV"
  },
  {
    name: "FD9 Judge",
    type: "Kinetic",
    cost: 500000,
    equipmentLevel: 3,
    kineticDefence: 0,
    energyDefence: 0,
    mobility: 0,
    stoppingPower: 0,
    piercingPower: 0,
    rateOfFire: 0,
    range: 0,
    accuracy: 0,
    handling: 0,
    roundCapacity: 18,
    action: "Select-fire",
    calibre: "10mm INF"
  },
  {
    name: "FD99x Perfection",
    type: "Kinetic",
    cost: 6000000,
    equipmentLevel: 7,
    kineticDefence: 0,
    energyDefence: 0,
    mobility: 0,
    stoppingPower: 0,
    piercingPower: 0,
    rateOfFire: 0,
    range: 0,
    accuracy: 0,
    handling: 0,
    roundCapacity: "1000+",
    action: "Gatling",
    calibre: "45mm Qn"
  },
  {
    name: "Flashbang",
    type: "Grenade",
    cost: 200000,
    equipmentLevel: 1,
    kineticDefence: 0,
    energyDefence: 0,
    mobility: 0,
    stoppingPower: 0,
    piercingPower: 0,
    rateOfFire: 0,
    range: 0,
    handling: 0
  },
  {
    name: "Forcify MK VII",
    type: "Plasma",
    cost: 100000,
    equipmentLevel: 1,
    kineticDefence: 0,
    energyDefence: 0,
    mobility: 0,
    stoppingPower: 0,
    piercingPower: 0,
    rateOfFire: 0,
    range: 0,
    accuracy: 0,
    handling: 0,
    roundCapacity: "-16",
    action: "Semi-auto",
    diode: "980nm"
  },
  {
    name: "Fragmentation",
    type: "Grenade",
    cost: 50000,
    equipmentLevel: 1,
    kineticDefence: 0,
    energyDefence: 0,
    mobility: 0,
    stoppingPower: 0,
    piercingPower: 0,
    rateOfFire: 0,
    range: 0,
    handling: 0
  },
  {
    name: "Full-Body Tactical",
    type: "Armour",
    cost: 150000,
    equipmentLevel: 3,
    kineticDefence: 0,
    energyDefence: 0,
    mobility: 0,
    stoppingPower: 0,
    piercingPower: 0,
    rateOfFire: 0,
    range: 0
  },
  {
    name: "Gloom MK III",
    type: "Plasma/Laser",
    cost: 1000000,
    equipmentLevel: 4,
    kineticDefence: 0,
    energyDefence: 0,
    mobility: 0,
    stoppingPower: 0,
    piercingPower: 0,
    rateOfFire: 0,
    range: 0,
    accuracy: 0,
    handling: 0,
    roundCapacity: "~32",
    action: "Select-fire",
    diode: "995+440nm"
  },
  {
    name: "Grapple Mod",
    type: "Grenade",
    cost: 250000,
    equipmentLevel: 1,
    kineticDefence: 0,
    energyDefence: 0,
    mobility: 0,
    stoppingPower: 0,
    piercingPower: 0,
    rateOfFire: 0,
    range: 0,
    handling: 0
  },
  {
    name: "Gretel MK III",
    type: "Rail",
    cost: 800000,
    equipmentLevel: 3,
    kineticDefence: 0,
    energyDefence: 0,
    mobility: 0,
    stoppingPower: 0,
    piercingPower: 0,
    rateOfFire: 0,
    range: 0,
    accuracy: 0,
    handling: 0,
    roundCapacity: 4,
    action: "Semi-auto",
    bolt: "22mm"
  },
  {
    name: "H \"Flare\"",
    type: "Special",
    cost: 1600000,
    equipmentLevel: 5,
    kineticDefence: 0,
    energyDefence: 0,
    mobility: 0,
    stoppingPower: 0,
    piercingPower: 0,
    rateOfFire: 0,
    range: 0,
    accuracy: 0,
    handling: 0,
    roundCapacity: "~350",
    action: "Continuous",
    diode: "Unknown"
  },
  {
    name: "H \"Frill\"",
    type: "Special",
    cost: 800000,
    equipmentLevel: 3,
    kineticDefence: 0,
    energyDefence: 0,
    mobility: 0,
    stoppingPower: 0,
    piercingPower: 0,
    rateOfFire: 0,
    range: 0,
    accuracy: 0,
    handling: 0,
    roundCapacity: "~50",
    action: "Full-auto",
    diode: "Unknown"
  },
  {
    name: "H \"Grasps\"",
    type: "Special",
    cost: 4000000,
    equipmentLevel: 5,
    kineticDefence: 0,
    energyDefence: 0,
    mobility: 0,
    stoppingPower: 0,
    piercingPower: 0,
    rateOfFire: 0,
    range: 0,
    accuracy: 0,
    handling: "EEEEEEE.."
  },
  {
    name: "H \"Mantis\"",
    type: "Special",
    cost: 1000000,
    equipmentLevel: 4,
    kineticDefence: 0,
    energyDefence: 0,
    mobility: 0,
    stoppingPower: 0,
    piercingPower: 0,
    rateOfFire: 0,
    range: 0,
    accuracy: 0,
    handling: 0,
    roundCapacity: 0,
    action: "Burst",
    diode: "Unknown"
  },
  {
    name: "H12",
    type: "Explosive",
    cost: 500000,
    equipmentLevel: 4,
    kineticDefence: 0,
    energyDefence: 0,
    mobility: 0,
    stoppingPower: 0,
    piercingPower: 0,
    rateOfFire: 0,
    range: 0,
    accuracy: 0,
    handling: 0,
    roundCapacity: 12,
    action: "Semi-auto",
    bolt: "40mm"
  },
  {
    name: "H23",
    type: "Kinetic",
    cost: 800000,
    equipmentLevel: 4,
    kineticDefence: 0,
    energyDefence: 0,
    mobility: 0,
    stoppingPower: 0,
    piercingPower: 0,
    rateOfFire: 0,
    range: 0,
    accuracy: 0,
    handling: 0,
    roundCapacity: 28,
    action: "Select-fire",
    calibre: "6.8mm BH"
  },
  {
    name: "H56",
    type: "Kinetic",
    cost: 200000,
    equipmentLevel: 2,
    kineticDefence: 0,
    energyDefence: 0,
    mobility: 0,
    stoppingPower: 0,
    piercingPower: 0,
    rateOfFire: 0,
    range: 0,
    accuracy: 0,
    handling: 0,
    roundCapacity: 24,
    action: "Full-auto",
    calibre: "8.8mm PIL"
  },
  {
    name: "Hail-92",
    type: "Kinetic",
    cost: 650000,
    equipmentLevel: 4,
    kineticDefence: 0,
    energyDefence: 0,
    mobility: 0,
    stoppingPower: 0,
    piercingPower: 0,
    rateOfFire: 0,
    range: 0,
    accuracy: "~60",
    handling: 0,
    roundCapacity: 200,
    action: "Full-auto",
    calibre: "6.16mm UNI"
  },
  {
    name: "Hel",
    type: "Special",
    cost: 4000000,
    equipmentLevel: 6,
    kineticDefence: 0,
    energyDefence: 0,
    mobility: 0,
    stoppingPower: 0,
    piercingPower: 0,
    rateOfFire: 0,
    range: 0,
    accuracy: 0,
    handling: 0,
    roundCapacity: 0,
    action: "Thrower",
    calibre: "n/a"
  },
  {
    name: "Hellfang",
    type: "Laser",
    cost: 500000,
    equipmentLevel: 3,
    kineticDefence: 0,
    energyDefence: 0,
    mobility: 0,
    stoppingPower: 0,
    piercingPower: 0,
    rateOfFire: 0,
    range: 0,
    accuracy: 0,
    handling: 0,
    roundCapacity: "16",
    action: "Full-auto",
    diode: "320nm"
  },
  {
    name: "Hellhound",
    type: "Armour",
    cost: 5500000,
    equipmentLevel: 8,
    kineticDefence: "00000000SS",
    energyDefence: 0,
    mobility: 0,
    stoppingPower: 0,
    piercingPower: 0,
    rateOfFire: 0,
    range: 0
  },
  {
    name: "Hi-Ex",
    type: "Grenade",
    cost: 100000,
    equipmentLevel: 1,
    kineticDefence: 0,
    energyDefence: 0,
    mobility: 0,
    stoppingPower: 0,
    piercingPower: 0,
    rateOfFire: 0,
    range: 0,
    handling: 0
  },
  {
    name: "Hydra Vest",
    type: "Armour",
    cost: 350000,
    equipmentLevel: 4,
    kineticDefence: "0000 000SS",
    energyDefence: 0,
    mobility: 0,
    stoppingPower: 0,
    piercingPower: 0,
    rateOfFire: 0,
    range: 0
  },
  {
    name: "Incendiary",
    type: "Grenade",
    cost: 200000,
    equipmentLevel: 1,
    kineticDefence: 0,
    energyDefence: 0,
    mobility: 0,
    stoppingPower: 0,
    piercingPower: 0,
    rateOfFire: 0,
    range: 0,
    handling: 0
  },
  {
    name: "Infiltrator",
    type: "Armour",
    cost: 300000,
    equipmentLevel: 4,
    kineticDefence: "00000000",
    energyDefence: 0,
    mobility: 0,
    stoppingPower: 0,
    piercingPower: 0,
    rateOfFire: 0,
    range: 0
  },
  {
    name: "Infantry",
    type: "Armour",
    cost: 600000,
    equipmentLevel: 5,
    kineticDefence: "00000...",
    energyDefence: 0,
    mobility: 0,
    stoppingPower: 0,
    piercingPower: 0,
    rateOfFire: 0,
    range: 0
  },
  {
    name: "Kayta F5",
    type: "Kinetic",
    cost: 200000,
    equipmentLevel: 2,
    kineticDefence: 0,
    energyDefence: 0,
    mobility: 0,
    stoppingPower: 0,
    piercingPower: 0,
    rateOfFire: 0,
    range: 0,
    accuracy: 0,
    handling: 0,
    roundCapacity: 30,
    action: "Full-auto",
    calibre: "8.8mm PIL"
  },
  {
    name: "KM Swarm",
    type: "Explosive",
    cost: 1200000,
    equipmentLevel: 5,
    kineticDefence: 0,
    energyDefence: 0,
    mobility: 0,
    stoppingPower: 0,
    piercingPower: 0,
    rateOfFire: 0,
    range: 0,
    accuracy: 0,
    handling: 0,
    roundCapacity: "8",
    action: "Semi-auto",
    ordnance: "28mm"
  },
  {
    name: "KML Compact",
    type: "Kinetic",
    cost: 50000,
    equipmentLevel: 1,
    kineticDefence: 0,
    energyDefence: 0,
    mobility: 0,
    stoppingPower: 0,
    piercingPower: 0,
    rateOfFire: 0,
    range: 0,
    accuracy: 0,
    handling: 0,
    roundCapacity: 12,
    action: "Semi-auto",
    calibre: "8.8mm PIL"
  },
  {
    name: "LK Banshee",
    type: "Plasma",
    cost: 700000,
    equipmentLevel: 3,
    kineticDefence: 0,
    energyDefence: "00000ES",
    mobility: 0,
    stoppingPower: 0,
    piercingPower: 0,
    rateOfFire: 0,
    range: 0,
    accuracy: 0,
    handling: 0,
    roundCapacity: "~16",
    action: "Full-auto/chg",
    diode: "1025nm"
  },
  {
    name: "LK Scarlet",
    type: "Laser",
    cost: 650000,
    equipmentLevel: 4,
    kineticDefence: 0,
    energyDefence: 0,
    mobility: 0,
    stoppingPower: 0,
    piercingPower: 0,
    rateOfFire: 0,
    range: 0,
    accuracy: 0,
    handling: 0,
    roundCapacity: 32,
    action: "Semi-auto",
    diode: "405nm"
  },
  {
    name: "Medium Melee Weapon",
    type: "Melee",
    cost: 100000,
    equipmentLevel: 1,
    kineticDefence: 0,
    energyDefence: 0,
    mobility: 0,
    stoppingPower: 0,
    piercingPower: 0,
    rateOfFire: 0,
    range: 0,
    handling: "Buuuuu"
  },
  {
    name: "Moses Or19",
    type: "Laser/Plasma",
    cost: 3000000,
    equipmentLevel: 5,
    kineticDefence: 0,
    energyDefence: 0,
    mobility: 0,
    stoppingPower: 0,
    piercingPower: 0,
    rateOfFire: 0,
    range: 0,
    accuracy: 0,
    handling: 0,
    roundCapacity: "-3",
    action: "Burst",
    diode: "720nm x4"
  },
  {
    name: "Nano Suit",
    type: "Armour",
    cost: 2500000,
    equipmentLevel: 7,
    kineticDefence: 0,
    energyDefence: 0,
    mobility: 0,
    stoppingPower: 0,
    piercingPower: 0,
    rateOfFire: 0,
    range: 0
  },
  {
    name: "Ogoun M31",
    type: "Plasma",
    cost: 400000,
    equipmentLevel: 3,
    kineticDefence: 0,
    energyDefence: 0,
    mobility: 0,
    stoppingPower: 0,
    piercingPower: 0,
    rateOfFire: 0,
    range: 0,
    accuracy: "00000",
    handling: 0,
    roundCapacity: "~8",
    action: "Full-auto",
    diode: "80nm x6"
  },
  {
    name: "Olympian",
    type: "Armour",
    cost: 5000000,
    equipmentLevel: 8,
    kineticDefence: "0000000SS",
    energyDefence: "0000000ES",
    mobility: "0000000000",
    stoppingPower: 0,
    piercingPower: 0,
    rateOfFire: 0,
    range: 0
  },
  {
    name: "Orca A7",
    type: "Rail",
    cost: 1800000,
    equipmentLevel: 4,
    kineticDefence: 0,
    energyDefence: 0,
    mobility: 0,
    stoppingPower: 0,
    piercingPower: 0,
    rateOfFire: 0,
    range: 0,
    accuracy: 0,
    handling: 0,
    roundCapacity: 6,
    action: "Semi-auto",
    bolt: "28mm"
  },
  {
    name: "Pallach Or2",
    type: "Laser",
    cost: 200000,
    equipmentLevel: 2,
    kineticDefence: 0,
    energyDefence: 0,
    mobility: 0,
    stoppingPower: 0,
    piercingPower: 0,
    rateOfFire: 0,
    range: 0,
    accuracy: 0,
    handling: 0,
    roundCapacity: "~5",
    action: "Full-auto",
    diode: "405nm"
  },
  {
    name: "Phorcys",
    type: "Armour",
    cost: 1200000,
    equipmentLevel: 6,
    kineticDefence: 0,
    energyDefence: 0,
    mobility: 0,
    stoppingPower: 0,
    piercingPower: 0,
    rateOfFire: 0,
    range: 0
  },
  {
    name: "Pioneer",
    type: "Armour",
    cost: 3500000,
    equipmentLevel: 7,
    kineticDefence: 0,
    energyDefence: 0,
    mobility: 0,
    stoppingPower: 0,
    piercingPower: 0,
    rateOfFire: 0,
    range: 0
  },
  {
    name: "Plasma Sticky",
    type: "Grenade",
    cost: 400000,
    equipmentLevel: 1,
    kineticDefence: 0,
    energyDefence: 0,
    mobility: 0,
    stoppingPower: 0,
    piercingPower: 0,
    rateOfFire: 0,
    range: 0,
    handling: 0
  },
  {
    name: "Power Armour",
    type: "Armour",
    cost: 9000000,
    equipmentLevel: 10,
    kineticDefence: "0000000",
    energyDefence: 0,
    mobility: 0,
    stoppingPower: 0,
    piercingPower: 0,
    rateOfFire: 0,
    range: 0
  },
  {
    name: "Ratio MK II",
    type: "Rail",
    cost: 2000000,
    equipmentLevel: 5,
    kineticDefence: 0,
    energyDefence: 0,
    mobility: 0,
    stoppingPower: 0,
    piercingPower: 0,
    rateOfFire: 0,
    range: 0,
    accuracy: 0,
    handling: 0,
    roundCapacity: "-3",
    action: "Bolt-action",
    calibre: "42mm"
  },
  {
    name: "Reactive Plating",
    type: "Armour",
    cost: 2000000,
    equipmentLevel: 6,
    kineticDefence: "0000 SE",
    energyDefence: 0,
    mobility: 0,
    stoppingPower: 0,
    piercingPower: 0,
    rateOfFire: 0,
    range: 0
  },
  {
    name: "Rinn-J",
    type: "Plasma",
    cost: 200000,
    equipmentLevel: 2,
    kineticDefence: 0,
    energyDefence: 0,
    mobility: 0,
    stoppingPower: 0,
    piercingPower: 0,
    rateOfFire: 0,
    range: 0,
    accuracy: 0,
    handling: 0,
    roundCapacity: "~16",
    action: "Full-auto",
    diode: "980nm"
  },
  {
    name: "Sabre 6",
    type: "Plasma",
    cost: 150000,
    equipmentLevel: 1,
    kineticDefence: 0,
    energyDefence: 0,
    mobility: 0,
    stoppingPower: 0,
    piercingPower: 0,
    rateOfFire: 0,
    range: 0,
    accuracy: "DOSSSSSASS",
    handling: "00000665",
    roundCapacity: "-28",
    action: "Semi-auto",
    diode: "1025nm"
  },
  {
    name: "Salamander Or2",
    type: "Special",
    cost: 800000,
    equipmentLevel: 4,
    kineticDefence: 0,
    energyDefence: 0,
    mobility: 0,
    stoppingPower: 0,
    piercingPower: 0,
    rateOfFire: 0,
    range: 0,
    accuracy: 0,
    handling: 0,
    roundCapacity: 0,
    action: "Thrower",
    calibre: "n/a",
    tankCapacity: "200L"
  },
  {
    name: "Sardonic-9",
    type: "Explosive/Plasma",
    cost: 2200000,
    equipmentLevel: 5,
    kineticDefence: 0,
    energyDefence: 0,
    mobility: 0,
    stoppingPower: 0,
    piercingPower: 0,
    rateOfFire: 0,
    range: 0,
    accuracy: 0,
    handling: 0,
    roundCapacity: "~12",
    action: "Rocket",
    diode: "1990nm"
  },
  {
    name: "Sharktooth-T751",
    type: "Plasma",
    cost: 400000,
    equipmentLevel: 4,
    kineticDefence: 0,
    energyDefence: 0,
    mobility: 0,
    stoppingPower: 0,
    piercingPower: 0,
    rateOfFire: 0,
    range: 0,
    accuracy: 0,
    handling: 0,
    roundCapacity: "~40",
    action: "Full-auto",
    diode: "1155nm"
  },
  {
    name: "Spatha 2100FP",
    type: "Kinetic",
    cost: 100000,
    equipmentLevel: 3,
    kineticDefence: 0,
    energyDefence: 0,
    mobility: 0,
    stoppingPower: 0,
    piercingPower: 0,
    rateOfFire: 0,
    range: 0,
    accuracy: 0,
    handling: 0,
    roundCapacity: "8",
    action: "Pump",
    calibre: "10ga"
  },
  {
    name: "Stark-4",
    type: "Explosive",
    cost: 700000,
    equipmentLevel: 5,
    kineticDefence: 0,
    energyDefence: 0,
    mobility: 0,
    stoppingPower: 0,
    piercingPower: 0,
    rateOfFire: 0,
    range: 0,
    accuracy: "000000",
    handling: 0,
    roundCapacity: "8",
    action: "Launcher",
    ordnance: "82mm"
  },
  {
    name: "Stasis",
    type: "Grenade",
    cost: 1000000,
    equipmentLevel: 2,
    kineticDefence: 0,
    energyDefence: 0,
    mobility: 0,
    stoppingPower: 0,
    piercingPower: 0,
    rateOfFire: 0,
    range: 0,
    handling: 0,
  },
  {
    name: "Starburst MK VI",
    type: "Laser",
    cost: 200000,
    equipmentLevel: 3,
    kineticDefence: 0,
    energyDefence: 0,
    mobility: 0,
    stoppingPower: 0,
    piercingPower: 0,
    rateOfFire: 0,
    range: 0,
    accuracy: 0,
    handling: 0,
    roundCapacity: "~10",
    action: "Semi-auto",
    diode: "4x675nm"
  },
  {
    name: "Survivalist",
    type: "Armour",
    cost: 500000,
    equipmentLevel: 5,
    kineticDefence: 0,
    energyDefence: 0,
    mobility: 0,
    stoppingPower: 0,
    piercingPower: 0,
    rateOfFire: 0,
    range: 0
  },
  {
    name: "Taser Baton",
    type: "Melee",
    cost: 50000,
    equipmentLevel: 1,
    kineticDefence: 0,
    energyDefence: 0,
    mobility: 0,
    stoppingPower: 0,
    piercingPower: 0,
    rateOfFire: 0,
    range: 0,
    handling: 0,
  },
  {
    name: "The EVI Platform",
    type: "Kinetic",
    cost: 700000,
    equipmentLevel: 4,
    kineticDefence: 0,
    energyDefence: 0,
    mobility: 0,
    stoppingPower: 0,
    piercingPower: 0,
    rateOfFire: 0,
    range: 0,
    accuracy: 0,
    handling: 0,
    roundCapacity: 32,
    action: "Select-fire",
    calibre: "6.16mm UNI"
  },
  {
    name: "The Ivan",
    type: "Kinetic",
    cost: 250000,
    equipmentLevel: 4,
    kineticDefence: 0,
    energyDefence: 0,
    mobility: 0,
    stoppingPower: 0,
    piercingPower: 0,
    rateOfFire: 0,
    range: 0,
    accuracy: 0,
    handling: 0,
    roundCapacity: 30,
    action: "Full-auto",
    calibre: "7.75mm SV"
  },
  {
    name: "UN200-42",
    type: "Plasma",
    cost: 400000,
    equipmentLevel: 3,
    kineticDefence: 0,
    energyDefence: 0,
    mobility: 0,
    stoppingPower: 0,
    piercingPower: 0,
    rateOfFire: 0,
    range: 0,
    accuracy: "~34",
    handling: "Full-auto",
    roundCapacity: 30,
    action: "Full-auto",
    diode: "980nm"
  },
  {
    name: "Vibro-Blade",
    type: "Melee",
    cost: 400000,
    equipmentLevel: 2,
    kineticDefence: 0,
    energyDefence: 0,
    mobility: 0,
    stoppingPower: 0,
    piercingPower: 0,
    rateOfFire: 0,
    range: 0,
    handling: "00000000"
  },
  {
    name: "Wastelander",
    type: "Armour",
    cost: 150000,
    equipmentLevel: 3,
    kineticDefence: "000000ORS",
    energyDefence: 0,
    mobility: 0,
    stoppingPower: 0,
    piercingPower: 0,
    rateOfFire: 0,
    range: 0
  },
  {
    name: "Wraithsong A4",
    type: "Rail",
    cost: 800000,
    equipmentLevel: 4,
    kineticDefence: 0,
    energyDefence: 0,
    mobility: 0,
    stoppingPower: 0,
    piercingPower: 0,
    rateOfFire: 0,
    range: 0,
    accuracy: 0,
    handling: 0,
    roundCapacity: 4,
    action: "Burst",
    bolt: "4mm ×3"
  }
];

const weapons = [];

const mechs = [];